// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use std::io::{BufRead, BufReader, BufWriter, Write};
use std::fs::File;

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct FdAcctfileRec {
    /// FD-ACCT-ID
    pub fd_acct_id: u64,
    /// FD-ACCT-DATA
    pub fd_acct_data: FixedString<289>,
}
impl std::fmt::Display for FdAcctfileRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.fd_acct_id, self.fd_acct_data)
    }
}
impl From<&str> for FdAcctfileRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for FdAcctfileRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl FdAcctfileRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AcctfileFile {
    /// FD-ACCTFILE-REC
    pub fd_acctfile_rec: FdAcctfileRec,
}
impl std::fmt::Display for AcctfileFile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.fd_acctfile_rec)
    }
}
impl From<&str> for AcctfileFile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for AcctfileFile {
    fn from(_s: String) -> Self { Self::default() }
}
impl AcctfileFile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct OutAcctRec {
    /// OUT-ACCT-ID
    pub out_acct_id: u64,
    /// OUT-ACCT-ACTIVE-STATUS
    pub out_acct_active_status: FixedString<1>,
    /// OUT-ACCT-CURR-BAL
    pub out_acct_curr_bal: Decimal /* 10,2 Signed */,
    /// OUT-ACCT-CREDIT-LIMIT
    pub out_acct_credit_limit: Decimal /* 10,2 Signed */,
    /// OUT-ACCT-CASH-CREDIT-LIMIT
    pub out_acct_cash_credit_limit: Decimal /* 10,2 Signed */,
    /// OUT-ACCT-OPEN-DATE
    pub out_acct_open_date: FixedString<10>,
    /// OUT-ACCT-EXPIRAION-DATE
    pub out_acct_expiraion_date: FixedString<10>,
    /// OUT-ACCT-REISSUE-DATE
    pub out_acct_reissue_date: FixedString<10>,
    /// OUT-ACCT-CURR-CYC-CREDIT
    pub out_acct_curr_cyc_credit: Decimal /* 10,2 Signed */,
    /// OUT-ACCT-CURR-CYC-DEBIT
    pub out_acct_curr_cyc_debit: PackedDecimal<12> /* Signed */,
    /// OUT-ACCT-GROUP-ID
    pub out_acct_group_id: FixedString<10>,
}
impl std::fmt::Display for OutAcctRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}", self.out_acct_id, self.out_acct_active_status, self.out_acct_curr_bal, self.out_acct_credit_limit, self.out_acct_cash_credit_limit, self.out_acct_open_date, self.out_acct_expiraion_date, self.out_acct_reissue_date, self.out_acct_curr_cyc_credit, self.out_acct_curr_cyc_debit, self.out_acct_group_id)
    }
}
impl From<&str> for OutAcctRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for OutAcctRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl OutAcctRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct OutFile {
    /// OUT-ACCT-REC
    pub out_acct_rec: OutAcctRec,
}
impl std::fmt::Display for OutFile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.out_acct_rec)
    }
}
impl From<&str> for OutFile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for OutFile {
    fn from(_s: String) -> Self { Self::default() }
}
impl OutFile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ArrArrayRec {
    /// ARR-ACCT-ID
    pub arr_acct_id: u64,
    /// ARR-ACCT-BAL
    pub arr_acct_bal: [ArrAcctBal; 5],
    /// ARR-FILLER
    pub arr_filler: FixedString<4>,
}
impl std::fmt::Display for ArrArrayRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.arr_acct_id, self.arr_filler)
    }
}
impl From<&str> for ArrArrayRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ArrArrayRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl ArrArrayRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ArrAcctBal {
    /// ARR-ACCT-CURR-BAL
    pub arr_acct_curr_bal: Decimal /* 10,2 Signed */,
    /// ARR-ACCT-CURR-CYC-DEBIT
    pub arr_acct_curr_cyc_debit: PackedDecimal<12> /* Signed */,
}
impl std::fmt::Display for ArrAcctBal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.arr_acct_curr_bal, self.arr_acct_curr_cyc_debit)
    }
}
impl From<&str> for ArrAcctBal {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ArrAcctBal {
    fn from(_s: String) -> Self { Self::default() }
}
impl ArrAcctBal {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ArryFile {
    /// ARR-ARRAY-REC
    pub arr_array_rec: ArrArrayRec,
}
impl std::fmt::Display for ArryFile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.arr_array_rec)
    }
}
impl From<&str> for ArryFile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ArryFile {
    fn from(_s: String) -> Self { Self::default() }
}
impl ArryFile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct VbrcFile {
    /// VBR-REC
    pub vbr_rec: FixedString<80>,
}
impl std::fmt::Display for VbrcFile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.vbr_rec)
    }
}
impl From<&str> for VbrcFile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for VbrcFile {
    fn from(_s: String) -> Self { Self::default() }
}
impl VbrcFile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AccountRecord {
    /// ACCT-ID
    pub acct_id: u64,
    /// ACCT-ACTIVE-STATUS
    pub acct_active_status: FixedString<1>,
    /// ACCT-CURR-BAL
    pub acct_curr_bal: Decimal /* 10,2 Signed */,
    /// ACCT-CREDIT-LIMIT
    pub acct_credit_limit: Decimal /* 10,2 Signed */,
    /// ACCT-CASH-CREDIT-LIMIT
    pub acct_cash_credit_limit: Decimal /* 10,2 Signed */,
    /// ACCT-OPEN-DATE
    pub acct_open_date: FixedString<10>,
    /// ACCT-EXPIRAION-DATE
    pub acct_expiraion_date: FixedString<10>,
    /// ACCT-REISSUE-DATE
    pub acct_reissue_date: FixedString<10>,
    /// ACCT-CURR-CYC-CREDIT
    pub acct_curr_cyc_credit: Decimal /* 10,2 Signed */,
    /// ACCT-CURR-CYC-DEBIT
    pub acct_curr_cyc_debit: Decimal /* 10,2 Signed */,
    /// ACCT-ADDR-ZIP
    pub acct_addr_zip: FixedString<10>,
    /// ACCT-GROUP-ID
    pub acct_group_id: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_105: FixedString<178>,
}
impl std::fmt::Display for AccountRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}", self.acct_id, self.acct_active_status, self.acct_curr_bal, self.acct_credit_limit, self.acct_cash_credit_limit, self.acct_open_date, self.acct_expiraion_date, self.acct_reissue_date, self.acct_curr_cyc_credit, self.acct_curr_cyc_debit, self.acct_addr_zip, self.acct_group_id, self._filler_105)
    }
}
impl From<&str> for AccountRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for AccountRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl AccountRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CodatecnRec {
    /// CODATECN-IN-REC
    pub codatecn_in_rec: CodatecnInRec,
    /// CODATECN-OUT-REC
    pub codatecn_out_rec: CodatecnOutRec,
    /// CODATECN-ERROR-MSG
    pub codatecn_error_msg: FixedString<38>,
}
impl std::fmt::Display for CodatecnRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.codatecn_in_rec, self.codatecn_out_rec, self.codatecn_error_msg)
    }
}
impl From<&str> for CodatecnRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CodatecnRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl CodatecnRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CodatecnInRec {
    /// CODATECN-TYPE
    pub codatecn_type: FixedString<1>,
    /// CODATECN-INP-DATE
    pub codatecn_inp_date: FixedString<20>,
    /// CODATECN-1INP
    pub codatecn_1inp: Codatecn1inp,
    /// CODATECN-2INP
    pub codatecn_2inp: Codatecn2inp,
}
impl std::fmt::Display for CodatecnInRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.codatecn_type, self.codatecn_inp_date, self.codatecn_1inp, self.codatecn_2inp)
    }
}
impl From<&str> for CodatecnInRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CodatecnInRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl CodatecnInRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Codatecn1inp {
    /// CODATECN-1YYYY
    pub codatecn_1yyyy: FixedString<4>,
    /// CODATECN-1MM
    pub codatecn_1mm: FixedString<2>,
    /// CODATECN-1DD
    pub codatecn_1dd: FixedString<2>,
    /// CODATECN-1FIL
    pub codatecn_1fil: FixedString<12>,
}
impl std::fmt::Display for Codatecn1inp {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.codatecn_1yyyy, self.codatecn_1mm, self.codatecn_1dd, self.codatecn_1fil)
    }
}
impl From<&str> for Codatecn1inp {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Codatecn1inp {
    fn from(_s: String) -> Self { Self::default() }
}
impl Codatecn1inp {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Codatecn2inp {
    /// CODATECN-1O-YYYY
    pub codatecn_1o_yyyy: FixedString<4>,
    /// CODATECN-1I-S1
    pub codatecn_1i_s1: FixedString<1>,
    /// CODATECN-1MM
    pub codatecn_1mm: FixedString<2>,
    /// CODATECN-1I-S2
    pub codatecn_1i_s2: FixedString<1>,
    /// CODATECN-2YY
    pub codatecn_2yy: FixedString<2>,
    /// CODATECN-2FIL
    pub codatecn_2fil: FixedString<10>,
}
impl std::fmt::Display for Codatecn2inp {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}", self.codatecn_1o_yyyy, self.codatecn_1i_s1, self.codatecn_1mm, self.codatecn_1i_s2, self.codatecn_2yy, self.codatecn_2fil)
    }
}
impl From<&str> for Codatecn2inp {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Codatecn2inp {
    fn from(_s: String) -> Self { Self::default() }
}
impl Codatecn2inp {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CodatecnOutRec {
    /// CODATECN-OUTTYPE
    pub codatecn_outtype: FixedString<1>,
    /// CODATECN-0UT-DATE
    pub codatecn_0ut_date: FixedString<20>,
    /// CODATECN-1OUT
    pub codatecn_1out: Codatecn1out,
    /// CODATECN-2OUT
    pub codatecn_2out: Codatecn2out,
}
impl std::fmt::Display for CodatecnOutRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.codatecn_outtype, self.codatecn_0ut_date, self.codatecn_1out, self.codatecn_2out)
    }
}
impl From<&str> for CodatecnOutRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CodatecnOutRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl CodatecnOutRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Codatecn1out {
    /// CODATECN-1O-YYYY
    pub codatecn_1o_yyyy: FixedString<4>,
    /// CODATECN-1O-S1
    pub codatecn_1o_s1: FixedString<1>,
    /// CODATECN-1O-MM
    pub codatecn_1o_mm: FixedString<2>,
    /// CODATECN-1O-S2
    pub codatecn_1o_s2: FixedString<1>,
    /// CODATECN-1O-DD
    pub codatecn_1o_dd: FixedString<2>,
    /// CODATECN-1OFIL
    pub codatecn_1ofil: FixedString<10>,
}
impl std::fmt::Display for Codatecn1out {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}", self.codatecn_1o_yyyy, self.codatecn_1o_s1, self.codatecn_1o_mm, self.codatecn_1o_s2, self.codatecn_1o_dd, self.codatecn_1ofil)
    }
}
impl From<&str> for Codatecn1out {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Codatecn1out {
    fn from(_s: String) -> Self { Self::default() }
}
impl Codatecn1out {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Codatecn2out {
    /// CODATECN-2O-YYYY
    pub codatecn_2o_yyyy: FixedString<4>,
    /// CODATECN-2O-MM
    pub codatecn_2o_mm: FixedString<2>,
    /// CODATECN-2O-DD
    pub codatecn_2o_dd: FixedString<2>,
    /// CODATECN-2OFIL
    pub codatecn_2ofil: FixedString<12>,
}
impl std::fmt::Display for Codatecn2out {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.codatecn_2o_yyyy, self.codatecn_2o_mm, self.codatecn_2o_dd, self.codatecn_2ofil)
    }
}
impl From<&str> for Codatecn2out {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Codatecn2out {
    fn from(_s: String) -> Self { Self::default() }
}
impl Codatecn2out {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AcctfileStatus {
    /// ACCTFILE-STAT1
    pub acctfile_stat1: FixedString<1>,
    /// ACCTFILE-STAT2
    pub acctfile_stat2: FixedString<1>,
}
impl std::fmt::Display for AcctfileStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.acctfile_stat1, self.acctfile_stat2)
    }
}
impl From<&str> for AcctfileStatus {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for AcctfileStatus {
    fn from(_s: String) -> Self { Self::default() }
}
impl AcctfileStatus {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct OutfileStatus {
    /// OUTFILE-STAT1
    pub outfile_stat1: FixedString<1>,
    /// OUTFILE-STAT2
    pub outfile_stat2: FixedString<1>,
}
impl std::fmt::Display for OutfileStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.outfile_stat1, self.outfile_stat2)
    }
}
impl From<&str> for OutfileStatus {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for OutfileStatus {
    fn from(_s: String) -> Self { Self::default() }
}
impl OutfileStatus {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ArryfileStatus {
    /// ARRYFILE-STAT1
    pub arryfile_stat1: FixedString<1>,
    /// ARRYFILE-STAT2
    pub arryfile_stat2: FixedString<1>,
}
impl std::fmt::Display for ArryfileStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.arryfile_stat1, self.arryfile_stat2)
    }
}
impl From<&str> for ArryfileStatus {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ArryfileStatus {
    fn from(_s: String) -> Self { Self::default() }
}
impl ArryfileStatus {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct VbrcfileStatus {
    /// VBRCFILE-STAT1
    pub vbrcfile_stat1: FixedString<1>,
    /// VBRCFILE-STAT2
    pub vbrcfile_stat2: FixedString<1>,
}
impl std::fmt::Display for VbrcfileStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.vbrcfile_stat1, self.vbrcfile_stat2)
    }
}
impl From<&str> for VbrcfileStatus {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for VbrcfileStatus {
    fn from(_s: String) -> Self { Self::default() }
}
impl VbrcfileStatus {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct IoStatus {
    /// IO-STAT1
    pub io_stat1: FixedString<1>,
    /// IO-STAT2
    pub io_stat2: FixedString<1>,
}
impl std::fmt::Display for IoStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.io_stat1, self.io_stat2)
    }
}
impl From<&str> for IoStatus {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for IoStatus {
    fn from(_s: String) -> Self { Self::default() }
}
impl IoStatus {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TwoBytesAlpha {
    /// TWO-BYTES-LEFT
    pub two_bytes_left: FixedString<1>,
    /// TWO-BYTES-RIGHT
    pub two_bytes_right: FixedString<1>,
}
impl std::fmt::Display for TwoBytesAlpha {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.two_bytes_left, self.two_bytes_right)
    }
}
impl From<&str> for TwoBytesAlpha {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TwoBytesAlpha {
    fn from(_s: String) -> Self { Self::default() }
}
impl TwoBytesAlpha {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct IoStatus04 {
    /// IO-STATUS-0401
    pub io_status_0401: u32,
    /// IO-STATUS-0403
    pub io_status_0403: u32,
}
impl std::fmt::Display for IoStatus04 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.io_status_0401, self.io_status_0403)
    }
}
impl From<&str> for IoStatus04 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for IoStatus04 {
    fn from(_s: String) -> Self { Self::default() }
}
impl IoStatus04 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct VbrcRec1 {
    /// VB1-ACCT-ID
    pub vb1_acct_id: u64,
    /// VB1-ACCT-ACTIVE-STATUS
    pub vb1_acct_active_status: FixedString<1>,
}
impl std::fmt::Display for VbrcRec1 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.vb1_acct_id, self.vb1_acct_active_status)
    }
}
impl From<&str> for VbrcRec1 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for VbrcRec1 {
    fn from(_s: String) -> Self { Self::default() }
}
impl VbrcRec1 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct VbrcRec2 {
    /// VB2-ACCT-ID
    pub vb2_acct_id: u64,
    /// VB2-ACCT-CURR-BAL
    pub vb2_acct_curr_bal: Decimal /* 10,2 Signed */,
    /// VB2-ACCT-CREDIT-LIMIT
    pub vb2_acct_credit_limit: Decimal /* 10,2 Signed */,
    /// VB2-ACCT-REISSUE-YYYY
    pub vb2_acct_reissue_yyyy: FixedString<4>,
}
impl std::fmt::Display for VbrcRec2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.vb2_acct_id, self.vb2_acct_curr_bal, self.vb2_acct_credit_limit, self.vb2_acct_reissue_yyyy)
    }
}
impl From<&str> for VbrcRec2 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for VbrcRec2 {
    fn from(_s: String) -> Self { Self::default() }
}
impl VbrcRec2 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsAcctReissueDate {
    /// WS-ACCT-REISSUE-YYYY
    pub ws_acct_reissue_yyyy: FixedString<4>,
    /// WS-FILLER-1
    pub ws_filler_1: FixedString<1>,
    /// WS-ACCT-REISSUE-MM
    pub ws_acct_reissue_mm: FixedString<2>,
    /// WS-FILLER-2
    pub ws_filler_2: FixedString<1>,
    /// WS-ACCT-REISSUE-DD
    pub ws_acct_reissue_dd: FixedString<2>,
}
impl std::fmt::Display for WsAcctReissueDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}", self.ws_acct_reissue_yyyy, self.ws_filler_1, self.ws_acct_reissue_mm, self.ws_filler_2, self.ws_acct_reissue_dd)
    }
}
impl From<&str> for WsAcctReissueDate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsAcctReissueDate {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsAcctReissueDate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// FD group: FD-ACCTFILE-REC
    pub fd_acctfile_rec: FixedString<297>,
    /// FD: FD-ACCT-ID
    pub fd_acct_id: u64,
    /// FD: FD-ACCT-DATA
    pub fd_acct_data: FixedString<289>,
    /// FD group: OUT-ACCT-REC
    pub out_acct_rec: FixedString<104>,
    /// FD: OUT-ACCT-ID
    pub out_acct_id: u64,
    /// FD: OUT-ACCT-ACTIVE-STATUS
    pub out_acct_active_status: FixedString<1>,
    /// FD: OUT-ACCT-CURR-BAL
    pub out_acct_curr_bal: Decimal /* 10,2 Signed */,
    /// FD: OUT-ACCT-CREDIT-LIMIT
    pub out_acct_credit_limit: Decimal /* 10,2 Signed */,
    /// FD: OUT-ACCT-CASH-CREDIT-LIMIT
    pub out_acct_cash_credit_limit: Decimal /* 10,2 Signed */,
    /// FD: OUT-ACCT-OPEN-DATE
    pub out_acct_open_date: FixedString<10>,
    /// FD: OUT-ACCT-EXPIRAION-DATE
    pub out_acct_expiraion_date: FixedString<10>,
    /// FD: OUT-ACCT-REISSUE-DATE
    pub out_acct_reissue_date: FixedString<10>,
    /// FD: OUT-ACCT-CURR-CYC-CREDIT
    pub out_acct_curr_cyc_credit: Decimal /* 10,2 Signed */,
    /// FD: OUT-ACCT-CURR-CYC-DEBIT
    pub out_acct_curr_cyc_debit: PackedDecimal<12> /* Signed */,
    /// FD: OUT-ACCT-GROUP-ID
    pub out_acct_group_id: FixedString<10>,
    /// FD group: ARR-ARRAY-REC
    pub arr_array_rec: FixedString<31>,
    /// FD: ARR-ACCT-ID
    pub arr_acct_id: u64,
    /// FD group: ARR-ACCT-BAL
    pub arr_acct_bal: FixedString<19>,
    /// FD: ARR-ACCT-CURR-BAL
    pub arr_acct_curr_bal: Decimal /* 10,2 Signed */,
    /// FD: ARR-ACCT-CURR-CYC-DEBIT
    pub arr_acct_curr_cyc_debit: PackedDecimal<12> /* Signed */,
    /// FD: ARR-FILLER
    pub arr_filler: FixedString<4>,
    /// FD: VBR-REC
    pub vbr_rec: FixedString<80>,
    /// ACCOUNT-RECORD
    pub account_record: AccountRecord,
    /// ACCT-ID
    pub acct_id: u64,
    /// ACCT-ACTIVE-STATUS
    pub acct_active_status: FixedString<1>,
    /// ACCT-CURR-BAL
    pub acct_curr_bal: Decimal /* 10,2 Signed */,
    /// ACCT-CREDIT-LIMIT
    pub acct_credit_limit: Decimal /* 10,2 Signed */,
    /// ACCT-CASH-CREDIT-LIMIT
    pub acct_cash_credit_limit: Decimal /* 10,2 Signed */,
    /// ACCT-OPEN-DATE
    pub acct_open_date: FixedString<10>,
    /// ACCT-EXPIRAION-DATE
    pub acct_expiraion_date: FixedString<10>,
    /// ACCT-REISSUE-DATE
    pub acct_reissue_date: FixedString<10>,
    /// ACCT-CURR-CYC-CREDIT
    pub acct_curr_cyc_credit: Decimal /* 10,2 Signed */,
    /// ACCT-CURR-CYC-DEBIT
    pub acct_curr_cyc_debit: Decimal /* 10,2 Signed */,
    /// ACCT-ADDR-ZIP
    pub acct_addr_zip: FixedString<10>,
    /// ACCT-GROUP-ID
    pub acct_group_id: FixedString<10>,
    /// CODATECN-REC
    pub codatecn_rec: CodatecnRec,
    /// CODATECN-IN-REC
    pub codatecn_in_rec: CodatecnInRec,
    /// CODATECN-TYPE
    pub codatecn_type: FixedString<1>,
    /// CODATECN-INP-DATE
    pub codatecn_inp_date: FixedString<20>,
    /// CODATECN-OUT-REC
    pub codatecn_out_rec: CodatecnOutRec,
    /// CODATECN-OUTTYPE
    pub codatecn_outtype: FixedString<1>,
    /// CODATECN-0UT-DATE
    pub codatecn_0ut_date: FixedString<20>,
    /// CODATECN-ERROR-MSG
    pub codatecn_error_msg: FixedString<38>,
    /// ACCTFILE-STATUS
    pub acctfile_status: AcctfileStatus,
    /// ACCTFILE-STAT1
    pub acctfile_stat1: FixedString<1>,
    /// ACCTFILE-STAT2
    pub acctfile_stat2: FixedString<1>,
    /// OUTFILE-STATUS
    pub outfile_status: OutfileStatus,
    /// OUTFILE-STAT1
    pub outfile_stat1: FixedString<1>,
    /// OUTFILE-STAT2
    pub outfile_stat2: FixedString<1>,
    /// ARRYFILE-STATUS
    pub arryfile_status: ArryfileStatus,
    /// ARRYFILE-STAT1
    pub arryfile_stat1: FixedString<1>,
    /// ARRYFILE-STAT2
    pub arryfile_stat2: FixedString<1>,
    /// VBRCFILE-STATUS
    pub vbrcfile_status: VbrcfileStatus,
    /// VBRCFILE-STAT1
    pub vbrcfile_stat1: FixedString<1>,
    /// VBRCFILE-STAT2
    pub vbrcfile_stat2: FixedString<1>,
    /// IO-STATUS
    pub io_status: IoStatus,
    /// IO-STAT1
    pub io_stat1: FixedString<1>,
    /// IO-STAT2
    pub io_stat2: FixedString<1>,
    /// TWO-BYTES-BINARY
    pub two_bytes_binary: u32,
    /// TWO-BYTES-ALPHA
    pub two_bytes_alpha: TwoBytesAlpha,
    /// TWO-BYTES-LEFT
    pub two_bytes_left: FixedString<1>,
    /// TWO-BYTES-RIGHT
    pub two_bytes_right: FixedString<1>,
    /// IO-STATUS-04
    pub io_status_04: IoStatus04,
    /// IO-STATUS-0401
    pub io_status_0401: u32,
    /// IO-STATUS-0403
    pub io_status_0403: u32,
    /// APPL-RESULT
    pub appl_result: i32,
    /// END-OF-FILE
    pub end_of_file: FixedString<1>,
    /// ABCODE
    pub abcode: i32,
    /// TIMING
    pub timing: i32,
    /// WS-RECD-LEN
    pub ws_recd_len: u32,
    /// VBRC-REC1
    pub vbrc_rec1: VbrcRec1,
    /// VB1-ACCT-ID
    pub vb1_acct_id: u64,
    /// VB1-ACCT-ACTIVE-STATUS
    pub vb1_acct_active_status: FixedString<1>,
    /// VBRC-REC2
    pub vbrc_rec2: VbrcRec2,
    /// VB2-ACCT-ID
    pub vb2_acct_id: u64,
    /// VB2-ACCT-CURR-BAL
    pub vb2_acct_curr_bal: Decimal /* 10,2 Signed */,
    /// VB2-ACCT-CREDIT-LIMIT
    pub vb2_acct_credit_limit: Decimal /* 10,2 Signed */,
    /// VB2-ACCT-REISSUE-YYYY
    pub vb2_acct_reissue_yyyy: FixedString<4>,
    /// WS-ACCT-REISSUE-DATE
    pub ws_acct_reissue_date: WsAcctReissueDate,
    /// WS-ACCT-REISSUE-YYYY
    pub ws_acct_reissue_yyyy: FixedString<4>,
    /// WS-FILLER-1
    pub ws_filler_1: FixedString<1>,
    /// WS-ACCT-REISSUE-MM
    pub ws_acct_reissue_mm: FixedString<2>,
    /// WS-FILLER-2
    pub ws_filler_2: FixedString<1>,
    /// WS-ACCT-REISSUE-DD
    pub ws_acct_reissue_dd: FixedString<2>,
    /// WS-REISSUE-DATE
    pub ws_reissue_date: FixedString<10>,
    /// File status for ACCTFILE-FILE
    pub _fs_acctfile_file: FileStatus,
    /// File handle for ACCTFILE-FILE
    pub _fh_acctfile_file: CobolFile,
    /// File status for OUT-FILE
    pub _fs_out_file: FileStatus,
    /// File handle for OUT-FILE
    pub _fh_out_file: CobolFile,
    /// File status for ARRY-FILE
    pub _fs_arry_file: FileStatus,
    /// File handle for ARRY-FILE
    pub _fh_arry_file: CobolFile,
    /// File status for VBRC-FILE
    pub _fs_vbrc_file: FileStatus,
    /// File handle for VBRC-FILE
    pub _fh_vbrc_file: CobolFile,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            fd_acctfile_rec: Default::default(),
            fd_acct_id: Default::default(),
            fd_acct_data: Default::default(),
            out_acct_rec: Default::default(),
            out_acct_id: Default::default(),
            out_acct_active_status: Default::default(),
            out_acct_curr_bal: Default::default(),
            out_acct_credit_limit: Default::default(),
            out_acct_cash_credit_limit: Default::default(),
            out_acct_open_date: Default::default(),
            out_acct_expiraion_date: Default::default(),
            out_acct_reissue_date: Default::default(),
            out_acct_curr_cyc_credit: Default::default(),
            out_acct_curr_cyc_debit: Default::default(),
            out_acct_group_id: Default::default(),
            arr_array_rec: Default::default(),
            arr_acct_id: Default::default(),
            arr_acct_bal: Default::default(),
            arr_acct_curr_bal: Default::default(),
            arr_acct_curr_cyc_debit: Default::default(),
            arr_filler: Default::default(),
            vbr_rec: Default::default(),
            account_record: Default::default(),
            acct_id: Default::default(),
            acct_active_status: Default::default(),
            acct_curr_bal: Default::default(),
            acct_credit_limit: Default::default(),
            acct_cash_credit_limit: Default::default(),
            acct_open_date: Default::default(),
            acct_expiraion_date: Default::default(),
            acct_reissue_date: Default::default(),
            acct_curr_cyc_credit: Default::default(),
            acct_curr_cyc_debit: Default::default(),
            acct_addr_zip: Default::default(),
            acct_group_id: Default::default(),
            codatecn_rec: Default::default(),
            codatecn_in_rec: Default::default(),
            codatecn_type: Default::default(),
            codatecn_inp_date: Default::default(),
            codatecn_out_rec: Default::default(),
            codatecn_outtype: Default::default(),
            codatecn_0ut_date: Default::default(),
            codatecn_error_msg: Default::default(),
            acctfile_status: Default::default(),
            acctfile_stat1: Default::default(),
            acctfile_stat2: Default::default(),
            outfile_status: Default::default(),
            outfile_stat1: Default::default(),
            outfile_stat2: Default::default(),
            arryfile_status: Default::default(),
            arryfile_stat1: Default::default(),
            arryfile_stat2: Default::default(),
            vbrcfile_status: Default::default(),
            vbrcfile_stat1: Default::default(),
            vbrcfile_stat2: Default::default(),
            io_status: Default::default(),
            io_stat1: Default::default(),
            io_stat2: Default::default(),
            two_bytes_binary: Default::default(),
            two_bytes_alpha: Default::default(),
            two_bytes_left: Default::default(),
            two_bytes_right: Default::default(),
            io_status_04: Default::default(),
            io_status_0401: Default::default(),
            io_status_0403: Default::default(),
            appl_result: Default::default(),
            end_of_file: FixedString::from_str("N"),
            abcode: Default::default(),
            timing: Default::default(),
            ws_recd_len: Default::default(),
            vbrc_rec1: Default::default(),
            vb1_acct_id: Default::default(),
            vb1_acct_active_status: Default::default(),
            vbrc_rec2: Default::default(),
            vb2_acct_id: Default::default(),
            vb2_acct_curr_bal: Default::default(),
            vb2_acct_credit_limit: Default::default(),
            vb2_acct_reissue_yyyy: Default::default(),
            ws_acct_reissue_date: Default::default(),
            ws_acct_reissue_yyyy: Default::default(),
            ws_filler_1: Default::default(),
            ws_acct_reissue_mm: Default::default(),
            ws_filler_2: Default::default(),
            ws_acct_reissue_dd: Default::default(),
            ws_reissue_date: Default::default(),
            _fs_acctfile_file: FileStatus::Success,
            _fh_acctfile_file: CobolFile::Closed,
            _fs_out_file: FileStatus::Success,
            _fh_out_file: CobolFile::Closed,
            _fs_arry_file: FileStatus::Success,
            _fh_arry_file: CobolFile::Closed,
            _fs_vbrc_file: FileStatus::Success,
            _fh_vbrc_file: CobolFile::Closed,
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// 0000-ACCTFILE-OPEN
fn p_0000_acctfile_open(state: &mut ProgramState) {
    p_2000_outfile_open(state);
    p_3000_arrfile_open(state);
    p_4000_vbrfile_open(state);
    while !(&format!("{}", state.end_of_file) == &"Y".to_string()) {
        // SKIP: unresolved ref
    }
    p_9000_acctfile_close(state);
    println!("{}", "END OF EXECUTION OF PROGRAM CBACT01C");
    { let _ = state._fh_acctfile_file.close();
        let _ = state._fh_out_file.close();
        let _ = state._fh_arry_file.close();
        let _ = state._fh_vbrc_file.close();
        return; }
}

/// 1000-ACCTFILE-GET-NEXT
fn p_1000_acctfile_get_next(state: &mut ProgramState) {
    acctfile_file_read(state);
    if { let _s = format!("{}", state.acctfile_status); _s.trim().to_string() } == "00".to_string() {
        state.appl_result = 0 as i32;
        state.arr_array_rec = Default::default();
        p_1100_display_acct_record(state);
        p_1300_popul_acct_record(state);
        p_1350_write_acct_record(state);
        p_1400_popul_array_record(state);
        p_1450_write_arry_record(state);
        state.vbrc_rec1 = Default::default();
        p_1500_popul_vbrc_record(state);
        p_1550_write_vb1_record(state);
        p_1575_write_vb2_record(state);
    } else {
        if { let _s = format!("{}", state.acctfile_status); _s.trim().to_string() } == "10".to_string() {
            state.appl_result = 16 as i32;
        } else {
            state.appl_result = 12 as i32;
        }
    }
    if state.appl_result == 0 {
    } else {
        if state.appl_result == 0 {
            state.end_of_file = "Y".into();
        } else {
            println!("{}", "ERROR READING ACCOUNT FILE");
            {
                let mut _bytes = vec![b' '; 2];
                { let _src = state.acctfile_status.acctfile_stat1.as_bytes(); let _end = (0+1).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
                { let _src = state.acctfile_status.acctfile_stat2.as_bytes(); let _end = (1+1).min(_bytes.len()); let _cl = _src.len().min(_end-1); _bytes[1..1+_cl].copy_from_slice(&_src[.._cl]); }
                let _len = _bytes.len();
                if _len > 0 { let _end = _len.min(0+1); state.io_status.io_stat1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
                if _len > 1 { let _end = _len.min(1+1); state.io_status.io_stat2 = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
            }
            p_9910_display_io_status(state);
            p_9999_abend_program(state);
        }
    }
}

/// 1100-DISPLAY-ACCT-RECORD
fn p_1100_display_acct_record(state: &mut ProgramState) {
    println!("{}{}", "ACCT-ID                 :", state.account_record.acct_id);
    println!("{}{}", "ACCT-ACTIVE-STATUS      :", state.account_record.acct_active_status);
    println!("{}{}", "ACCT-CURR-BAL           :", state.account_record.acct_curr_bal);
    println!("{}{}", "ACCT-CREDIT-LIMIT       :", state.account_record.acct_credit_limit);
    println!("{}{}", "ACCT-CASH-CREDIT-LIMIT  :", state.account_record.acct_cash_credit_limit);
    println!("{}{}", "ACCT-OPEN-DATE          :", state.account_record.acct_open_date);
    println!("{}{}", "ACCT-EXPIRAION-DATE     :", state.account_record.acct_expiraion_date);
    println!("{}{}", "ACCT-REISSUE-DATE       :", state.account_record.acct_reissue_date);
    println!("{}{}", "ACCT-CURR-CYC-CREDIT    :", state.account_record.acct_curr_cyc_credit);
    println!("{}{}", "ACCT-CURR-CYC-DEBIT     :", state.account_record.acct_curr_cyc_debit);
    println!("{}{}", "ACCT-GROUP-ID           :", state.account_record.acct_group_id);
    println!("{}", "-------------------------------------------------");
}

/// 1300-POPUL-ACCT-RECORD
fn p_1300_popul_acct_record(state: &mut ProgramState) {
    state.out_acct_id = state.account_record.acct_id.clone();
    state.out_acct_active_status = FixedString::copy_from(&state.account_record.acct_active_status);
    state.out_acct_curr_bal = Decimal::from_i64(state.account_record.acct_curr_bal.value, state.account_record.acct_curr_bal.scale);
    state.out_acct_credit_limit = Decimal::from_i64(state.account_record.acct_credit_limit.value, state.account_record.acct_credit_limit.scale);
    state.out_acct_cash_credit_limit = Decimal::from_i64(state.account_record.acct_cash_credit_limit.value, state.account_record.acct_cash_credit_limit.scale);
    state.out_acct_open_date = FixedString::copy_from(&state.account_record.acct_open_date);
    state.out_acct_expiraion_date = FixedString::copy_from(&state.account_record.acct_expiraion_date);
    state.codatecn_rec.codatecn_in_rec.codatecn_inp_date = FixedString::copy_from(&state.account_record.acct_reissue_date);
    state.ws_reissue_date = FixedString::copy_from(&state.account_record.acct_reissue_date);
    state.codatecn_rec.codatecn_in_rec.codatecn_type = "2".into();
    state.codatecn_rec.codatecn_out_rec.codatecn_outtype = "2".into();
    {
        let mut _p1 = (state.codatecn_rec).clone();
        cobdatft(&mut _p1);
        state.codatecn_rec = _p1;
    }
    state.out_acct_reissue_date = FixedString::copy_from(&state.codatecn_rec.codatecn_out_rec.codatecn_0ut_date);
    state.out_acct_curr_cyc_credit = Decimal::from_i64(state.account_record.acct_curr_cyc_credit.value, state.account_record.acct_curr_cyc_credit.scale);
    if format!("{}", state.account_record.acct_curr_cyc_debit).trim() == "0" {
        state.out_acct_curr_cyc_debit = (2525.00).into();
    }
    state.out_acct_group_id = FixedString::copy_from(&state.account_record.acct_group_id);
}

/// 1350-WRITE-ACCT-RECORD
fn p_1350_write_acct_record(state: &mut ProgramState) {
    out_acct_rec_write(state);
    if ({ let _s = format!("{}", state.outfile_status); _s.trim().to_string() } != "00".to_string()) && ({ let _s = format!("{}", state.outfile_status); _s.trim().to_string() } != "10".to_string()) {
        println!("{}{}", "ACCOUNT FILE WRITE STATUS IS:", state.outfile_status);
        {
            let mut _bytes = vec![b' '; 2];
            { let _src = state.outfile_status.outfile_stat1.as_bytes(); let _end = (0+1).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
            { let _src = state.outfile_status.outfile_stat2.as_bytes(); let _end = (1+1).min(_bytes.len()); let _cl = _src.len().min(_end-1); _bytes[1..1+_cl].copy_from_slice(&_src[.._cl]); }
            let _len = _bytes.len();
            if _len > 0 { let _end = _len.min(0+1); state.io_status.io_stat1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 1 { let _end = _len.min(1+1); state.io_status.io_stat2 = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        }
        p_9910_display_io_status(state);
        p_9999_abend_program(state);
    }
}

/// 1400-POPUL-ARRAY-RECORD
fn p_1400_popul_array_record(state: &mut ProgramState) {
    state.arr_acct_id = state.account_record.acct_id.clone();
    state.arr_acct_curr_bal = Decimal::from_i64(state.account_record.acct_curr_bal.value, state.account_record.acct_curr_bal.scale);
    state.arr_acct_curr_cyc_debit = (1005.00).into();
    state.arr_acct_curr_bal = Decimal::from_i64(state.account_record.acct_curr_bal.value, state.account_record.acct_curr_bal.scale);
    state.arr_acct_curr_cyc_debit = (1525.00).into();
    state.arr_acct_curr_bal = (-1025.00).into();
    state.arr_acct_curr_cyc_debit = (-2500.00).into();
}

/// 1450-WRITE-ARRY-RECORD
fn p_1450_write_arry_record(state: &mut ProgramState) {
    arr_array_rec_write(state);
    if ({ let _s = format!("{}", state.arryfile_status); _s.trim().to_string() } != "00".to_string()) && ({ let _s = format!("{}", state.arryfile_status); _s.trim().to_string() } != "10".to_string()) {
        println!("{}{}", "ACCOUNT FILE WRITE STATUS IS:", state.arryfile_status);
        {
            let mut _bytes = vec![b' '; 2];
            { let _src = state.arryfile_status.arryfile_stat1.as_bytes(); let _end = (0+1).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
            { let _src = state.arryfile_status.arryfile_stat2.as_bytes(); let _end = (1+1).min(_bytes.len()); let _cl = _src.len().min(_end-1); _bytes[1..1+_cl].copy_from_slice(&_src[.._cl]); }
            let _len = _bytes.len();
            if _len > 0 { let _end = _len.min(0+1); state.io_status.io_stat1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 1 { let _end = _len.min(1+1); state.io_status.io_stat2 = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        }
        p_9910_display_io_status(state);
        p_9999_abend_program(state);
    }
}

/// 1500-POPUL-VBRC-RECORD
fn p_1500_popul_vbrc_record(state: &mut ProgramState) {
    state.vbrc_rec1.vb1_acct_id = state.account_record.acct_id.clone();
    state.vbrc_rec2.vb2_acct_id = state.account_record.acct_id.clone();
    state.vbrc_rec1.vb1_acct_active_status = FixedString::copy_from(&state.account_record.acct_active_status);
    state.vbrc_rec2.vb2_acct_curr_bal = Decimal::from_i64(state.account_record.acct_curr_bal.value, state.account_record.acct_curr_bal.scale);
    state.vbrc_rec2.vb2_acct_credit_limit = Decimal::from_i64(state.account_record.acct_credit_limit.value, state.account_record.acct_credit_limit.scale);
    state.vbrc_rec2.vb2_acct_reissue_yyyy = FixedString::copy_from(&state.ws_acct_reissue_date.ws_acct_reissue_yyyy);
    println!("{}{}", "VBRC-REC1:", state.vbrc_rec1);
    println!("{}{}", "VBRC-REC2:", state.vbrc_rec2);
}

/// 1550-WRITE-VB1-RECORD
fn p_1550_write_vb1_record(state: &mut ProgramState) {
    state.ws_recd_len = 12 as u32;
    { let _s = (1 - 1) as usize; let _l = (state.ws_recd_len) as usize; let _sv = state.vbrc_rec1.to_string(); let _src = _sv.as_bytes(); let _dst = state.vbr_rec.as_bytes_mut(); let _cl = _l.min(_src.len()).min(_dst.len() - _s); _dst[_s.._s+_cl].copy_from_slice(&_src[.._cl]); }
    vbr_rec_write(state);
    if ({ let _s = format!("{}", state.vbrcfile_status); _s.trim().to_string() } != "00".to_string()) && ({ let _s = format!("{}", state.vbrcfile_status); _s.trim().to_string() } != "10".to_string()) {
        println!("{}{}", "ACCOUNT FILE WRITE STATUS IS:", state.vbrcfile_status);
        {
            let mut _bytes = vec![b' '; 2];
            { let _src = state.vbrcfile_status.vbrcfile_stat1.as_bytes(); let _end = (0+1).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
            { let _src = state.vbrcfile_status.vbrcfile_stat2.as_bytes(); let _end = (1+1).min(_bytes.len()); let _cl = _src.len().min(_end-1); _bytes[1..1+_cl].copy_from_slice(&_src[.._cl]); }
            let _len = _bytes.len();
            if _len > 0 { let _end = _len.min(0+1); state.io_status.io_stat1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 1 { let _end = _len.min(1+1); state.io_status.io_stat2 = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        }
        p_9910_display_io_status(state);
        p_9999_abend_program(state);
    }
}

/// 1575-WRITE-VB2-RECORD
fn p_1575_write_vb2_record(state: &mut ProgramState) {
    state.ws_recd_len = 39 as u32;
    { let _s = (1 - 1) as usize; let _l = (state.ws_recd_len) as usize; let _sv = state.vbrc_rec2.to_string(); let _src = _sv.as_bytes(); let _dst = state.vbr_rec.as_bytes_mut(); let _cl = _l.min(_src.len()).min(_dst.len() - _s); _dst[_s.._s+_cl].copy_from_slice(&_src[.._cl]); }
    vbr_rec_write(state);
    if ({ let _s = format!("{}", state.vbrcfile_status); _s.trim().to_string() } != "00".to_string()) && ({ let _s = format!("{}", state.vbrcfile_status); _s.trim().to_string() } != "10".to_string()) {
        println!("{}{}", "ACCOUNT FILE WRITE STATUS IS:", state.vbrcfile_status);
        {
            let mut _bytes = vec![b' '; 2];
            { let _src = state.vbrcfile_status.vbrcfile_stat1.as_bytes(); let _end = (0+1).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
            { let _src = state.vbrcfile_status.vbrcfile_stat2.as_bytes(); let _end = (1+1).min(_bytes.len()); let _cl = _src.len().min(_end-1); _bytes[1..1+_cl].copy_from_slice(&_src[.._cl]); }
            let _len = _bytes.len();
            if _len > 0 { let _end = _len.min(0+1); state.io_status.io_stat1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 1 { let _end = _len.min(1+1); state.io_status.io_stat2 = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        }
        p_9910_display_io_status(state);
        p_9999_abend_program(state);
    }
}

/// 0000-ACCTFILE-OPEN
fn p_0000_acctfile_open_2(state: &mut ProgramState) {
    state.appl_result = 8 as i32;
    acctfile_file_open_input(state);
    if { let _s = format!("{}", state.acctfile_status); _s.trim().to_string() } == "00".to_string() {
        state.appl_result = 0 as i32;
    } else {
        state.appl_result = 12 as i32;
    }
    if state.appl_result == 0 {
    } else {
        println!("{}", "ERROR OPENING ACCTFILE");
        {
            let mut _bytes = vec![b' '; 2];
            { let _src = state.acctfile_status.acctfile_stat1.as_bytes(); let _end = (0+1).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
            { let _src = state.acctfile_status.acctfile_stat2.as_bytes(); let _end = (1+1).min(_bytes.len()); let _cl = _src.len().min(_end-1); _bytes[1..1+_cl].copy_from_slice(&_src[.._cl]); }
            let _len = _bytes.len();
            if _len > 0 { let _end = _len.min(0+1); state.io_status.io_stat1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 1 { let _end = _len.min(1+1); state.io_status.io_stat2 = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        }
        p_9910_display_io_status(state);
        p_9999_abend_program(state);
    }
}

/// 2000-OUTFILE-OPEN
fn p_2000_outfile_open(state: &mut ProgramState) {
    state.appl_result = 8 as i32;
    out_file_open_output(state);
    if { let _s = format!("{}", state.outfile_status); _s.trim().to_string() } == "00".to_string() {
        state.appl_result = 0 as i32;
    } else {
        state.appl_result = 12 as i32;
    }
    if state.appl_result == 0 {
    } else {
        println!("{}{}", "ERROR OPENING OUTFILE", state.outfile_status);
        {
            let mut _bytes = vec![b' '; 2];
            { let _src = state.outfile_status.outfile_stat1.as_bytes(); let _end = (0+1).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
            { let _src = state.outfile_status.outfile_stat2.as_bytes(); let _end = (1+1).min(_bytes.len()); let _cl = _src.len().min(_end-1); _bytes[1..1+_cl].copy_from_slice(&_src[.._cl]); }
            let _len = _bytes.len();
            if _len > 0 { let _end = _len.min(0+1); state.io_status.io_stat1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 1 { let _end = _len.min(1+1); state.io_status.io_stat2 = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        }
        p_9910_display_io_status(state);
        p_9999_abend_program(state);
    }
}

/// 3000-ARRFILE-OPEN
fn p_3000_arrfile_open(state: &mut ProgramState) {
    state.appl_result = 8 as i32;
    arry_file_open_output(state);
    if { let _s = format!("{}", state.arryfile_status); _s.trim().to_string() } == "00".to_string() {
        state.appl_result = 0 as i32;
    } else {
        state.appl_result = 12 as i32;
    }
    if state.appl_result == 0 {
    } else {
        println!("{}{}", "ERROR OPENING ARRAYFILE", state.arryfile_status);
        {
            let mut _bytes = vec![b' '; 2];
            { let _src = state.arryfile_status.arryfile_stat1.as_bytes(); let _end = (0+1).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
            { let _src = state.arryfile_status.arryfile_stat2.as_bytes(); let _end = (1+1).min(_bytes.len()); let _cl = _src.len().min(_end-1); _bytes[1..1+_cl].copy_from_slice(&_src[.._cl]); }
            let _len = _bytes.len();
            if _len > 0 { let _end = _len.min(0+1); state.io_status.io_stat1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 1 { let _end = _len.min(1+1); state.io_status.io_stat2 = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        }
        p_9910_display_io_status(state);
        p_9999_abend_program(state);
    }
}

/// 4000-VBRFILE-OPEN
fn p_4000_vbrfile_open(state: &mut ProgramState) {
    state.appl_result = 8 as i32;
    vbrc_file_open_output(state);
    if { let _s = format!("{}", state.vbrcfile_status); _s.trim().to_string() } == "00".to_string() {
        state.appl_result = 0 as i32;
    } else {
        state.appl_result = 12 as i32;
    }
    if state.appl_result == 0 {
    } else {
        println!("{}{}", "ERROR OPENING VBRC FILE", state.vbrcfile_status);
        {
            let mut _bytes = vec![b' '; 2];
            { let _src = state.vbrcfile_status.vbrcfile_stat1.as_bytes(); let _end = (0+1).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
            { let _src = state.vbrcfile_status.vbrcfile_stat2.as_bytes(); let _end = (1+1).min(_bytes.len()); let _cl = _src.len().min(_end-1); _bytes[1..1+_cl].copy_from_slice(&_src[.._cl]); }
            let _len = _bytes.len();
            if _len > 0 { let _end = _len.min(0+1); state.io_status.io_stat1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 1 { let _end = _len.min(1+1); state.io_status.io_stat2 = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        }
        p_9910_display_io_status(state);
        p_9999_abend_program(state);
    }
}

/// 9000-ACCTFILE-CLOSE
fn p_9000_acctfile_close(state: &mut ProgramState) {
    // SKIP: unresolved ref
}

/// APPL-RESULT
fn p_appl_result(state: &mut ProgramState) {
    acctfile_file_close(state);
    if { let _s = format!("{}", state.acctfile_status); _s.trim().to_string() } == "00".to_string() {
        state.appl_result -= state.appl_result;
    } else {
        // SKIP: unresolved ref
    }
    if state.appl_result == 0 {
    } else {
        println!("{}", "ERROR CLOSING ACCOUNT FILE");
        {
            let mut _bytes = vec![b' '; 2];
            { let _src = state.acctfile_status.acctfile_stat1.as_bytes(); let _end = (0+1).min(_bytes.len()); let _cl = _src.len().min(_end-0); _bytes[0..0+_cl].copy_from_slice(&_src[.._cl]); }
            { let _src = state.acctfile_status.acctfile_stat2.as_bytes(); let _end = (1+1).min(_bytes.len()); let _cl = _src.len().min(_end-1); _bytes[1..1+_cl].copy_from_slice(&_src[.._cl]); }
            let _len = _bytes.len();
            if _len > 0 { let _end = _len.min(0+1); state.io_status.io_stat1 = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 1 { let _end = _len.min(1+1); state.io_status.io_stat2 = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
        }
        p_9910_display_io_status(state);
        p_9999_abend_program(state);
    }
}

/// 9999-ABEND-PROGRAM
fn p_9999_abend_program(state: &mut ProgramState) {
    println!("{}", "ABENDING PROGRAM");
    state.timing = 0 as i32;
    state.abcode = 999 as i32;
    {
        let mut _p1 = (state.abcode).clone();
        let mut _p2 = (state.timing).clone();
        cee3abd(&mut _p1, &mut _p2);
        state.abcode = _p1;
        state.timing = _p2;
    }
}

/// 9910-DISPLAY-IO-STATUS
fn p_9910_display_io_status(state: &mut ProgramState) {
    if state.io_status.to_string().trim() != "" {
    }
    { /* refmod MOVE to struct IO-STATUS-04 skipped */ }
    state.two_bytes_binary = 0 as u32;
    state.two_bytes_alpha.two_bytes_right = FixedString::copy_from(&state.io_status.io_stat2);
    state.io_status_04.io_status_0403 = state.two_bytes_binary as u32;
    println!("{}{}", "FILE STATUS IS: NNNN", state.io_status_04);
    {
        let _bytes = b"0000";
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+1); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.io_status_04.io_status_0401 = _s.parse().unwrap_or_default(); }
        if _len > 1 { let _end = _len.min(1+3); let _s = String::from_utf8_lossy(&_bytes[1.._end]).trim().to_string(); state.io_status_04.io_status_0403 = _s.parse().unwrap_or_default(); }
    }
    { /* refmod MOVE to struct IO-STATUS-04 skipped */ }
    println!("{}{}", "FILE STATUS IS: NNNN", state.io_status_04);
}

/// STUB: p__unnamed
fn p__unnamed(state: &mut ProgramState) {
    // SKIP: unresolved ref
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// OPEN INPUT ACCTFILE-FILE
fn acctfile_file_open_input(state: &mut ProgramState) {
    let path = std::env::var("ACCTFILE_FILE").unwrap_or("acctfile_file.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_acctfile_file = handle; state._fs_acctfile_file = FileStatus::Success; }
        Err(_) => { state._fs_acctfile_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_acctfile_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN OUTPUT ACCTFILE-FILE
fn acctfile_file_open_output(state: &mut ProgramState) {
    let path = std::env::var("ACCTFILE_FILE").unwrap_or("acctfile_file.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_acctfile_file = handle; state._fs_acctfile_file = FileStatus::Success; }
        Err(_) => { state._fs_acctfile_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_acctfile_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// READ ACCTFILE-FILE
fn acctfile_file_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_acctfile_file.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(300);
            if _len > 0 { let _end = _len.min(0+11); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.fd_acct_id = _s.parse().unwrap_or_default(); }
            if _len > 11 { let _end = _len.min(11+289); state.fd_acct_data = FixedString::from(String::from_utf8_lossy(&_bytes[11.._end])); }
            state._fs_acctfile_file = FileStatus::Success;
    { let _s = format!("{}", state._fs_acctfile_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(FileStatus::AtEnd) => {
            state._fs_acctfile_file = FileStatus::AtEnd;
    { let _s = format!("{}", state._fs_acctfile_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(e) => {
            state._fs_acctfile_file = e.clone();
    { let _s = format!("{}", state._fs_acctfile_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
    }
    Ok(())
}

/// WRITE to ACCTFILE-FILE
fn acctfile_file_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 300];
    { let _s = format!("{:>width$}", state.fd_acct_id, width = 11); let _b = _s.as_bytes(); let _cl = _b.len().min(11); _buf[0..0+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _src = state.fd_acct_data.as_bytes(); let _end = (11+289).min(_buf.len()); let _cl = _src.len().min(_end-11); _buf[11..11+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_acctfile_file.write_record(&_buf) {
        Ok(()) => state._fs_acctfile_file = FileStatus::Success,
        Err(e) => state._fs_acctfile_file = e,
    }
}

/// CLOSE ACCTFILE-FILE
fn acctfile_file_close(state: &mut ProgramState) {
    match state._fh_acctfile_file.close() {
        Ok(()) => state._fs_acctfile_file = FileStatus::Success,
        Err(e) => state._fs_acctfile_file = e,
    }
    { let _s = format!("{}", state._fs_acctfile_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN I-O ACCTFILE-FILE
fn acctfile_file_open_io(state: &mut ProgramState) {
    let path = std::env::var("ACCTFILE_FILE").unwrap_or("acctfile_file.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_acctfile_file = handle; state._fs_acctfile_file = FileStatus::Success; }
        Err(_) => { state._fs_acctfile_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_acctfile_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN EXTEND ACCTFILE-FILE
fn acctfile_file_open_extend(state: &mut ProgramState) {
    let path = std::env::var("ACCTFILE_FILE").unwrap_or("acctfile_file.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_acctfile_file = handle; state._fs_acctfile_file = FileStatus::Success; }
        Err(_) => { state._fs_acctfile_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_acctfile_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN INPUT OUT-FILE
fn out_file_open_input(state: &mut ProgramState) {
    let path = std::env::var("OUT_FILE").unwrap_or("out_file.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_out_file = handle; state._fs_out_file = FileStatus::Success; }
        Err(_) => { state._fs_out_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_out_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.outfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN OUTPUT OUT-FILE
fn out_file_open_output(state: &mut ProgramState) {
    let path = std::env::var("OUT_FILE").unwrap_or("out_file.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_out_file = handle; state._fs_out_file = FileStatus::Success; }
        Err(_) => { state._fs_out_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_out_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.outfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// READ OUT-FILE
fn out_file_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_out_file.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(107);
            if _len > 0 { let _end = _len.min(0+11); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.out_acct_id = _s.parse().unwrap_or_default(); }
            if _len > 11 { let _end = _len.min(11+1); state.out_acct_active_status = FixedString::from(String::from_utf8_lossy(&_bytes[11.._end])); }
            if _len > 12 { let _end = _len.min(12+12); let _s = String::from_utf8_lossy(&_bytes[12.._end]).trim().to_string(); state.out_acct_curr_bal = _s.parse::<i64>().unwrap_or_default().into(); }
            if _len > 24 { let _end = _len.min(24+12); let _s = String::from_utf8_lossy(&_bytes[24.._end]).trim().to_string(); state.out_acct_credit_limit = _s.parse::<i64>().unwrap_or_default().into(); }
            if _len > 36 { let _end = _len.min(36+12); let _s = String::from_utf8_lossy(&_bytes[36.._end]).trim().to_string(); state.out_acct_cash_credit_limit = _s.parse::<i64>().unwrap_or_default().into(); }
            if _len > 48 { let _end = _len.min(48+10); state.out_acct_open_date = FixedString::from(String::from_utf8_lossy(&_bytes[48.._end])); }
            if _len > 58 { let _end = _len.min(58+10); state.out_acct_expiraion_date = FixedString::from(String::from_utf8_lossy(&_bytes[58.._end])); }
            if _len > 68 { let _end = _len.min(68+10); state.out_acct_reissue_date = FixedString::from(String::from_utf8_lossy(&_bytes[68.._end])); }
            if _len > 78 { let _end = _len.min(78+12); let _s = String::from_utf8_lossy(&_bytes[78.._end]).trim().to_string(); state.out_acct_curr_cyc_credit = _s.parse::<i64>().unwrap_or_default().into(); }
            if _len > 90 { let _end = _len.min(90+7); state.out_acct_curr_cyc_debit = PackedDecimal::from_bytes(&_bytes[90.._end]); }
            if _len > 97 { let _end = _len.min(97+10); state.out_acct_group_id = FixedString::from(String::from_utf8_lossy(&_bytes[97.._end])); }
            state._fs_out_file = FileStatus::Success;
    { let _s = format!("{}", state._fs_out_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.outfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(FileStatus::AtEnd) => {
            state._fs_out_file = FileStatus::AtEnd;
    { let _s = format!("{}", state._fs_out_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.outfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(e) => {
            state._fs_out_file = e.clone();
    { let _s = format!("{}", state._fs_out_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.outfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
    }
    Ok(())
}

/// WRITE to OUT-FILE
fn out_file_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 107];
    { let _s = format!("{:>width$}", state.out_acct_id, width = 11); let _b = _s.as_bytes(); let _cl = _b.len().min(11); _buf[0..0+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _src = state.out_acct_active_status.as_bytes(); let _end = (11+1).min(_buf.len()); let _cl = _src.len().min(_end-11); _buf[11..11+_cl].copy_from_slice(&_src[.._cl]); }
    { let _s = format!("{:>width$}", state.out_acct_curr_bal.value, width = 12); let _b = _s.as_bytes(); let _cl = _b.len().min(12); _buf[12..12+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _s = format!("{:>width$}", state.out_acct_credit_limit.value, width = 12); let _b = _s.as_bytes(); let _cl = _b.len().min(12); _buf[24..24+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _s = format!("{:>width$}", state.out_acct_cash_credit_limit.value, width = 12); let _b = _s.as_bytes(); let _cl = _b.len().min(12); _buf[36..36+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _src = state.out_acct_open_date.as_bytes(); let _end = (48+10).min(_buf.len()); let _cl = _src.len().min(_end-48); _buf[48..48+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.out_acct_expiraion_date.as_bytes(); let _end = (58+10).min(_buf.len()); let _cl = _src.len().min(_end-58); _buf[58..58+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.out_acct_reissue_date.as_bytes(); let _end = (68+10).min(_buf.len()); let _cl = _src.len().min(_end-68); _buf[68..68+_cl].copy_from_slice(&_src[.._cl]); }
    { let _s = format!("{:>width$}", state.out_acct_curr_cyc_credit.value, width = 12); let _b = _s.as_bytes(); let _cl = _b.len().min(12); _buf[78..78+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _packed = state.out_acct_curr_cyc_debit.to_bytes(); let _cl = _packed.len().min(7); _buf[90..90+_cl].copy_from_slice(&_packed[.._cl]); }
    { let _src = state.out_acct_group_id.as_bytes(); let _end = (97+10).min(_buf.len()); let _cl = _src.len().min(_end-97); _buf[97..97+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_out_file.write_record(&_buf) {
        Ok(()) => state._fs_out_file = FileStatus::Success,
        Err(e) => state._fs_out_file = e,
    }
}

/// CLOSE OUT-FILE
fn out_file_close(state: &mut ProgramState) {
    match state._fh_out_file.close() {
        Ok(()) => state._fs_out_file = FileStatus::Success,
        Err(e) => state._fs_out_file = e,
    }
    { let _s = format!("{}", state._fs_out_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.outfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN I-O OUT-FILE
fn out_file_open_io(state: &mut ProgramState) {
    let path = std::env::var("OUT_FILE").unwrap_or("out_file.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_out_file = handle; state._fs_out_file = FileStatus::Success; }
        Err(_) => { state._fs_out_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_out_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.outfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN EXTEND OUT-FILE
fn out_file_open_extend(state: &mut ProgramState) {
    let path = std::env::var("OUT_FILE").unwrap_or("out_file.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_out_file = handle; state._fs_out_file = FileStatus::Success; }
        Err(_) => { state._fs_out_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_out_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.outfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN INPUT ARRY-FILE
fn arry_file_open_input(state: &mut ProgramState) {
    let path = std::env::var("ARRY_FILE").unwrap_or("arry_file.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_arry_file = handle; state._fs_arry_file = FileStatus::Success; }
        Err(_) => { state._fs_arry_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_arry_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.arryfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN OUTPUT ARRY-FILE
fn arry_file_open_output(state: &mut ProgramState) {
    let path = std::env::var("ARRY_FILE").unwrap_or("arry_file.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_arry_file = handle; state._fs_arry_file = FileStatus::Success; }
        Err(_) => { state._fs_arry_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_arry_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.arryfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// READ ARRY-FILE
fn arry_file_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_arry_file.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(34);
            if _len > 0 { let _end = _len.min(0+11); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.arr_acct_id = _s.parse().unwrap_or_default(); }
            if _len > 11 { let _end = _len.min(11+19); state.arr_acct_bal = FixedString::from(String::from_utf8_lossy(&_bytes[11.._end])); }
            if _len > 11 { let _end = _len.min(11+12); let _s = String::from_utf8_lossy(&_bytes[11.._end]).trim().to_string(); state.arr_acct_curr_bal = _s.parse::<i64>().unwrap_or_default().into(); }
            if _len > 23 { let _end = _len.min(23+7); state.arr_acct_curr_cyc_debit = PackedDecimal::from_bytes(&_bytes[23.._end]); }
            if _len > 30 { let _end = _len.min(30+4); state.arr_filler = FixedString::from(String::from_utf8_lossy(&_bytes[30.._end])); }
            state._fs_arry_file = FileStatus::Success;
    { let _s = format!("{}", state._fs_arry_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.arryfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(FileStatus::AtEnd) => {
            state._fs_arry_file = FileStatus::AtEnd;
    { let _s = format!("{}", state._fs_arry_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.arryfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(e) => {
            state._fs_arry_file = e.clone();
    { let _s = format!("{}", state._fs_arry_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.arryfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
    }
    Ok(())
}

/// WRITE to ARRY-FILE
fn arry_file_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 34];
    { let _s = format!("{:>width$}", state.arr_acct_id, width = 11); let _b = _s.as_bytes(); let _cl = _b.len().min(11); _buf[0..0+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _s = format!("{:>width$}", state.arr_acct_curr_bal.value, width = 12); let _b = _s.as_bytes(); let _cl = _b.len().min(12); _buf[11..11+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _packed = state.arr_acct_curr_cyc_debit.to_bytes(); let _cl = _packed.len().min(7); _buf[23..23+_cl].copy_from_slice(&_packed[.._cl]); }
    { let _src = state.arr_filler.as_bytes(); let _end = (30+4).min(_buf.len()); let _cl = _src.len().min(_end-30); _buf[30..30+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_arry_file.write_record(&_buf) {
        Ok(()) => state._fs_arry_file = FileStatus::Success,
        Err(e) => state._fs_arry_file = e,
    }
}

/// CLOSE ARRY-FILE
fn arry_file_close(state: &mut ProgramState) {
    match state._fh_arry_file.close() {
        Ok(()) => state._fs_arry_file = FileStatus::Success,
        Err(e) => state._fs_arry_file = e,
    }
    { let _s = format!("{}", state._fs_arry_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.arryfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN I-O ARRY-FILE
fn arry_file_open_io(state: &mut ProgramState) {
    let path = std::env::var("ARRY_FILE").unwrap_or("arry_file.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_arry_file = handle; state._fs_arry_file = FileStatus::Success; }
        Err(_) => { state._fs_arry_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_arry_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.arryfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN EXTEND ARRY-FILE
fn arry_file_open_extend(state: &mut ProgramState) {
    let path = std::env::var("ARRY_FILE").unwrap_or("arry_file.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_arry_file = handle; state._fs_arry_file = FileStatus::Success; }
        Err(_) => { state._fs_arry_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_arry_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.arryfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN INPUT VBRC-FILE
fn vbrc_file_open_input(state: &mut ProgramState) {
    let path = std::env::var("VBRC_FILE").unwrap_or("vbrc_file.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_vbrc_file = handle; state._fs_vbrc_file = FileStatus::Success; }
        Err(_) => { state._fs_vbrc_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_vbrc_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.vbrcfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN OUTPUT VBRC-FILE
fn vbrc_file_open_output(state: &mut ProgramState) {
    let path = std::env::var("VBRC_FILE").unwrap_or("vbrc_file.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_vbrc_file = handle; state._fs_vbrc_file = FileStatus::Success; }
        Err(_) => { state._fs_vbrc_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_vbrc_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.vbrcfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// READ VBRC-FILE
fn vbrc_file_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_vbrc_file.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(80);
            if _len > 0 { let _end = _len.min(0+80); state.vbr_rec = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            state._fs_vbrc_file = FileStatus::Success;
    { let _s = format!("{}", state._fs_vbrc_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.vbrcfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(FileStatus::AtEnd) => {
            state._fs_vbrc_file = FileStatus::AtEnd;
    { let _s = format!("{}", state._fs_vbrc_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.vbrcfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(e) => {
            state._fs_vbrc_file = e.clone();
    { let _s = format!("{}", state._fs_vbrc_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.vbrcfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
    }
    Ok(())
}

/// WRITE to VBRC-FILE
fn vbrc_file_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 80];
    { let _src = state.vbr_rec.as_bytes(); let _end = (0+80).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_vbrc_file.write_record(&_buf) {
        Ok(()) => state._fs_vbrc_file = FileStatus::Success,
        Err(e) => state._fs_vbrc_file = e,
    }
}

/// CLOSE VBRC-FILE
fn vbrc_file_close(state: &mut ProgramState) {
    match state._fh_vbrc_file.close() {
        Ok(()) => state._fs_vbrc_file = FileStatus::Success,
        Err(e) => state._fs_vbrc_file = e,
    }
    { let _s = format!("{}", state._fs_vbrc_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.vbrcfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN I-O VBRC-FILE
fn vbrc_file_open_io(state: &mut ProgramState) {
    let path = std::env::var("VBRC_FILE").unwrap_or("vbrc_file.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_vbrc_file = handle; state._fs_vbrc_file = FileStatus::Success; }
        Err(_) => { state._fs_vbrc_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_vbrc_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.vbrcfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN EXTEND VBRC-FILE
fn vbrc_file_open_extend(state: &mut ProgramState) {
    let path = std::env::var("VBRC_FILE").unwrap_or("vbrc_file.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_vbrc_file = handle; state._fs_vbrc_file = FileStatus::Success; }
        Err(_) => { state._fs_vbrc_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_vbrc_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.vbrcfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// WRITE VBR-REC
fn vbr_rec_write(state: &mut ProgramState) {
    // Write VBR-REC via vbrc_file_write (byte buffer)
    vbrc_file_write(state);
}

/// WRITE OUT-ACCT-REC
fn out_acct_rec_write(state: &mut ProgramState) {
    // Write OUT-ACCT-REC via out_file_write (byte buffer)
    out_file_write(state);
}

/// WRITE ARR-ARRAY-REC
fn arr_array_rec_write(state: &mut ProgramState) {
    // Write ARR-ARRAY-REC via arry_file_write (byte buffer)
    arry_file_write(state);
}

/// External: CALL 'COBDATFT'
fn cobdatft(_param1: &mut impl std::fmt::Debug) {
    todo!("External subroutine 'COBDATFT' not yet linked — implement or link the COBDATFT module")
}

/// External: CALL 'CEE3ABD'
fn cee3abd(_param1: &mut impl std::fmt::Debug, _param2: &mut impl std::fmt::Debug) {
    todo!("External subroutine 'CEE3ABD' not yet linked — implement or link the CEE3ABD module")
}


fn file_read(_state: &mut ProgramState) {
    // stub: CICS file read
}

fn main() {
    let mut state = ProgramState::default();
    p_0000_acctfile_open(&mut state);
}

