// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use std::io::{BufRead, BufReader, BufWriter, Write};
use std::fs::File;

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct FdTrnxfileRec {
    /// FD-TRNXS-ID
    pub fd_trnxs_id: FdTrnxsId,
    /// FD-ACCT-DATA
    pub fd_acct_data: FixedString<318>,
}
impl std::fmt::Display for FdTrnxfileRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.fd_trnxs_id, self.fd_acct_data)
    }
}
impl From<&str> for FdTrnxfileRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for FdTrnxfileRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl FdTrnxfileRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct FdTrnxsId {
    /// FD-TRNX-CARD
    pub fd_trnx_card: FixedString<16>,
    /// FD-TRNX-ID
    pub fd_trnx_id: FixedString<16>,
}
impl std::fmt::Display for FdTrnxsId {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.fd_trnx_card, self.fd_trnx_id)
    }
}
impl From<&str> for FdTrnxsId {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for FdTrnxsId {
    fn from(_s: String) -> Self { Self::default() }
}
impl FdTrnxsId {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TrnxFile {
    /// FD-TRNXFILE-REC
    pub fd_trnxfile_rec: FdTrnxfileRec,
}
impl std::fmt::Display for TrnxFile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.fd_trnxfile_rec)
    }
}
impl From<&str> for TrnxFile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TrnxFile {
    fn from(_s: String) -> Self { Self::default() }
}
impl TrnxFile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct FdXreffileRec {
    /// FD-XREF-CARD-NUM
    pub fd_xref_card_num: FixedString<16>,
    /// FD-XREF-DATA
    pub fd_xref_data: FixedString<34>,
}
impl std::fmt::Display for FdXreffileRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.fd_xref_card_num, self.fd_xref_data)
    }
}
impl From<&str> for FdXreffileRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for FdXreffileRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl FdXreffileRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct XrefFile {
    /// FD-XREFFILE-REC
    pub fd_xreffile_rec: FdXreffileRec,
}
impl std::fmt::Display for XrefFile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.fd_xreffile_rec)
    }
}
impl From<&str> for XrefFile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for XrefFile {
    fn from(_s: String) -> Self { Self::default() }
}
impl XrefFile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct FdCustfileRec {
    /// FD-CUST-ID
    pub fd_cust_id: FixedString<9>,
    /// FD-CUST-DATA
    pub fd_cust_data: FixedString<491>,
}
impl std::fmt::Display for FdCustfileRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.fd_cust_id, self.fd_cust_data)
    }
}
impl From<&str> for FdCustfileRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for FdCustfileRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl FdCustfileRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CustFile {
    /// FD-CUSTFILE-REC
    pub fd_custfile_rec: FdCustfileRec,
}
impl std::fmt::Display for CustFile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.fd_custfile_rec)
    }
}
impl From<&str> for CustFile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CustFile {
    fn from(_s: String) -> Self { Self::default() }
}
impl CustFile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct FdAcctfileRec {
    /// FD-ACCT-ID
    pub fd_acct_id: u64,
    /// FD-ACCT-DATA
    pub fd_acct_data: FixedString<289>,
}
impl std::fmt::Display for FdAcctfileRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.fd_acct_id, self.fd_acct_data)
    }
}
impl From<&str> for FdAcctfileRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for FdAcctfileRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl FdAcctfileRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AcctFile {
    /// FD-ACCTFILE-REC
    pub fd_acctfile_rec: FdAcctfileRec,
}
impl std::fmt::Display for AcctFile {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.fd_acctfile_rec)
    }
}
impl From<&str> for AcctFile {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for AcctFile {
    fn from(_s: String) -> Self { Self::default() }
}
impl AcctFile {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TrnxfileStatus {
    /// TRNXFILE-STAT1
    pub trnxfile_stat1: FixedString<1>,
    /// TRNXFILE-STAT2
    pub trnxfile_stat2: FixedString<1>,
}
impl std::fmt::Display for TrnxfileStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.trnxfile_stat1, self.trnxfile_stat2)
    }
}
impl From<&str> for TrnxfileStatus {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TrnxfileStatus {
    fn from(_s: String) -> Self { Self::default() }
}
impl TrnxfileStatus {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct XreffileStatus {
    /// XREFFILE-STAT1
    pub xreffile_stat1: FixedString<1>,
    /// XREFFILE-STAT2
    pub xreffile_stat2: FixedString<1>,
}
impl std::fmt::Display for XreffileStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.xreffile_stat1, self.xreffile_stat2)
    }
}
impl From<&str> for XreffileStatus {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for XreffileStatus {
    fn from(_s: String) -> Self { Self::default() }
}
impl XreffileStatus {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CustfileStatus {
    /// CUSTFILE-STAT1
    pub custfile_stat1: FixedString<1>,
    /// CUSTFILE-STAT2
    pub custfile_stat2: FixedString<1>,
}
impl std::fmt::Display for CustfileStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.custfile_stat1, self.custfile_stat2)
    }
}
impl From<&str> for CustfileStatus {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CustfileStatus {
    fn from(_s: String) -> Self { Self::default() }
}
impl CustfileStatus {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AcctfileStatus {
    /// ACCTFILE-STAT1
    pub acctfile_stat1: FixedString<1>,
    /// ACCTFILE-STAT2
    pub acctfile_stat2: FixedString<1>,
}
impl std::fmt::Display for AcctfileStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.acctfile_stat1, self.acctfile_stat2)
    }
}
impl From<&str> for AcctfileStatus {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for AcctfileStatus {
    fn from(_s: String) -> Self { Self::default() }
}
impl AcctfileStatus {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct LkM03bArea {
    /// LK-M03B-DD
    pub lk_m03b_dd: FixedString<8>,
    /// LK-M03B-OPER
    pub lk_m03b_oper: FixedString<1>,
    /// LK-M03B-RC
    pub lk_m03b_rc: FixedString<2>,
    /// LK-M03B-KEY
    pub lk_m03b_key: FixedString<25>,
    /// LK-M03B-KEY-LN
    pub lk_m03b_key_ln: i32,
    /// LK-M03B-FLDT
    pub lk_m03b_fldt: FixedString<1000>,
}
impl std::fmt::Display for LkM03bArea {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}", self.lk_m03b_dd, self.lk_m03b_oper, self.lk_m03b_rc, self.lk_m03b_key, self.lk_m03b_key_ln, self.lk_m03b_fldt)
    }
}
impl From<&str> for LkM03bArea {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for LkM03bArea {
    fn from(_s: String) -> Self { Self::default() }
}
impl LkM03bArea {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// FD group: FD-TRNXFILE-REC
    pub fd_trnxfile_rec: FixedString<350>,
    /// FD group: FD-TRNXS-ID
    pub fd_trnxs_id: FixedString<32>,
    /// FD: FD-TRNX-CARD
    pub fd_trnx_card: FixedString<16>,
    /// FD: FD-TRNX-ID
    pub fd_trnx_id: FixedString<16>,
    /// FD: FD-ACCT-DATA
    pub fd_acct_data: FixedString<318>,
    /// FD group: FD-XREFFILE-REC
    pub fd_xreffile_rec: FixedString<50>,
    /// FD: FD-XREF-CARD-NUM
    pub fd_xref_card_num: FixedString<16>,
    /// FD: FD-XREF-DATA
    pub fd_xref_data: FixedString<34>,
    /// FD group: FD-CUSTFILE-REC
    pub fd_custfile_rec: FixedString<500>,
    /// FD: FD-CUST-ID
    pub fd_cust_id: FixedString<9>,
    /// FD: FD-CUST-DATA
    pub fd_cust_data: FixedString<491>,
    /// FD group: FD-ACCTFILE-REC
    pub fd_acctfile_rec: FixedString<297>,
    /// FD: FD-ACCT-ID
    pub fd_acct_id: u64,
    /// FD: FD-ACCT-DATA
    pub fd_acct_data_2: FixedString<289>,
    /// TRNXFILE-STATUS
    pub trnxfile_status: TrnxfileStatus,
    /// TRNXFILE-STAT1
    pub trnxfile_stat1: FixedString<1>,
    /// TRNXFILE-STAT2
    pub trnxfile_stat2: FixedString<1>,
    /// XREFFILE-STATUS
    pub xreffile_status: XreffileStatus,
    /// XREFFILE-STAT1
    pub xreffile_stat1: FixedString<1>,
    /// XREFFILE-STAT2
    pub xreffile_stat2: FixedString<1>,
    /// CUSTFILE-STATUS
    pub custfile_status: CustfileStatus,
    /// CUSTFILE-STAT1
    pub custfile_stat1: FixedString<1>,
    /// CUSTFILE-STAT2
    pub custfile_stat2: FixedString<1>,
    /// ACCTFILE-STATUS
    pub acctfile_status: AcctfileStatus,
    /// ACCTFILE-STAT1
    pub acctfile_stat1: FixedString<1>,
    /// ACCTFILE-STAT2
    pub acctfile_stat2: FixedString<1>,
    /// LINKAGE: LK-M03B-AREA
    pub lk_m03b_area: LkM03bArea,
    /// File status for TRNX-FILE
    pub _fs_trnx_file: FileStatus,
    /// File handle for TRNX-FILE
    pub _fh_trnx_file: CobolFile,
    /// File status for XREF-FILE
    pub _fs_xref_file: FileStatus,
    /// File handle for XREF-FILE
    pub _fh_xref_file: CobolFile,
    /// File status for CUST-FILE
    pub _fs_cust_file: FileStatus,
    /// File handle for CUST-FILE
    pub _fh_cust_file: CobolFile,
    /// File status for ACCT-FILE
    pub _fs_acct_file: FileStatus,
    /// File handle for ACCT-FILE
    pub _fh_acct_file: CobolFile,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            fd_trnxfile_rec: Default::default(),
            fd_trnxs_id: Default::default(),
            fd_trnx_card: Default::default(),
            fd_trnx_id: Default::default(),
            fd_acct_data: Default::default(),
            fd_xreffile_rec: Default::default(),
            fd_xref_card_num: Default::default(),
            fd_xref_data: Default::default(),
            fd_custfile_rec: Default::default(),
            fd_cust_id: Default::default(),
            fd_cust_data: Default::default(),
            fd_acctfile_rec: Default::default(),
            fd_acct_id: Default::default(),
            fd_acct_data_2: Default::default(),
            trnxfile_status: Default::default(),
            trnxfile_stat1: Default::default(),
            trnxfile_stat2: Default::default(),
            xreffile_status: Default::default(),
            xreffile_stat1: Default::default(),
            xreffile_stat2: Default::default(),
            custfile_status: Default::default(),
            custfile_stat1: Default::default(),
            custfile_stat2: Default::default(),
            acctfile_status: Default::default(),
            acctfile_stat1: Default::default(),
            acctfile_stat2: Default::default(),
            lk_m03b_area: Default::default(),
            _fs_trnx_file: FileStatus::Success,
            _fh_trnx_file: CobolFile::Closed,
            _fs_xref_file: FileStatus::Success,
            _fh_xref_file: CobolFile::Closed,
            _fs_cust_file: FileStatus::Success,
            _fh_cust_file: CobolFile::Closed,
            _fs_acct_file: FileStatus::Success,
            _fh_acct_file: CobolFile::Closed,
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// LK-M03B-AREA
fn p_lk_m03b_area(state: &mut ProgramState) {
}

/// 0000-START
fn p_0000_start(state: &mut ProgramState) {
    if state.lk_m03b_area.lk_m03b_dd.to_string() == "TRNXFILE" {
        p_1000_trnxfile_proc(state);
        p_1900_exit(state);
        p_1999_exit(state);
    } else {
        if state.lk_m03b_area.lk_m03b_dd.to_string() == "XREFFILE" {
            p_2000_xreffile_proc(state);
            p_2900_exit(state);
            p_2999_exit(state);
        } else {
            if state.lk_m03b_area.lk_m03b_dd.to_string() == "CUSTFILE" {
                p_3000_custfile_proc(state);
                p_3900_exit(state);
                p_3999_exit(state);
            } else {
                if state.lk_m03b_area.lk_m03b_dd.to_string() == "ACCTFILE" {
                    p_4000_acctfile_proc(state);
                    p_4900_exit(state);
                    p_4999_exit(state);
                } else {
                    if true {
                        p_9999_goback(state); return;
                    }
                }
            }
        }
    }
}

/// 9999-GOBACK
fn p_9999_goback(state: &mut ProgramState) {
    { let _ = state._fh_trnx_file.close();
        let _ = state._fh_xref_file.close();
        let _ = state._fh_cust_file.close();
        let _ = state._fh_acct_file.close();
        return; }
}

/// 1000-TRNXFILE-PROC
fn p_1000_trnxfile_proc(state: &mut ProgramState) {
    // SKIP: unresolved condition
    // SKIP: unresolved condition
    // SKIP: unresolved condition
}

/// 1900-EXIT
fn p_1900_exit(state: &mut ProgramState) {
    state.lk_m03b_area.lk_m03b_rc = FixedString::copy_from(&state.trnxfile_status);
}

/// 1999-EXIT
fn p_1999_exit(state: &mut ProgramState) {
}

/// 2000-XREFFILE-PROC
fn p_2000_xreffile_proc(state: &mut ProgramState) {
    // SKIP: unresolved condition
    // SKIP: unresolved condition
    // SKIP: unresolved condition
}

/// 2900-EXIT
fn p_2900_exit(state: &mut ProgramState) {
    state.lk_m03b_area.lk_m03b_rc = FixedString::copy_from(&state.xreffile_status);
}

/// 2999-EXIT
fn p_2999_exit(state: &mut ProgramState) {
}

/// 3000-CUSTFILE-PROC
fn p_3000_custfile_proc(state: &mut ProgramState) {
    // SKIP: unresolved condition
    // SKIP: unresolved condition
    // SKIP: unresolved condition
}

/// 3900-EXIT
fn p_3900_exit(state: &mut ProgramState) {
    state.lk_m03b_area.lk_m03b_rc = FixedString::copy_from(&state.custfile_status);
}

/// 3999-EXIT
fn p_3999_exit(state: &mut ProgramState) {
}

/// 4000-ACCTFILE-PROC
fn p_4000_acctfile_proc(state: &mut ProgramState) {
    // SKIP: unresolved condition
    // SKIP: unresolved condition
    // SKIP: unresolved condition
}

/// 4900-EXIT
fn p_4900_exit(state: &mut ProgramState) {
    state.lk_m03b_area.lk_m03b_rc = FixedString::copy_from(&state.acctfile_status);
}

/// 4999-EXIT
fn p_4999_exit(state: &mut ProgramState) {
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// OPEN INPUT TRNX-FILE
fn trnx_file_open_input(state: &mut ProgramState) {
    let path = std::env::var("TRNX_FILE").unwrap_or("trnx_file.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_trnx_file = handle; state._fs_trnx_file = FileStatus::Success; }
        Err(_) => { state._fs_trnx_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_trnx_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.trnxfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN OUTPUT TRNX-FILE
fn trnx_file_open_output(state: &mut ProgramState) {
    let path = std::env::var("TRNX_FILE").unwrap_or("trnx_file.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_trnx_file = handle; state._fs_trnx_file = FileStatus::Success; }
        Err(_) => { state._fs_trnx_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_trnx_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.trnxfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// READ TRNX-FILE
fn trnx_file_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_trnx_file.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(350);
            if _len > 0 { let _end = _len.min(0+16); state.fd_trnx_card = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 16 { let _end = _len.min(16+16); state.fd_trnx_id = FixedString::from(String::from_utf8_lossy(&_bytes[16.._end])); }
            if _len > 32 { let _end = _len.min(32+318); state.fd_acct_data = FixedString::from(String::from_utf8_lossy(&_bytes[32.._end])); }
            state._fs_trnx_file = FileStatus::Success;
    { let _s = format!("{}", state._fs_trnx_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.trnxfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(FileStatus::AtEnd) => {
            state._fs_trnx_file = FileStatus::AtEnd;
    { let _s = format!("{}", state._fs_trnx_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.trnxfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(e) => {
            state._fs_trnx_file = e.clone();
    { let _s = format!("{}", state._fs_trnx_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.trnxfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
    }
    Ok(())
}

/// WRITE to TRNX-FILE
fn trnx_file_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 350];
    { let _src = state.fd_trnx_card.as_bytes(); let _end = (0+16).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.fd_trnx_id.as_bytes(); let _end = (16+16).min(_buf.len()); let _cl = _src.len().min(_end-16); _buf[16..16+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.fd_acct_data.as_bytes(); let _end = (32+318).min(_buf.len()); let _cl = _src.len().min(_end-32); _buf[32..32+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_trnx_file.write_record(&_buf) {
        Ok(()) => state._fs_trnx_file = FileStatus::Success,
        Err(e) => state._fs_trnx_file = e,
    }
}

/// CLOSE TRNX-FILE
fn trnx_file_close(state: &mut ProgramState) {
    match state._fh_trnx_file.close() {
        Ok(()) => state._fs_trnx_file = FileStatus::Success,
        Err(e) => state._fs_trnx_file = e,
    }
    { let _s = format!("{}", state._fs_trnx_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.trnxfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN I-O TRNX-FILE
fn trnx_file_open_io(state: &mut ProgramState) {
    let path = std::env::var("TRNX_FILE").unwrap_or("trnx_file.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_trnx_file = handle; state._fs_trnx_file = FileStatus::Success; }
        Err(_) => { state._fs_trnx_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_trnx_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.trnxfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN EXTEND TRNX-FILE
fn trnx_file_open_extend(state: &mut ProgramState) {
    let path = std::env::var("TRNX_FILE").unwrap_or("trnx_file.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_trnx_file = handle; state._fs_trnx_file = FileStatus::Success; }
        Err(_) => { state._fs_trnx_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_trnx_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.trnxfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN INPUT XREF-FILE
fn xref_file_open_input(state: &mut ProgramState) {
    let path = std::env::var("XREF_FILE").unwrap_or("xref_file.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_xref_file = handle; state._fs_xref_file = FileStatus::Success; }
        Err(_) => { state._fs_xref_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_xref_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.xreffile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN OUTPUT XREF-FILE
fn xref_file_open_output(state: &mut ProgramState) {
    let path = std::env::var("XREF_FILE").unwrap_or("xref_file.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_xref_file = handle; state._fs_xref_file = FileStatus::Success; }
        Err(_) => { state._fs_xref_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_xref_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.xreffile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// READ XREF-FILE
fn xref_file_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_xref_file.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(50);
            if _len > 0 { let _end = _len.min(0+16); state.fd_xref_card_num = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 16 { let _end = _len.min(16+34); state.fd_xref_data = FixedString::from(String::from_utf8_lossy(&_bytes[16.._end])); }
            state._fs_xref_file = FileStatus::Success;
    { let _s = format!("{}", state._fs_xref_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.xreffile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(FileStatus::AtEnd) => {
            state._fs_xref_file = FileStatus::AtEnd;
    { let _s = format!("{}", state._fs_xref_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.xreffile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(e) => {
            state._fs_xref_file = e.clone();
    { let _s = format!("{}", state._fs_xref_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.xreffile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
    }
    Ok(())
}

/// WRITE to XREF-FILE
fn xref_file_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 50];
    { let _src = state.fd_xref_card_num.as_bytes(); let _end = (0+16).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.fd_xref_data.as_bytes(); let _end = (16+34).min(_buf.len()); let _cl = _src.len().min(_end-16); _buf[16..16+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_xref_file.write_record(&_buf) {
        Ok(()) => state._fs_xref_file = FileStatus::Success,
        Err(e) => state._fs_xref_file = e,
    }
}

/// CLOSE XREF-FILE
fn xref_file_close(state: &mut ProgramState) {
    match state._fh_xref_file.close() {
        Ok(()) => state._fs_xref_file = FileStatus::Success,
        Err(e) => state._fs_xref_file = e,
    }
    { let _s = format!("{}", state._fs_xref_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.xreffile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN I-O XREF-FILE
fn xref_file_open_io(state: &mut ProgramState) {
    let path = std::env::var("XREF_FILE").unwrap_or("xref_file.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_xref_file = handle; state._fs_xref_file = FileStatus::Success; }
        Err(_) => { state._fs_xref_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_xref_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.xreffile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN EXTEND XREF-FILE
fn xref_file_open_extend(state: &mut ProgramState) {
    let path = std::env::var("XREF_FILE").unwrap_or("xref_file.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_xref_file = handle; state._fs_xref_file = FileStatus::Success; }
        Err(_) => { state._fs_xref_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_xref_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.xreffile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN INPUT CUST-FILE
fn cust_file_open_input(state: &mut ProgramState) {
    let path = std::env::var("CUST_FILE").unwrap_or("cust_file.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_cust_file = handle; state._fs_cust_file = FileStatus::Success; }
        Err(_) => { state._fs_cust_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_cust_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.custfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN OUTPUT CUST-FILE
fn cust_file_open_output(state: &mut ProgramState) {
    let path = std::env::var("CUST_FILE").unwrap_or("cust_file.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_cust_file = handle; state._fs_cust_file = FileStatus::Success; }
        Err(_) => { state._fs_cust_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_cust_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.custfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// READ CUST-FILE
fn cust_file_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_cust_file.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(500);
            if _len > 0 { let _end = _len.min(0+9); state.fd_cust_id = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 9 { let _end = _len.min(9+491); state.fd_cust_data = FixedString::from(String::from_utf8_lossy(&_bytes[9.._end])); }
            state._fs_cust_file = FileStatus::Success;
    { let _s = format!("{}", state._fs_cust_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.custfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(FileStatus::AtEnd) => {
            state._fs_cust_file = FileStatus::AtEnd;
    { let _s = format!("{}", state._fs_cust_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.custfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(e) => {
            state._fs_cust_file = e.clone();
    { let _s = format!("{}", state._fs_cust_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.custfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
    }
    Ok(())
}

/// WRITE to CUST-FILE
fn cust_file_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 500];
    { let _src = state.fd_cust_id.as_bytes(); let _end = (0+9).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.fd_cust_data.as_bytes(); let _end = (9+491).min(_buf.len()); let _cl = _src.len().min(_end-9); _buf[9..9+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_cust_file.write_record(&_buf) {
        Ok(()) => state._fs_cust_file = FileStatus::Success,
        Err(e) => state._fs_cust_file = e,
    }
}

/// CLOSE CUST-FILE
fn cust_file_close(state: &mut ProgramState) {
    match state._fh_cust_file.close() {
        Ok(()) => state._fs_cust_file = FileStatus::Success,
        Err(e) => state._fs_cust_file = e,
    }
    { let _s = format!("{}", state._fs_cust_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.custfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN I-O CUST-FILE
fn cust_file_open_io(state: &mut ProgramState) {
    let path = std::env::var("CUST_FILE").unwrap_or("cust_file.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_cust_file = handle; state._fs_cust_file = FileStatus::Success; }
        Err(_) => { state._fs_cust_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_cust_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.custfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN EXTEND CUST-FILE
fn cust_file_open_extend(state: &mut ProgramState) {
    let path = std::env::var("CUST_FILE").unwrap_or("cust_file.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_cust_file = handle; state._fs_cust_file = FileStatus::Success; }
        Err(_) => { state._fs_cust_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_cust_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.custfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN INPUT ACCT-FILE
fn acct_file_open_input(state: &mut ProgramState) {
    let path = std::env::var("ACCT_FILE").unwrap_or("acct_file.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_acct_file = handle; state._fs_acct_file = FileStatus::Success; }
        Err(_) => { state._fs_acct_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_acct_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN OUTPUT ACCT-FILE
fn acct_file_open_output(state: &mut ProgramState) {
    let path = std::env::var("ACCT_FILE").unwrap_or("acct_file.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_acct_file = handle; state._fs_acct_file = FileStatus::Success; }
        Err(_) => { state._fs_acct_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_acct_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// READ ACCT-FILE
fn acct_file_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_acct_file.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(300);
            if _len > 0 { let _end = _len.min(0+11); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.fd_acct_id = _s.parse().unwrap_or_default(); }
            if _len > 11 { let _end = _len.min(11+289); state.fd_acct_data = FixedString::from(String::from_utf8_lossy(&_bytes[11.._end])); }
            state._fs_acct_file = FileStatus::Success;
    { let _s = format!("{}", state._fs_acct_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(FileStatus::AtEnd) => {
            state._fs_acct_file = FileStatus::AtEnd;
    { let _s = format!("{}", state._fs_acct_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(e) => {
            state._fs_acct_file = e.clone();
    { let _s = format!("{}", state._fs_acct_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
    }
    Ok(())
}

/// WRITE to ACCT-FILE
fn acct_file_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 300];
    { let _s = format!("{:>width$}", state.fd_acct_id, width = 11); let _b = _s.as_bytes(); let _cl = _b.len().min(11); _buf[0..0+_cl].copy_from_slice(&_b[_b.len()-_cl..]); }
    { let _src = state.fd_acct_data.as_bytes(); let _end = (11+289).min(_buf.len()); let _cl = _src.len().min(_end-11); _buf[11..11+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_acct_file.write_record(&_buf) {
        Ok(()) => state._fs_acct_file = FileStatus::Success,
        Err(e) => state._fs_acct_file = e,
    }
}

/// CLOSE ACCT-FILE
fn acct_file_close(state: &mut ProgramState) {
    match state._fh_acct_file.close() {
        Ok(()) => state._fs_acct_file = FileStatus::Success,
        Err(e) => state._fs_acct_file = e,
    }
    { let _s = format!("{}", state._fs_acct_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN I-O ACCT-FILE
fn acct_file_open_io(state: &mut ProgramState) {
    let path = std::env::var("ACCT_FILE").unwrap_or("acct_file.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_acct_file = handle; state._fs_acct_file = FileStatus::Success; }
        Err(_) => { state._fs_acct_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_acct_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN EXTEND ACCT-FILE
fn acct_file_open_extend(state: &mut ProgramState) {
    let path = std::env::var("ACCT_FILE").unwrap_or("acct_file.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_acct_file = handle; state._fs_acct_file = FileStatus::Success; }
        Err(_) => { state._fs_acct_file = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_acct_file); let _b = _s.as_bytes(); unsafe { let p = &mut state.acctfile_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

fn main() {
    let mut state = ProgramState::default();
    p_lk_m03b_area(&mut state);
}

