// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.


use cobol_runtime::FixedString;
use cobol_runtime::CicsContext;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsVariables {
    /// WS-PGMNAME
    pub ws_pgmname: FixedString<8>,
    /// WS-TRANID
    pub ws_tranid: FixedString<4>,
    /// WS-MESSAGE
    pub ws_message: FixedString<80>,
    /// WS-TRANSACT-FILE
    pub ws_transact_file: FixedString<8>,
    /// WS-ACCTDAT-FILE
    pub ws_acctdat_file: FixedString<8>,
    /// WS-CXACAIX-FILE
    pub ws_cxacaix_file: FixedString<8>,
    /// WS-ERR-FLG
    pub ws_err_flg: FixedString<1>,
    /// WS-RESP-CD
    pub ws_resp_cd: i32,
    /// WS-REAS-CD
    pub ws_reas_cd: i32,
    /// WS-USR-MODIFIED
    pub ws_usr_modified: FixedString<1>,
    /// WS-CONF-PAY-FLG
    pub ws_conf_pay_flg: FixedString<1>,
    /// WS-TRAN-AMT
    pub ws_tran_amt: u32,
    /// WS-CURR-BAL
    pub ws_curr_bal: u64,
    /// WS-TRAN-ID-NUM
    pub ws_tran_id_num: u64,
    /// WS-TRAN-DATE
    pub ws_tran_date: FixedString<8>,
    /// WS-ABS-TIME
    pub ws_abs_time: PackedDecimal<15> /* Signed */,
    /// WS-CUR-DATE-X10
    pub ws_cur_date_x10: FixedString<10>,
    /// WS-CUR-TIME-X08
    pub ws_cur_time_x08: FixedString<8>,
}
impl std::fmt::Display for WsVariables {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self.ws_pgmname, self.ws_tranid, self.ws_message, self.ws_transact_file, self.ws_acctdat_file, self.ws_cxacaix_file, self.ws_err_flg, self.ws_resp_cd, self.ws_reas_cd, self.ws_usr_modified, self.ws_conf_pay_flg, self.ws_tran_amt, self.ws_curr_bal, self.ws_tran_id_num, self.ws_tran_date, self.ws_abs_time, self.ws_cur_date_x10, self.ws_cur_time_x08)
    }
}
impl From<&str> for WsVariables {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsVariables {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsVariables {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CarddemoCommarea {
    /// CDEMO-GENERAL-INFO
    pub cdemo_general_info: CdemoGeneralInfo,
    /// CDEMO-CUSTOMER-INFO
    pub cdemo_customer_info: CdemoCustomerInfo,
    /// CDEMO-ACCOUNT-INFO
    pub cdemo_account_info: CdemoAccountInfo,
    /// CDEMO-CARD-INFO
    pub cdemo_card_info: CdemoCardInfo,
    /// CDEMO-MORE-INFO
    pub cdemo_more_info: CdemoMoreInfo,
    /// CDEMO-CB00-INFO
    pub cdemo_cb00_info: CdemoCb00Info,
}
impl std::fmt::Display for CarddemoCommarea {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}", self.cdemo_general_info, self.cdemo_customer_info, self.cdemo_account_info, self.cdemo_card_info, self.cdemo_more_info, self.cdemo_cb00_info)
    }
}
impl From<&str> for CarddemoCommarea {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CarddemoCommarea {
    fn from(_s: String) -> Self { Self::default() }
}
impl CarddemoCommarea {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CdemoGeneralInfo {
    /// CDEMO-FROM-TRANID
    pub cdemo_from_tranid: FixedString<4>,
    /// CDEMO-FROM-PROGRAM
    pub cdemo_from_program: FixedString<8>,
    /// CDEMO-TO-TRANID
    pub cdemo_to_tranid: FixedString<4>,
    /// CDEMO-TO-PROGRAM
    pub cdemo_to_program: FixedString<8>,
    /// CDEMO-USER-ID
    pub cdemo_user_id: FixedString<8>,
    /// CDEMO-USER-TYPE
    pub cdemo_user_type: FixedString<1>,
    /// CDEMO-PGM-CONTEXT
    pub cdemo_pgm_context: u32,
}
impl std::fmt::Display for CdemoGeneralInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}", self.cdemo_from_tranid, self.cdemo_from_program, self.cdemo_to_tranid, self.cdemo_to_program, self.cdemo_user_id, self.cdemo_user_type, self.cdemo_pgm_context)
    }
}
impl From<&str> for CdemoGeneralInfo {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CdemoGeneralInfo {
    fn from(_s: String) -> Self { Self::default() }
}
impl CdemoGeneralInfo {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CdemoCustomerInfo {
    /// CDEMO-CUST-ID
    pub cdemo_cust_id: u32,
    /// CDEMO-CUST-FNAME
    pub cdemo_cust_fname: FixedString<25>,
    /// CDEMO-CUST-MNAME
    pub cdemo_cust_mname: FixedString<25>,
    /// CDEMO-CUST-LNAME
    pub cdemo_cust_lname: FixedString<25>,
}
impl std::fmt::Display for CdemoCustomerInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.cdemo_cust_id, self.cdemo_cust_fname, self.cdemo_cust_mname, self.cdemo_cust_lname)
    }
}
impl From<&str> for CdemoCustomerInfo {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CdemoCustomerInfo {
    fn from(_s: String) -> Self { Self::default() }
}
impl CdemoCustomerInfo {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CdemoAccountInfo {
    /// CDEMO-ACCT-ID
    pub cdemo_acct_id: u64,
    /// CDEMO-ACCT-STATUS
    pub cdemo_acct_status: FixedString<1>,
}
impl std::fmt::Display for CdemoAccountInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.cdemo_acct_id, self.cdemo_acct_status)
    }
}
impl From<&str> for CdemoAccountInfo {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CdemoAccountInfo {
    fn from(_s: String) -> Self { Self::default() }
}
impl CdemoAccountInfo {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CdemoCardInfo {
    /// CDEMO-CARD-NUM
    pub cdemo_card_num: u64,
}
impl std::fmt::Display for CdemoCardInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.cdemo_card_num)
    }
}
impl From<&str> for CdemoCardInfo {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CdemoCardInfo {
    fn from(_s: String) -> Self { Self::default() }
}
impl CdemoCardInfo {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CdemoMoreInfo {
    /// CDEMO-LAST-MAP
    pub cdemo_last_map: FixedString<7>,
    /// CDEMO-LAST-MAPSET
    pub cdemo_last_mapset: FixedString<7>,
}
impl std::fmt::Display for CdemoMoreInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.cdemo_last_map, self.cdemo_last_mapset)
    }
}
impl From<&str> for CdemoMoreInfo {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CdemoMoreInfo {
    fn from(_s: String) -> Self { Self::default() }
}
impl CdemoMoreInfo {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CdemoCb00Info {
    /// CDEMO-CB00-TRNID-FIRST
    pub cdemo_cb00_trnid_first: FixedString<16>,
    /// CDEMO-CB00-TRNID-LAST
    pub cdemo_cb00_trnid_last: FixedString<16>,
    /// CDEMO-CB00-PAGE-NUM
    pub cdemo_cb00_page_num: u32,
    /// CDEMO-CB00-NEXT-PAGE-FLG
    pub cdemo_cb00_next_page_flg: FixedString<1>,
    /// CDEMO-CB00-TRN-SEL-FLG
    pub cdemo_cb00_trn_sel_flg: FixedString<1>,
    /// CDEMO-CB00-TRN-SELECTED
    pub cdemo_cb00_trn_selected: FixedString<16>,
}
impl std::fmt::Display for CdemoCb00Info {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}", self.cdemo_cb00_trnid_first, self.cdemo_cb00_trnid_last, self.cdemo_cb00_page_num, self.cdemo_cb00_next_page_flg, self.cdemo_cb00_trn_sel_flg, self.cdemo_cb00_trn_selected)
    }
}
impl From<&str> for CdemoCb00Info {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CdemoCb00Info {
    fn from(_s: String) -> Self { Self::default() }
}
impl CdemoCb00Info {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Cobil0ai {
    /// FILLER PIC FILLER
    pub _filler_137: FixedString<12>,
    /// TRNNAMEL
    pub trnnamel: i32,
    /// TRNNAMEF
    pub trnnamef: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_140: Filler140,
    /// FILLER PIC FILLER
    pub _filler_142: FixedString<4>,
    /// TRNNAMEI
    pub trnnamei: FixedString<4>,
    /// TITLE01L
    pub title01l: i32,
    /// TITLE01F
    pub title01f: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_146: Filler146,
    /// FILLER PIC FILLER
    pub _filler_148: FixedString<4>,
    /// TITLE01I
    pub title01i: FixedString<40>,
    /// CURDATEL
    pub curdatel: i32,
    /// CURDATEF
    pub curdatef: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_152: Filler152,
    /// FILLER PIC FILLER
    pub _filler_154: FixedString<4>,
    /// CURDATEI
    pub curdatei: FixedString<8>,
    /// PGMNAMEL
    pub pgmnamel: i32,
    /// PGMNAMEF
    pub pgmnamef: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_158: Filler158,
    /// FILLER PIC FILLER
    pub _filler_160: FixedString<4>,
    /// PGMNAMEI
    pub pgmnamei: FixedString<8>,
    /// TITLE02L
    pub title02l: i32,
    /// TITLE02F
    pub title02f: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_164: Filler164,
    /// FILLER PIC FILLER
    pub _filler_166: FixedString<4>,
    /// TITLE02I
    pub title02i: FixedString<40>,
    /// CURTIMEL
    pub curtimel: i32,
    /// CURTIMEF
    pub curtimef: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_170: Filler170,
    /// FILLER PIC FILLER
    pub _filler_172: FixedString<4>,
    /// CURTIMEI
    pub curtimei: FixedString<8>,
    /// ACTIDINL
    pub actidinl: i32,
    /// ACTIDINF
    pub actidinf: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_176: Filler176,
    /// FILLER PIC FILLER
    pub _filler_178: FixedString<4>,
    /// ACTIDINI
    pub actidini: FixedString<11>,
    /// CURBALL
    pub curball: i32,
    /// CURBALF
    pub curbalf: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_182: Filler182,
    /// FILLER PIC FILLER
    pub _filler_184: FixedString<4>,
    /// CURBALI
    pub curbali: FixedString<14>,
    /// CONFIRML
    pub confirml: i32,
    /// CONFIRMF
    pub confirmf: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_188: Filler188,
    /// FILLER PIC FILLER
    pub _filler_190: FixedString<4>,
    /// CONFIRMI
    pub confirmi: FixedString<1>,
    /// ERRMSGL
    pub errmsgl: i32,
    /// ERRMSGF
    pub errmsgf: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_194: Filler194,
    /// FILLER PIC FILLER
    pub _filler_196: FixedString<4>,
    /// ERRMSGI
    pub errmsgi: FixedString<78>,
}
impl std::fmt::Display for Cobil0ai {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self._filler_137, self.trnnamel, self.trnnamef, self._filler_140, self._filler_142, self.trnnamei, self.title01l, self.title01f, self._filler_146, self._filler_148, self.title01i, self.curdatel, self.curdatef, self._filler_152, self._filler_154, self.curdatei, self.pgmnamel, self.pgmnamef, self._filler_158, self._filler_160, self.pgmnamei, self.title02l, self.title02f, self._filler_164, self._filler_166, self.title02i, self.curtimel, self.curtimef, self._filler_170, self._filler_172, self.curtimei, self.actidinl, self.actidinf, self._filler_176, self._filler_178, self.actidini, self.curball, self.curbalf, self._filler_182, self._filler_184, self.curbali, self.confirml, self.confirmf, self._filler_188, self._filler_190, self.confirmi, self.errmsgl, self.errmsgf, self._filler_194, self._filler_196, self.errmsgi)
    }
}
impl From<&str> for Cobil0ai {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Cobil0ai {
    fn from(_s: String) -> Self { Self::default() }
}
impl Cobil0ai {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Filler140 {
    /// TRNNAMEA
    pub trnnamea: FixedString<1>,
}
impl std::fmt::Display for Filler140 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.trnnamea)
    }
}
impl From<&str> for Filler140 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Filler140 {
    fn from(_s: String) -> Self { Self::default() }
}
impl Filler140 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Filler146 {
    /// TITLE01A
    pub title01a: FixedString<1>,
}
impl std::fmt::Display for Filler146 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.title01a)
    }
}
impl From<&str> for Filler146 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Filler146 {
    fn from(_s: String) -> Self { Self::default() }
}
impl Filler146 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Filler152 {
    /// CURDATEA
    pub curdatea: FixedString<1>,
}
impl std::fmt::Display for Filler152 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.curdatea)
    }
}
impl From<&str> for Filler152 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Filler152 {
    fn from(_s: String) -> Self { Self::default() }
}
impl Filler152 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Filler158 {
    /// PGMNAMEA
    pub pgmnamea: FixedString<1>,
}
impl std::fmt::Display for Filler158 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.pgmnamea)
    }
}
impl From<&str> for Filler158 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Filler158 {
    fn from(_s: String) -> Self { Self::default() }
}
impl Filler158 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Filler164 {
    /// TITLE02A
    pub title02a: FixedString<1>,
}
impl std::fmt::Display for Filler164 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.title02a)
    }
}
impl From<&str> for Filler164 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Filler164 {
    fn from(_s: String) -> Self { Self::default() }
}
impl Filler164 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Filler170 {
    /// CURTIMEA
    pub curtimea: FixedString<1>,
}
impl std::fmt::Display for Filler170 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.curtimea)
    }
}
impl From<&str> for Filler170 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Filler170 {
    fn from(_s: String) -> Self { Self::default() }
}
impl Filler170 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Filler176 {
    /// ACTIDINA
    pub actidina: FixedString<1>,
}
impl std::fmt::Display for Filler176 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.actidina)
    }
}
impl From<&str> for Filler176 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Filler176 {
    fn from(_s: String) -> Self { Self::default() }
}
impl Filler176 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Filler182 {
    /// CURBALA
    pub curbala: FixedString<1>,
}
impl std::fmt::Display for Filler182 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.curbala)
    }
}
impl From<&str> for Filler182 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Filler182 {
    fn from(_s: String) -> Self { Self::default() }
}
impl Filler182 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Filler188 {
    /// CONFIRMA
    pub confirma: FixedString<1>,
}
impl std::fmt::Display for Filler188 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.confirma)
    }
}
impl From<&str> for Filler188 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Filler188 {
    fn from(_s: String) -> Self { Self::default() }
}
impl Filler188 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Filler194 {
    /// ERRMSGA
    pub errmsga: FixedString<1>,
}
impl std::fmt::Display for Filler194 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.errmsga)
    }
}
impl From<&str> for Filler194 {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Filler194 {
    fn from(_s: String) -> Self { Self::default() }
}
impl Filler194 {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Cobil0ao {
    /// FILLER PIC FILLER
    pub _filler_199: FixedString<12>,
    /// FILLER PIC FILLER
    pub _filler_200: FixedString<3>,
    /// TRNNAMEC
    pub trnnamec: FixedString<1>,
    /// TRNNAMEP
    pub trnnamep: FixedString<1>,
    /// TRNNAMEH
    pub trnnameh: FixedString<1>,
    /// TRNNAMEV
    pub trnnamev: FixedString<1>,
    /// TRNNAMEO
    pub trnnameo: FixedString<4>,
    /// FILLER PIC FILLER
    pub _filler_206: FixedString<3>,
    /// TITLE01C
    pub title01c: FixedString<1>,
    /// TITLE01P
    pub title01p: FixedString<1>,
    /// TITLE01H
    pub title01h: FixedString<1>,
    /// TITLE01V
    pub title01v: FixedString<1>,
    /// TITLE01O
    pub title01o: FixedString<40>,
    /// FILLER PIC FILLER
    pub _filler_212: FixedString<3>,
    /// CURDATEC
    pub curdatec: FixedString<1>,
    /// CURDATEP
    pub curdatep: FixedString<1>,
    /// CURDATEH
    pub curdateh: FixedString<1>,
    /// CURDATEV
    pub curdatev: FixedString<1>,
    /// CURDATEO
    pub curdateo: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_218: FixedString<3>,
    /// PGMNAMEC
    pub pgmnamec: FixedString<1>,
    /// PGMNAMEP
    pub pgmnamep: FixedString<1>,
    /// PGMNAMEH
    pub pgmnameh: FixedString<1>,
    /// PGMNAMEV
    pub pgmnamev: FixedString<1>,
    /// PGMNAMEO
    pub pgmnameo: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_224: FixedString<3>,
    /// TITLE02C
    pub title02c: FixedString<1>,
    /// TITLE02P
    pub title02p: FixedString<1>,
    /// TITLE02H
    pub title02h: FixedString<1>,
    /// TITLE02V
    pub title02v: FixedString<1>,
    /// TITLE02O
    pub title02o: FixedString<40>,
    /// FILLER PIC FILLER
    pub _filler_230: FixedString<3>,
    /// CURTIMEC
    pub curtimec: FixedString<1>,
    /// CURTIMEP
    pub curtimep: FixedString<1>,
    /// CURTIMEH
    pub curtimeh: FixedString<1>,
    /// CURTIMEV
    pub curtimev: FixedString<1>,
    /// CURTIMEO
    pub curtimeo: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_236: FixedString<3>,
    /// ACTIDINC
    pub actidinc: FixedString<1>,
    /// ACTIDINP
    pub actidinp: FixedString<1>,
    /// ACTIDINH
    pub actidinh: FixedString<1>,
    /// ACTIDINV
    pub actidinv: FixedString<1>,
    /// ACTIDINO
    pub actidino: FixedString<11>,
    /// FILLER PIC FILLER
    pub _filler_242: FixedString<3>,
    /// CURBALC
    pub curbalc: FixedString<1>,
    /// CURBALP
    pub curbalp: FixedString<1>,
    /// CURBALH
    pub curbalh: FixedString<1>,
    /// CURBALV
    pub curbalv: FixedString<1>,
    /// CURBALO
    pub curbalo: FixedString<14>,
    /// FILLER PIC FILLER
    pub _filler_248: FixedString<3>,
    /// CONFIRMC
    pub confirmc: FixedString<1>,
    /// CONFIRMP
    pub confirmp: FixedString<1>,
    /// CONFIRMH
    pub confirmh: FixedString<1>,
    /// CONFIRMV
    pub confirmv: FixedString<1>,
    /// CONFIRMO
    pub confirmo: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_254: FixedString<3>,
    /// ERRMSGC
    pub errmsgc: FixedString<1>,
    /// ERRMSGP
    pub errmsgp: FixedString<1>,
    /// ERRMSGH
    pub errmsgh: FixedString<1>,
    /// ERRMSGV
    pub errmsgv: FixedString<1>,
    /// ERRMSGO
    pub errmsgo: FixedString<78>,
}
impl std::fmt::Display for Cobil0ao {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self._filler_199, self._filler_200, self.trnnamec, self.trnnamep, self.trnnameh, self.trnnamev, self.trnnameo, self._filler_206, self.title01c, self.title01p, self.title01h, self.title01v, self.title01o, self._filler_212, self.curdatec, self.curdatep, self.curdateh, self.curdatev, self.curdateo, self._filler_218, self.pgmnamec, self.pgmnamep, self.pgmnameh, self.pgmnamev, self.pgmnameo, self._filler_224, self.title02c, self.title02p, self.title02h, self.title02v, self.title02o, self._filler_230, self.curtimec, self.curtimep, self.curtimeh, self.curtimev, self.curtimeo, self._filler_236, self.actidinc, self.actidinp, self.actidinh, self.actidinv, self.actidino, self._filler_242, self.curbalc, self.curbalp, self.curbalh, self.curbalv, self.curbalo, self._filler_248, self.confirmc, self.confirmp, self.confirmh, self.confirmv, self.confirmo, self._filler_254, self.errmsgc, self.errmsgp, self.errmsgh, self.errmsgv, self.errmsgo)
    }
}
impl From<&str> for Cobil0ao {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Cobil0ao {
    fn from(_s: String) -> Self { Self::default() }
}
impl Cobil0ao {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CcdaScreenTitle {
    /// CCDA-TITLE01
    pub ccda_title01: FixedString<40>,
    /// CCDA-TITLE02
    pub ccda_title02: FixedString<40>,
    /// CCDA-THANK-YOU
    pub ccda_thank_you: FixedString<40>,
}
impl std::fmt::Display for CcdaScreenTitle {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.ccda_title01, self.ccda_title02, self.ccda_thank_you)
    }
}
impl From<&str> for CcdaScreenTitle {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CcdaScreenTitle {
    fn from(_s: String) -> Self { Self::default() }
}
impl CcdaScreenTitle {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsDateTime {
    /// WS-CURDATE-DATA
    pub ws_curdate_data: WsCurdateData,
    /// WS-CURDATE-MM-DD-YY
    pub ws_curdate_mm_dd_yy: WsCurdateMmDdYy,
    /// WS-CURTIME-HH-MM-SS
    pub ws_curtime_hh_mm_ss: WsCurtimeHhMmSs,
    /// WS-TIMESTAMP
    pub ws_timestamp: WsTimestamp,
}
impl std::fmt::Display for WsDateTime {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.ws_curdate_data, self.ws_curdate_mm_dd_yy, self.ws_curtime_hh_mm_ss, self.ws_timestamp)
    }
}
impl From<&str> for WsDateTime {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsDateTime {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsDateTime {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsCurdateData {
    /// WS-CURDATE
    pub ws_curdate: WsCurdate,
    /// WS-CURDATE-N
    pub ws_curdate_n: u32,
    /// WS-CURTIME
    pub ws_curtime: WsCurtime,
    /// WS-CURTIME-N
    pub ws_curtime_n: u32,
}
impl std::fmt::Display for WsCurdateData {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.ws_curdate, self.ws_curdate_n, self.ws_curtime, self.ws_curtime_n)
    }
}
impl From<&str> for WsCurdateData {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsCurdateData {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsCurdateData {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsCurdate {
    /// WS-CURDATE-YEAR
    pub ws_curdate_year: u32,
    /// WS-CURDATE-MONTH
    pub ws_curdate_month: u32,
    /// WS-CURDATE-DAY
    pub ws_curdate_day: u32,
}
impl std::fmt::Display for WsCurdate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.ws_curdate_year, self.ws_curdate_month, self.ws_curdate_day)
    }
}
impl From<&str> for WsCurdate {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsCurdate {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsCurdate {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsCurtime {
    /// WS-CURTIME-HOURS
    pub ws_curtime_hours: u32,
    /// WS-CURTIME-MINUTE
    pub ws_curtime_minute: u32,
    /// WS-CURTIME-SECOND
    pub ws_curtime_second: u32,
    /// WS-CURTIME-MILSEC
    pub ws_curtime_milsec: u32,
}
impl std::fmt::Display for WsCurtime {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.ws_curtime_hours, self.ws_curtime_minute, self.ws_curtime_second, self.ws_curtime_milsec)
    }
}
impl From<&str> for WsCurtime {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsCurtime {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsCurtime {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsCurdateMmDdYy {
    /// WS-CURDATE-MM
    pub ws_curdate_mm: u32,
    /// FILLER PIC FILLER
    pub _filler_319: FixedString<1>,
    /// WS-CURDATE-DD
    pub ws_curdate_dd: u32,
    /// FILLER PIC FILLER
    pub _filler_321: FixedString<1>,
    /// WS-CURDATE-YY
    pub ws_curdate_yy: u32,
}
impl std::fmt::Display for WsCurdateMmDdYy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}", self.ws_curdate_mm, self._filler_319, self.ws_curdate_dd, self._filler_321, self.ws_curdate_yy)
    }
}
impl From<&str> for WsCurdateMmDdYy {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsCurdateMmDdYy {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsCurdateMmDdYy {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsCurtimeHhMmSs {
    /// WS-CURTIME-HH
    pub ws_curtime_hh: u32,
    /// FILLER PIC FILLER
    pub _filler_325: FixedString<1>,
    /// WS-CURTIME-MM
    pub ws_curtime_mm: u32,
    /// FILLER PIC FILLER
    pub _filler_327: FixedString<1>,
    /// WS-CURTIME-SS
    pub ws_curtime_ss: u32,
}
impl std::fmt::Display for WsCurtimeHhMmSs {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}", self.ws_curtime_hh, self._filler_325, self.ws_curtime_mm, self._filler_327, self.ws_curtime_ss)
    }
}
impl From<&str> for WsCurtimeHhMmSs {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsCurtimeHhMmSs {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsCurtimeHhMmSs {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsTimestamp {
    /// WS-TIMESTAMP-DT-YYYY
    pub ws_timestamp_dt_yyyy: u32,
    /// FILLER PIC FILLER
    pub _filler_331: FixedString<1>,
    /// WS-TIMESTAMP-DT-MM
    pub ws_timestamp_dt_mm: u32,
    /// FILLER PIC FILLER
    pub _filler_333: FixedString<1>,
    /// WS-TIMESTAMP-DT-DD
    pub ws_timestamp_dt_dd: u32,
    /// FILLER PIC FILLER
    pub _filler_335: FixedString<1>,
    /// WS-TIMESTAMP-TM-HH
    pub ws_timestamp_tm_hh: u32,
    /// FILLER PIC FILLER
    pub _filler_337: FixedString<1>,
    /// WS-TIMESTAMP-TM-MM
    pub ws_timestamp_tm_mm: u32,
    /// FILLER PIC FILLER
    pub _filler_339: FixedString<1>,
    /// WS-TIMESTAMP-TM-SS
    pub ws_timestamp_tm_ss: u32,
    /// FILLER PIC FILLER
    pub _filler_341: FixedString<1>,
    /// WS-TIMESTAMP-TM-MS6
    pub ws_timestamp_tm_ms6: u32,
}
impl std::fmt::Display for WsTimestamp {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}", self.ws_timestamp_dt_yyyy, self._filler_331, self.ws_timestamp_dt_mm, self._filler_333, self.ws_timestamp_dt_dd, self._filler_335, self.ws_timestamp_tm_hh, self._filler_337, self.ws_timestamp_tm_mm, self._filler_339, self.ws_timestamp_tm_ss, self._filler_341, self.ws_timestamp_tm_ms6)
    }
}
impl From<&str> for WsTimestamp {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsTimestamp {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsTimestamp {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CcdaCommonMessages {
    /// CCDA-MSG-THANK-YOU
    pub ccda_msg_thank_you: FixedString<50>,
    /// CCDA-MSG-INVALID-KEY
    pub ccda_msg_invalid_key: FixedString<50>,
}
impl std::fmt::Display for CcdaCommonMessages {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.ccda_msg_thank_you, self.ccda_msg_invalid_key)
    }
}
impl From<&str> for CcdaCommonMessages {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CcdaCommonMessages {
    fn from(_s: String) -> Self { Self::default() }
}
impl CcdaCommonMessages {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct AccountRecord {
    /// ACCT-ID
    pub acct_id: u64,
    /// ACCT-ACTIVE-STATUS
    pub acct_active_status: FixedString<1>,
    /// ACCT-CURR-BAL
    pub acct_curr_bal: Decimal /* 10,2 Signed */,
    /// ACCT-CREDIT-LIMIT
    pub acct_credit_limit: Decimal /* 10,2 Signed */,
    /// ACCT-CASH-CREDIT-LIMIT
    pub acct_cash_credit_limit: Decimal /* 10,2 Signed */,
    /// ACCT-OPEN-DATE
    pub acct_open_date: FixedString<10>,
    /// ACCT-EXPIRAION-DATE
    pub acct_expiraion_date: FixedString<10>,
    /// ACCT-REISSUE-DATE
    pub acct_reissue_date: FixedString<10>,
    /// ACCT-CURR-CYC-CREDIT
    pub acct_curr_cyc_credit: Decimal /* 10,2 Signed */,
    /// ACCT-CURR-CYC-DEBIT
    pub acct_curr_cyc_debit: Decimal /* 10,2 Signed */,
    /// ACCT-ADDR-ZIP
    pub acct_addr_zip: FixedString<10>,
    /// ACCT-GROUP-ID
    pub acct_group_id: FixedString<10>,
    /// FILLER PIC FILLER
    pub _filler_387: FixedString<178>,
}
impl std::fmt::Display for AccountRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}", self.acct_id, self.acct_active_status, self.acct_curr_bal, self.acct_credit_limit, self.acct_cash_credit_limit, self.acct_open_date, self.acct_expiraion_date, self.acct_reissue_date, self.acct_curr_cyc_credit, self.acct_curr_cyc_debit, self.acct_addr_zip, self.acct_group_id, self._filler_387)
    }
}
impl From<&str> for AccountRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for AccountRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl AccountRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct CardXrefRecord {
    /// XREF-CARD-NUM
    pub xref_card_num: FixedString<16>,
    /// XREF-CUST-ID
    pub xref_cust_id: u32,
    /// XREF-ACCT-ID
    pub xref_acct_id: u64,
    /// FILLER PIC FILLER
    pub _filler_398: FixedString<14>,
}
impl std::fmt::Display for CardXrefRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}", self.xref_card_num, self.xref_cust_id, self.xref_acct_id, self._filler_398)
    }
}
impl From<&str> for CardXrefRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for CardXrefRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl CardXrefRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TranRecord {
    /// TRAN-ID
    pub tran_id: FixedString<16>,
    /// TRAN-TYPE-CD
    pub tran_type_cd: FixedString<2>,
    /// TRAN-CAT-CD
    pub tran_cat_cd: u32,
    /// TRAN-SOURCE
    pub tran_source: FixedString<10>,
    /// TRAN-DESC
    pub tran_desc: FixedString<100>,
    /// TRAN-AMT
    pub tran_amt: Decimal /* 9,2 Signed */,
    /// TRAN-MERCHANT-ID
    pub tran_merchant_id: u32,
    /// TRAN-MERCHANT-NAME
    pub tran_merchant_name: FixedString<50>,
    /// TRAN-MERCHANT-CITY
    pub tran_merchant_city: FixedString<50>,
    /// TRAN-MERCHANT-ZIP
    pub tran_merchant_zip: FixedString<10>,
    /// TRAN-CARD-NUM
    pub tran_card_num: FixedString<16>,
    /// TRAN-ORIG-TS
    pub tran_orig_ts: FixedString<26>,
    /// TRAN-PROC-TS
    pub tran_proc_ts: FixedString<26>,
    /// FILLER PIC FILLER
    pub _filler_419: FixedString<20>,
}
impl std::fmt::Display for TranRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self.tran_id, self.tran_type_cd, self.tran_cat_cd, self.tran_source, self.tran_desc, self.tran_amt, self.tran_merchant_id, self.tran_merchant_name, self.tran_merchant_city, self.tran_merchant_zip, self.tran_card_num, self.tran_orig_ts, self.tran_proc_ts, self._filler_419)
    }
}
impl From<&str> for TranRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TranRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl TranRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Dfhcommarea {
    /// LK-COMMAREA
    pub lk_commarea: [FixedString<1>; 1],
}
impl std::fmt::Display for Dfhcommarea {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "")
    }
}
impl From<&str> for Dfhcommarea {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Dfhcommarea {
    fn from(_s: String) -> Self { Self::default() }
}
impl Dfhcommarea {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    pub cics: CicsContext,
    /// WS-VARIABLES
    pub ws_variables: WsVariables,
    /// WS-PGMNAME
    pub ws_pgmname: FixedString<8>,
    /// WS-TRANID
    pub ws_tranid: FixedString<4>,
    /// WS-MESSAGE
    pub ws_message: FixedString<80>,
    /// WS-TRANSACT-FILE
    pub ws_transact_file: FixedString<8>,
    /// WS-ACCTDAT-FILE
    pub ws_acctdat_file: FixedString<8>,
    /// WS-CXACAIX-FILE
    pub ws_cxacaix_file: FixedString<8>,
    /// WS-ERR-FLG
    pub ws_err_flg: FixedString<1>,
    /// WS-RESP-CD
    pub ws_resp_cd: i32,
    /// WS-REAS-CD
    pub ws_reas_cd: i32,
    /// WS-USR-MODIFIED
    pub ws_usr_modified: FixedString<1>,
    /// WS-CONF-PAY-FLG
    pub ws_conf_pay_flg: FixedString<1>,
    /// WS-TRAN-AMT
    pub ws_tran_amt: u32,
    /// WS-CURR-BAL
    pub ws_curr_bal: u64,
    /// WS-TRAN-ID-NUM
    pub ws_tran_id_num: u64,
    /// WS-TRAN-DATE
    pub ws_tran_date: FixedString<8>,
    /// WS-ABS-TIME
    pub ws_abs_time: PackedDecimal<15> /* Signed */,
    /// WS-CUR-DATE-X10
    pub ws_cur_date_x10: FixedString<10>,
    /// WS-CUR-TIME-X08
    pub ws_cur_time_x08: FixedString<8>,
    /// CARDDEMO-COMMAREA
    pub carddemo_commarea: CarddemoCommarea,
    /// CDEMO-GENERAL-INFO
    pub cdemo_general_info: CdemoGeneralInfo,
    /// CDEMO-FROM-TRANID
    pub cdemo_from_tranid: FixedString<4>,
    /// CDEMO-FROM-PROGRAM
    pub cdemo_from_program: FixedString<8>,
    /// CDEMO-TO-TRANID
    pub cdemo_to_tranid: FixedString<4>,
    /// CDEMO-TO-PROGRAM
    pub cdemo_to_program: FixedString<8>,
    /// CDEMO-USER-ID
    pub cdemo_user_id: FixedString<8>,
    /// CDEMO-USER-TYPE
    pub cdemo_user_type: FixedString<1>,
    /// CDEMO-PGM-CONTEXT
    pub cdemo_pgm_context: u32,
    /// CDEMO-CUSTOMER-INFO
    pub cdemo_customer_info: CdemoCustomerInfo,
    /// CDEMO-CUST-ID
    pub cdemo_cust_id: u32,
    /// CDEMO-CUST-FNAME
    pub cdemo_cust_fname: FixedString<25>,
    /// CDEMO-CUST-MNAME
    pub cdemo_cust_mname: FixedString<25>,
    /// CDEMO-CUST-LNAME
    pub cdemo_cust_lname: FixedString<25>,
    /// CDEMO-ACCOUNT-INFO
    pub cdemo_account_info: CdemoAccountInfo,
    /// CDEMO-ACCT-ID
    pub cdemo_acct_id: u64,
    /// CDEMO-ACCT-STATUS
    pub cdemo_acct_status: FixedString<1>,
    /// CDEMO-CARD-INFO
    pub cdemo_card_info: CdemoCardInfo,
    /// CDEMO-CARD-NUM
    pub cdemo_card_num: u64,
    /// CDEMO-MORE-INFO
    pub cdemo_more_info: CdemoMoreInfo,
    /// CDEMO-LAST-MAP
    pub cdemo_last_map: FixedString<7>,
    /// CDEMO-LAST-MAPSET
    pub cdemo_last_mapset: FixedString<7>,
    /// CDEMO-CB00-INFO
    pub cdemo_cb00_info: CdemoCb00Info,
    /// CDEMO-CB00-TRNID-FIRST
    pub cdemo_cb00_trnid_first: FixedString<16>,
    /// CDEMO-CB00-TRNID-LAST
    pub cdemo_cb00_trnid_last: FixedString<16>,
    /// CDEMO-CB00-PAGE-NUM
    pub cdemo_cb00_page_num: u32,
    /// CDEMO-CB00-NEXT-PAGE-FLG
    pub cdemo_cb00_next_page_flg: FixedString<1>,
    /// CDEMO-CB00-TRN-SEL-FLG
    pub cdemo_cb00_trn_sel_flg: FixedString<1>,
    /// CDEMO-CB00-TRN-SELECTED
    pub cdemo_cb00_trn_selected: FixedString<16>,
    /// COBIL0AI
    pub cobil0ai: Cobil0ai,
    /// TRNNAMEL
    pub trnnamel: i32,
    /// TRNNAMEF
    pub trnnamef: FixedString<1>,
    /// TRNNAMEI
    pub trnnamei: FixedString<4>,
    /// TITLE01L
    pub title01l: i32,
    /// TITLE01F
    pub title01f: FixedString<1>,
    /// TITLE01I
    pub title01i: FixedString<40>,
    /// CURDATEL
    pub curdatel: i32,
    /// CURDATEF
    pub curdatef: FixedString<1>,
    /// CURDATEI
    pub curdatei: FixedString<8>,
    /// PGMNAMEL
    pub pgmnamel: i32,
    /// PGMNAMEF
    pub pgmnamef: FixedString<1>,
    /// PGMNAMEI
    pub pgmnamei: FixedString<8>,
    /// TITLE02L
    pub title02l: i32,
    /// TITLE02F
    pub title02f: FixedString<1>,
    /// TITLE02I
    pub title02i: FixedString<40>,
    /// CURTIMEL
    pub curtimel: i32,
    /// CURTIMEF
    pub curtimef: FixedString<1>,
    /// CURTIMEI
    pub curtimei: FixedString<8>,
    /// ACTIDINL
    pub actidinl: i32,
    /// ACTIDINF
    pub actidinf: FixedString<1>,
    /// ACTIDINI
    pub actidini: FixedString<11>,
    /// CURBALL
    pub curball: i32,
    /// CURBALF
    pub curbalf: FixedString<1>,
    /// CURBALI
    pub curbali: FixedString<14>,
    /// CONFIRML
    pub confirml: i32,
    /// CONFIRMF
    pub confirmf: FixedString<1>,
    /// CONFIRMI
    pub confirmi: FixedString<1>,
    /// ERRMSGL
    pub errmsgl: i32,
    /// ERRMSGF
    pub errmsgf: FixedString<1>,
    /// ERRMSGI
    pub errmsgi: FixedString<78>,
    /// COBIL0AO
    pub cobil0ao: Cobil0ao,
    /// TRNNAMEC
    pub trnnamec: FixedString<1>,
    /// TRNNAMEP
    pub trnnamep: FixedString<1>,
    /// TRNNAMEH
    pub trnnameh: FixedString<1>,
    /// TRNNAMEV
    pub trnnamev: FixedString<1>,
    /// TRNNAMEO
    pub trnnameo: FixedString<4>,
    /// TITLE01C
    pub title01c: FixedString<1>,
    /// TITLE01P
    pub title01p: FixedString<1>,
    /// TITLE01H
    pub title01h: FixedString<1>,
    /// TITLE01V
    pub title01v: FixedString<1>,
    /// TITLE01O
    pub title01o: FixedString<40>,
    /// CURDATEC
    pub curdatec: FixedString<1>,
    /// CURDATEP
    pub curdatep: FixedString<1>,
    /// CURDATEH
    pub curdateh: FixedString<1>,
    /// CURDATEV
    pub curdatev: FixedString<1>,
    /// CURDATEO
    pub curdateo: FixedString<8>,
    /// PGMNAMEC
    pub pgmnamec: FixedString<1>,
    /// PGMNAMEP
    pub pgmnamep: FixedString<1>,
    /// PGMNAMEH
    pub pgmnameh: FixedString<1>,
    /// PGMNAMEV
    pub pgmnamev: FixedString<1>,
    /// PGMNAMEO
    pub pgmnameo: FixedString<8>,
    /// TITLE02C
    pub title02c: FixedString<1>,
    /// TITLE02P
    pub title02p: FixedString<1>,
    /// TITLE02H
    pub title02h: FixedString<1>,
    /// TITLE02V
    pub title02v: FixedString<1>,
    /// TITLE02O
    pub title02o: FixedString<40>,
    /// CURTIMEC
    pub curtimec: FixedString<1>,
    /// CURTIMEP
    pub curtimep: FixedString<1>,
    /// CURTIMEH
    pub curtimeh: FixedString<1>,
    /// CURTIMEV
    pub curtimev: FixedString<1>,
    /// CURTIMEO
    pub curtimeo: FixedString<8>,
    /// ACTIDINC
    pub actidinc: FixedString<1>,
    /// ACTIDINP
    pub actidinp: FixedString<1>,
    /// ACTIDINH
    pub actidinh: FixedString<1>,
    /// ACTIDINV
    pub actidinv: FixedString<1>,
    /// ACTIDINO
    pub actidino: FixedString<11>,
    /// CURBALC
    pub curbalc: FixedString<1>,
    /// CURBALP
    pub curbalp: FixedString<1>,
    /// CURBALH
    pub curbalh: FixedString<1>,
    /// CURBALV
    pub curbalv: FixedString<1>,
    /// CURBALO
    pub curbalo: FixedString<14>,
    /// CONFIRMC
    pub confirmc: FixedString<1>,
    /// CONFIRMP
    pub confirmp: FixedString<1>,
    /// CONFIRMH
    pub confirmh: FixedString<1>,
    /// CONFIRMV
    pub confirmv: FixedString<1>,
    /// CONFIRMO
    pub confirmo: FixedString<1>,
    /// ERRMSGC
    pub errmsgc: FixedString<1>,
    /// ERRMSGP
    pub errmsgp: FixedString<1>,
    /// ERRMSGH
    pub errmsgh: FixedString<1>,
    /// ERRMSGV
    pub errmsgv: FixedString<1>,
    /// ERRMSGO
    pub errmsgo: FixedString<78>,
    /// CCDA-SCREEN-TITLE
    pub ccda_screen_title: CcdaScreenTitle,
    /// CCDA-TITLE01
    pub ccda_title01: FixedString<40>,
    /// CCDA-TITLE02
    pub ccda_title02: FixedString<40>,
    /// CCDA-THANK-YOU
    pub ccda_thank_you: FixedString<40>,
    /// WS-DATE-TIME
    pub ws_date_time: WsDateTime,
    /// WS-CURDATE-DATA
    pub ws_curdate_data: WsCurdateData,
    /// WS-CURDATE
    pub ws_curdate: WsCurdate,
    /// WS-CURDATE-YEAR
    pub ws_curdate_year: u32,
    /// WS-CURDATE-MONTH
    pub ws_curdate_month: u32,
    /// WS-CURDATE-DAY
    pub ws_curdate_day: u32,
    /// WS-CURTIME
    pub ws_curtime: WsCurtime,
    /// WS-CURTIME-HOURS
    pub ws_curtime_hours: u32,
    /// WS-CURTIME-MINUTE
    pub ws_curtime_minute: u32,
    /// WS-CURTIME-SECOND
    pub ws_curtime_second: u32,
    /// WS-CURTIME-MILSEC
    pub ws_curtime_milsec: u32,
    /// WS-CURDATE-MM-DD-YY
    pub ws_curdate_mm_dd_yy: WsCurdateMmDdYy,
    /// WS-CURDATE-MM
    pub ws_curdate_mm: u32,
    /// WS-CURDATE-DD
    pub ws_curdate_dd: u32,
    /// WS-CURDATE-YY
    pub ws_curdate_yy: u32,
    /// WS-CURTIME-HH-MM-SS
    pub ws_curtime_hh_mm_ss: WsCurtimeHhMmSs,
    /// WS-CURTIME-HH
    pub ws_curtime_hh: u32,
    /// WS-CURTIME-MM
    pub ws_curtime_mm: u32,
    /// WS-CURTIME-SS
    pub ws_curtime_ss: u32,
    /// WS-TIMESTAMP
    pub ws_timestamp: WsTimestamp,
    /// WS-TIMESTAMP-DT-YYYY
    pub ws_timestamp_dt_yyyy: u32,
    /// WS-TIMESTAMP-DT-MM
    pub ws_timestamp_dt_mm: u32,
    /// WS-TIMESTAMP-DT-DD
    pub ws_timestamp_dt_dd: u32,
    /// WS-TIMESTAMP-TM-HH
    pub ws_timestamp_tm_hh: u32,
    /// WS-TIMESTAMP-TM-MM
    pub ws_timestamp_tm_mm: u32,
    /// WS-TIMESTAMP-TM-SS
    pub ws_timestamp_tm_ss: u32,
    /// WS-TIMESTAMP-TM-MS6
    pub ws_timestamp_tm_ms6: u32,
    /// CCDA-COMMON-MESSAGES
    pub ccda_common_messages: CcdaCommonMessages,
    /// CCDA-MSG-THANK-YOU
    pub ccda_msg_thank_you: FixedString<50>,
    /// CCDA-MSG-INVALID-KEY
    pub ccda_msg_invalid_key: FixedString<50>,
    /// ACCOUNT-RECORD
    pub account_record: AccountRecord,
    /// ACCT-ID
    pub acct_id: u64,
    /// ACCT-ACTIVE-STATUS
    pub acct_active_status: FixedString<1>,
    /// ACCT-CURR-BAL
    pub acct_curr_bal: Decimal /* 10,2 Signed */,
    /// ACCT-CREDIT-LIMIT
    pub acct_credit_limit: Decimal /* 10,2 Signed */,
    /// ACCT-CASH-CREDIT-LIMIT
    pub acct_cash_credit_limit: Decimal /* 10,2 Signed */,
    /// ACCT-OPEN-DATE
    pub acct_open_date: FixedString<10>,
    /// ACCT-EXPIRAION-DATE
    pub acct_expiraion_date: FixedString<10>,
    /// ACCT-REISSUE-DATE
    pub acct_reissue_date: FixedString<10>,
    /// ACCT-CURR-CYC-CREDIT
    pub acct_curr_cyc_credit: Decimal /* 10,2 Signed */,
    /// ACCT-CURR-CYC-DEBIT
    pub acct_curr_cyc_debit: Decimal /* 10,2 Signed */,
    /// ACCT-ADDR-ZIP
    pub acct_addr_zip: FixedString<10>,
    /// ACCT-GROUP-ID
    pub acct_group_id: FixedString<10>,
    /// CARD-XREF-RECORD
    pub card_xref_record: CardXrefRecord,
    /// XREF-CARD-NUM
    pub xref_card_num: FixedString<16>,
    /// XREF-CUST-ID
    pub xref_cust_id: u32,
    /// XREF-ACCT-ID
    pub xref_acct_id: u64,
    /// TRAN-RECORD
    pub tran_record: TranRecord,
    /// TRAN-ID
    pub tran_id: FixedString<16>,
    /// TRAN-TYPE-CD
    pub tran_type_cd: FixedString<2>,
    /// TRAN-CAT-CD
    pub tran_cat_cd: u32,
    /// TRAN-SOURCE
    pub tran_source: FixedString<10>,
    /// TRAN-DESC
    pub tran_desc: FixedString<100>,
    /// TRAN-AMT
    pub tran_amt: Decimal /* 9,2 Signed */,
    /// TRAN-MERCHANT-ID
    pub tran_merchant_id: u32,
    /// TRAN-MERCHANT-NAME
    pub tran_merchant_name: FixedString<50>,
    /// TRAN-MERCHANT-CITY
    pub tran_merchant_city: FixedString<50>,
    /// TRAN-MERCHANT-ZIP
    pub tran_merchant_zip: FixedString<10>,
    /// TRAN-CARD-NUM
    pub tran_card_num: FixedString<16>,
    /// TRAN-ORIG-TS
    pub tran_orig_ts: FixedString<26>,
    /// TRAN-PROC-TS
    pub tran_proc_ts: FixedString<26>,
    /// DFHENTER
    pub dfhenter: FixedString<1>,
    /// DFHCLEAR
    pub dfhclear: FixedString<1>,
    /// DFHPA1
    pub dfhpa1: FixedString<1>,
    /// DFHPA2
    pub dfhpa2: FixedString<1>,
    /// DFHPA3
    pub dfhpa3: FixedString<1>,
    /// DFHPF1
    pub dfhpf1: FixedString<1>,
    /// DFHPF2
    pub dfhpf2: FixedString<1>,
    /// DFHPF3
    pub dfhpf3: FixedString<1>,
    /// DFHPF4
    pub dfhpf4: FixedString<1>,
    /// DFHPF5
    pub dfhpf5: FixedString<1>,
    /// DFHPF6
    pub dfhpf6: FixedString<1>,
    /// DFHPF7
    pub dfhpf7: FixedString<1>,
    /// DFHPF8
    pub dfhpf8: FixedString<1>,
    /// DFHPF9
    pub dfhpf9: FixedString<1>,
    /// DFHPF10
    pub dfhpf10: FixedString<1>,
    /// DFHPF11
    pub dfhpf11: FixedString<1>,
    /// DFHPF12
    pub dfhpf12: FixedString<1>,
    /// DFHPF13
    pub dfhpf13: FixedString<1>,
    /// DFHPF14
    pub dfhpf14: FixedString<1>,
    /// DFHPF15
    pub dfhpf15: FixedString<1>,
    /// DFHPF16
    pub dfhpf16: FixedString<1>,
    /// DFHPF17
    pub dfhpf17: FixedString<1>,
    /// DFHPF18
    pub dfhpf18: FixedString<1>,
    /// DFHPF19
    pub dfhpf19: FixedString<1>,
    /// DFHPF20
    pub dfhpf20: FixedString<1>,
    /// DFHPF21
    pub dfhpf21: FixedString<1>,
    /// DFHPF22
    pub dfhpf22: FixedString<1>,
    /// DFHPF23
    pub dfhpf23: FixedString<1>,
    /// DFHPF24
    pub dfhpf24: FixedString<1>,
    /// DFHPEN
    pub dfhpen: FixedString<1>,
    /// DFHOPID
    pub dfhopid: FixedString<1>,
    /// DFHMSRE
    pub dfhmsre: FixedString<1>,
    /// DFHSTRF
    pub dfhstrf: FixedString<1>,
    /// DFHTRIG
    pub dfhtrig: FixedString<1>,
    /// DFHBMPEM
    pub dfhbmpem: FixedString<1>,
    /// DFHBMPRO
    pub dfhbmpro: FixedString<1>,
    /// DFHBMASK
    pub dfhbmask: FixedString<1>,
    /// DFHBMUNP
    pub dfhbmunp: FixedString<1>,
    /// DFHBMUNN
    pub dfhbmunn: FixedString<1>,
    /// DFHBMFSE
    pub dfhbmfse: FixedString<1>,
    /// DFHBMPRF
    pub dfhbmprf: FixedString<1>,
    /// DFHBMASF
    pub dfhbmasf: FixedString<1>,
    /// DFHBMASB
    pub dfhbmasb: FixedString<1>,
    /// DFHBMPNL
    pub dfhbmpnl: FixedString<1>,
    /// DFHBMEOF
    pub dfhbmeof: FixedString<1>,
    /// DFHBMDAR
    pub dfhbmdar: FixedString<1>,
    /// DFHBMDEF
    pub dfhbmdef: FixedString<1>,
    /// DFHBMBRY
    pub dfhbmbry: FixedString<1>,
    /// DFHBMFIL
    pub dfhbmfil: FixedString<1>,
    /// DFHSA
    pub dfhsa: FixedString<1>,
    /// DFHCOLOR
    pub dfhcolor: FixedString<1>,
    /// DFHPS
    pub dfhps: FixedString<1>,
    /// DFHHLT
    pub dfhhlt: FixedString<1>,
    /// DFHVAL
    pub dfhval: FixedString<1>,
    /// DFHOUTLN
    pub dfhoutln: FixedString<1>,
    /// DFHSOSI
    pub dfhsosi: FixedString<1>,
    /// DFHALL
    pub dfhall: FixedString<1>,
    /// DFHDFT
    pub dfhdft: FixedString<1>,
    /// DFHERROR
    pub dfherror: FixedString<1>,
    /// DFHDFCOL
    pub dfhdfcol: FixedString<1>,
    /// DFHBLUE
    pub dfhblue: FixedString<1>,
    /// DFHRED
    pub dfhred: FixedString<1>,
    /// DFHPINK
    pub dfhpink: FixedString<1>,
    /// DFHGREEN
    pub dfhgreen: FixedString<1>,
    /// DFHTURQ
    pub dfhturq: FixedString<1>,
    /// DFHYELLO
    pub dfhyello: FixedString<1>,
    /// DFHWHTE
    pub dfhwhte: FixedString<1>,
    /// DFHNEUTR
    pub dfhneutr: FixedString<1>,
    /// DFHDFHI
    pub dfhdfhi: FixedString<1>,
    /// DFHBLINK
    pub dfhblink: FixedString<1>,
    /// DFHREVRS
    pub dfhrevrs: FixedString<1>,
    /// DFHUNDLN
    pub dfhundln: FixedString<1>,
    /// LINKAGE: DFHCOMMAREA
    pub dfhcommarea: Dfhcommarea,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            cics: CicsContext::new(),
            ws_variables: Default::default(),
            ws_pgmname: Default::default(),
            ws_tranid: Default::default(),
            ws_message: Default::default(),
            ws_transact_file: Default::default(),
            ws_acctdat_file: Default::default(),
            ws_cxacaix_file: Default::default(),
            ws_err_flg: Default::default(),
            ws_resp_cd: Default::default(),
            ws_reas_cd: Default::default(),
            ws_usr_modified: Default::default(),
            ws_conf_pay_flg: Default::default(),
            ws_tran_amt: Default::default(),
            ws_curr_bal: Default::default(),
            ws_tran_id_num: Default::default(),
            ws_tran_date: Default::default(),
            ws_abs_time: Default::default(),
            ws_cur_date_x10: Default::default(),
            ws_cur_time_x08: Default::default(),
            carddemo_commarea: Default::default(),
            cdemo_general_info: Default::default(),
            cdemo_from_tranid: Default::default(),
            cdemo_from_program: Default::default(),
            cdemo_to_tranid: Default::default(),
            cdemo_to_program: Default::default(),
            cdemo_user_id: Default::default(),
            cdemo_user_type: Default::default(),
            cdemo_pgm_context: Default::default(),
            cdemo_customer_info: Default::default(),
            cdemo_cust_id: Default::default(),
            cdemo_cust_fname: Default::default(),
            cdemo_cust_mname: Default::default(),
            cdemo_cust_lname: Default::default(),
            cdemo_account_info: Default::default(),
            cdemo_acct_id: Default::default(),
            cdemo_acct_status: Default::default(),
            cdemo_card_info: Default::default(),
            cdemo_card_num: Default::default(),
            cdemo_more_info: Default::default(),
            cdemo_last_map: Default::default(),
            cdemo_last_mapset: Default::default(),
            cdemo_cb00_info: Default::default(),
            cdemo_cb00_trnid_first: Default::default(),
            cdemo_cb00_trnid_last: Default::default(),
            cdemo_cb00_page_num: Default::default(),
            cdemo_cb00_next_page_flg: Default::default(),
            cdemo_cb00_trn_sel_flg: Default::default(),
            cdemo_cb00_trn_selected: Default::default(),
            cobil0ai: Default::default(),
            trnnamel: Default::default(),
            trnnamef: Default::default(),
            trnnamei: Default::default(),
            title01l: Default::default(),
            title01f: Default::default(),
            title01i: Default::default(),
            curdatel: Default::default(),
            curdatef: Default::default(),
            curdatei: Default::default(),
            pgmnamel: Default::default(),
            pgmnamef: Default::default(),
            pgmnamei: Default::default(),
            title02l: Default::default(),
            title02f: Default::default(),
            title02i: Default::default(),
            curtimel: Default::default(),
            curtimef: Default::default(),
            curtimei: Default::default(),
            actidinl: Default::default(),
            actidinf: Default::default(),
            actidini: Default::default(),
            curball: Default::default(),
            curbalf: Default::default(),
            curbali: Default::default(),
            confirml: Default::default(),
            confirmf: Default::default(),
            confirmi: Default::default(),
            errmsgl: Default::default(),
            errmsgf: Default::default(),
            errmsgi: Default::default(),
            cobil0ao: Default::default(),
            trnnamec: Default::default(),
            trnnamep: Default::default(),
            trnnameh: Default::default(),
            trnnamev: Default::default(),
            trnnameo: Default::default(),
            title01c: Default::default(),
            title01p: Default::default(),
            title01h: Default::default(),
            title01v: Default::default(),
            title01o: Default::default(),
            curdatec: Default::default(),
            curdatep: Default::default(),
            curdateh: Default::default(),
            curdatev: Default::default(),
            curdateo: Default::default(),
            pgmnamec: Default::default(),
            pgmnamep: Default::default(),
            pgmnameh: Default::default(),
            pgmnamev: Default::default(),
            pgmnameo: Default::default(),
            title02c: Default::default(),
            title02p: Default::default(),
            title02h: Default::default(),
            title02v: Default::default(),
            title02o: Default::default(),
            curtimec: Default::default(),
            curtimep: Default::default(),
            curtimeh: Default::default(),
            curtimev: Default::default(),
            curtimeo: Default::default(),
            actidinc: Default::default(),
            actidinp: Default::default(),
            actidinh: Default::default(),
            actidinv: Default::default(),
            actidino: Default::default(),
            curbalc: Default::default(),
            curbalp: Default::default(),
            curbalh: Default::default(),
            curbalv: Default::default(),
            curbalo: Default::default(),
            confirmc: Default::default(),
            confirmp: Default::default(),
            confirmh: Default::default(),
            confirmv: Default::default(),
            confirmo: Default::default(),
            errmsgc: Default::default(),
            errmsgp: Default::default(),
            errmsgh: Default::default(),
            errmsgv: Default::default(),
            errmsgo: Default::default(),
            ccda_screen_title: Default::default(),
            ccda_title01: Default::default(),
            ccda_title02: Default::default(),
            ccda_thank_you: Default::default(),
            ws_date_time: Default::default(),
            ws_curdate_data: Default::default(),
            ws_curdate: Default::default(),
            ws_curdate_year: Default::default(),
            ws_curdate_month: Default::default(),
            ws_curdate_day: Default::default(),
            ws_curtime: Default::default(),
            ws_curtime_hours: Default::default(),
            ws_curtime_minute: Default::default(),
            ws_curtime_second: Default::default(),
            ws_curtime_milsec: Default::default(),
            ws_curdate_mm_dd_yy: Default::default(),
            ws_curdate_mm: Default::default(),
            ws_curdate_dd: Default::default(),
            ws_curdate_yy: Default::default(),
            ws_curtime_hh_mm_ss: Default::default(),
            ws_curtime_hh: Default::default(),
            ws_curtime_mm: Default::default(),
            ws_curtime_ss: Default::default(),
            ws_timestamp: Default::default(),
            ws_timestamp_dt_yyyy: Default::default(),
            ws_timestamp_dt_mm: Default::default(),
            ws_timestamp_dt_dd: Default::default(),
            ws_timestamp_tm_hh: Default::default(),
            ws_timestamp_tm_mm: Default::default(),
            ws_timestamp_tm_ss: Default::default(),
            ws_timestamp_tm_ms6: Default::default(),
            ccda_common_messages: Default::default(),
            ccda_msg_thank_you: Default::default(),
            ccda_msg_invalid_key: Default::default(),
            account_record: Default::default(),
            acct_id: Default::default(),
            acct_active_status: Default::default(),
            acct_curr_bal: Default::default(),
            acct_credit_limit: Default::default(),
            acct_cash_credit_limit: Default::default(),
            acct_open_date: Default::default(),
            acct_expiraion_date: Default::default(),
            acct_reissue_date: Default::default(),
            acct_curr_cyc_credit: Default::default(),
            acct_curr_cyc_debit: Default::default(),
            acct_addr_zip: Default::default(),
            acct_group_id: Default::default(),
            card_xref_record: Default::default(),
            xref_card_num: Default::default(),
            xref_cust_id: Default::default(),
            xref_acct_id: Default::default(),
            tran_record: Default::default(),
            tran_id: Default::default(),
            tran_type_cd: Default::default(),
            tran_cat_cd: Default::default(),
            tran_source: Default::default(),
            tran_desc: Default::default(),
            tran_amt: Default::default(),
            tran_merchant_id: Default::default(),
            tran_merchant_name: Default::default(),
            tran_merchant_city: Default::default(),
            tran_merchant_zip: Default::default(),
            tran_card_num: Default::default(),
            tran_orig_ts: Default::default(),
            tran_proc_ts: Default::default(),
            dfhenter: FixedString::from_str("}"),
            dfhclear: FixedString::from_str("m"),
            dfhpa1: FixedString::from_str("l"),
            dfhpa2: FixedString::from_str("n"),
            dfhpa3: FixedString::from_str("k"),
            dfhpf1: FixedString::from_str(" "),
            dfhpf2: FixedString::from_str(" "),
            dfhpf3: FixedString::from_str(" "),
            dfhpf4: FixedString::from_str(" "),
            dfhpf5: FixedString::from_str(" "),
            dfhpf6: FixedString::from_str(" "),
            dfhpf7: FixedString::from_str(" "),
            dfhpf8: FixedString::from_str(" "),
            dfhpf9: FixedString::from_str(" "),
            dfhpf10: FixedString::from_str("z"),
            dfhpf11: FixedString::from_str("{"),
            dfhpf12: FixedString::from_str("|"),
            dfhpf13: FixedString::from_str(" "),
            dfhpf14: FixedString::from_str(" "),
            dfhpf15: FixedString::from_str(" "),
            dfhpf16: FixedString::from_str(" "),
            dfhpf17: FixedString::from_str(" "),
            dfhpf18: FixedString::from_str(" "),
            dfhpf19: FixedString::from_str(" "),
            dfhpf20: FixedString::from_str(" "),
            dfhpf21: FixedString::from_str(" "),
            dfhpf22: FixedString::from_str("J"),
            dfhpf23: FixedString::from_str("K"),
            dfhpf24: FixedString::from_str("L"),
            dfhpen: FixedString::from_str("}"),
            dfhopid: FixedString::from_str(" "),
            dfhmsre: FixedString::from_str(" "),
            dfhstrf: FixedString::from_str(" "),
            dfhtrig: FixedString::from_str(" "),
            dfhbmpem: FixedString::from_str(" "),
            dfhbmpro: FixedString::from_str(" "),
            dfhbmask: FixedString::from_str(" "),
            dfhbmunp: FixedString::from_str("@"),
            dfhbmunn: FixedString::from_str("P"),
            dfhbmfse: FixedString::from_str(" "),
            dfhbmprf: FixedString::from_str("a"),
            dfhbmasf: FixedString::from_str("a"),
            dfhbmasb: FixedString::from_str("\x60"),
            dfhbmpnl: FixedString::from_str(" "),
            dfhbmeof: FixedString::from_str(" "),
            dfhbmdar: FixedString::from_str("<"),
            dfhbmdef: FixedString::from_str(" "),
            dfhbmbry: FixedString::from_str(" "),
            dfhbmfil: FixedString::from_str(" "),
            dfhsa: FixedString::from_str(" "),
            dfhcolor: FixedString::from_str(" "),
            dfhps: FixedString::from_str(" "),
            dfhhlt: FixedString::from_str(" "),
            dfhval: FixedString::from_str(" "),
            dfhoutln: FixedString::from_str(" "),
            dfhsosi: FixedString::from_str(" "),
            dfhall: FixedString::from_str(" "),
            dfhdft: FixedString::from_str(" "),
            dfherror: FixedString::from_str(" "),
            dfhdfcol: FixedString::from_str(" "),
            dfhblue: FixedString::from_str(" "),
            dfhred: FixedString::from_str(" "),
            dfhpink: FixedString::from_str(" "),
            dfhgreen: FixedString::from_str(" "),
            dfhturq: FixedString::from_str(" "),
            dfhyello: FixedString::from_str(" "),
            dfhwhte: FixedString::from_str(" "),
            dfhneutr: FixedString::from_str(" "),
            dfhdfhi: FixedString::from_str(" "),
            dfhblink: FixedString::from_str(" "),
            dfhrevrs: FixedString::from_str(" "),
            dfhundln: FixedString::from_str(" "),
            dfhcommarea: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// MAIN-PARA
fn p_main_para(state: &mut ProgramState) {
    state.ws_variables.ws_err_flg = "N".into();
    state.ws_variables.ws_usr_modified = "N".into();
    state.ws_variables.ws_message = FixedString::spaces();
    state.cobil0ao.errmsgo = FixedString::spaces();
    // SKIP: unresolved condition
    // EXEC CICS RETURN 
    state.cics.execute("RETURN", &[("TRANSID", Some("_unknown")), ("WS-TRANID", Some("_unknown")), ("COMMAREA", Some("_unknown")), ("CARDDEMO-COMMAREA", Some("_unknown"))]);
}

/// PROCESS-ENTER-KEY
fn p_process_enter_key(state: &mut ProgramState) {
    state.ws_variables.ws_conf_pay_flg = "N".into();
    if state.cobil0ai.actidini.to_string().trim() != "" {
    } else {
        if true {
        }
    }
    if !(state.ws_variables.ws_err_flg == "Y") {
        state.account_record.acct_id = state.cobil0ai.actidini.trimmed().parse::<u64>().unwrap_or(0);
        state.card_xref_record.xref_acct_id = state.cobil0ai.actidini.trimmed().parse::<u64>().unwrap_or(0);
        if state.cobil0ai.confirmi.to_string() == "Y" || state.cobil0ai.confirmi.to_string() == "y" {
            state.ws_variables.ws_conf_pay_flg = "Y".into();
            p_read_acctdat_file(state);
        } else {
            if state.cobil0ai.confirmi.to_string() == "N" || state.cobil0ai.confirmi.to_string() == "n" {
                p_clear_current_screen(state);
                state.ws_variables.ws_err_flg = "Y".into();
            } else {
                if state.cobil0ai.confirmi == FixedString::spaces() || state.cobil0ai.confirmi == FixedString::low_values() {
                    p_read_acctdat_file(state);
                } else {
                    if true {
                        state.ws_variables.ws_err_flg = "Y".into();
                        state.ws_variables.ws_message = "Invalid value. Valid values are (Y/N)...".into();
                        state.cobil0ai.confirml = -1 as i32;
                        p_send_billpay_screen(state);
                    }
                }
            }
        }
        state.ws_variables.ws_curr_bal = i64::from(state.account_record.acct_curr_bal) as u64;
        state.cobil0ai.curbali = (state.ws_variables.ws_curr_bal).into();
    }
    if !(state.ws_variables.ws_err_flg == "Y") {
        // SKIP: unresolved condition
    }
    if !(state.ws_variables.ws_err_flg == "Y") {
        if state.ws_variables.ws_conf_pay_flg == "Y" {
            p_read_cxacaix_file(state);
            state.tran_record.tran_id = FixedString::high_values();
            p_startbr_transact_file(state);
            p_readprev_transact_file(state);
            p_endbr_transact_file(state);
            state.ws_variables.ws_tran_id_num = state.tran_record.tran_id.trimmed().parse::<u64>().unwrap_or(0);
            state.ws_variables.ws_tran_id_num += 1u64;
            state.tran_record = Default::default();
            state.tran_record.tran_id = (state.ws_variables.ws_tran_id_num).into();
            state.tran_record.tran_type_cd = "02".into();
            state.tran_record.tran_cat_cd = 2 as u32;
            state.tran_record.tran_source = "POS TERM".into();
            state.tran_record.tran_desc = "BILL PAYMENT - ONLINE".into();
            state.tran_record.tran_amt = Decimal::from_i64(state.account_record.acct_curr_bal.value, state.account_record.acct_curr_bal.scale);
            state.tran_record.tran_card_num = FixedString::copy_from(&state.card_xref_record.xref_card_num);
            state.tran_record.tran_merchant_id = 999999999 as u32;
            state.tran_record.tran_merchant_name = "BILL PAYMENT".into();
            state.tran_record.tran_merchant_city = "N/A".into();
            state.tran_record.tran_merchant_zip = "N/A".into();
            p_get_current_timestamp(state);
            state.tran_record.tran_orig_ts = FixedString::copy_from(&state.ws_date_time.ws_timestamp);
            state.tran_record.tran_proc_ts = FixedString::copy_from(&state.ws_date_time.ws_timestamp);
            p_write_transact_file(state);
            state.account_record.acct_curr_bal = Decimal::from(i64::from(state.account_record.acct_curr_bal - state.tran_record.tran_amt));
            p_update_acctdat_file(state);
        } else {
            state.ws_variables.ws_message = "Confirm to make a bill payment...".into();
            state.cobil0ai.confirml = -1 as i32;
        }
        p_send_billpay_screen(state);
    }
}

/// GET-CURRENT-TIMESTAMP
fn p_get_current_timestamp(state: &mut ProgramState) {
    // EXEC CICS ASKTIME 
    state.cics.execute("ASKTIME", &[("ABSTIME", Some("_unknown")), ("WS-ABS-TIME", Some("_unknown"))]);
    // EXEC CICS FORMATTIME 
    state.cics.execute("FORMATTIME", &[("ABSTIME", Some("_unknown")), ("WS-ABS-TIME", Some("_unknown")), ("YYYYMMDD", Some("_unknown")), ("WS-CUR-DATE-X10", Some("_unknown")), ("DATESEP", Some("_unknown")), ("_unknown", Some("_unknown")), ("TIME", Some("_unknown")), ("WS-CUR-TIME-X08", Some("_unknown")), ("TIMESEP", Some("_unknown")), ("_unknown", Some("_unknown"))]);
    state.ws_date_time.ws_timestamp = Default::default();
    { /* refmod MOVE to struct WS-TIMESTAMP skipped */ }
    { /* refmod MOVE to struct WS-TIMESTAMP skipped */ }
    state.ws_date_time.ws_timestamp.ws_timestamp_tm_ms6 = 0;
}

/// RETURN-TO-PREV-SCREEN
fn p_return_to_prev_screen(state: &mut ProgramState) {
    // SKIP: unresolved condition
    state.carddemo_commarea.cdemo_general_info.cdemo_from_tranid = FixedString::copy_from(&state.ws_variables.ws_tranid);
    state.carddemo_commarea.cdemo_general_info.cdemo_from_program = FixedString::copy_from(&state.ws_variables.ws_pgmname);
    // SKIP: unresolved ref
}

/// SEND-BILLPAY-SCREEN
fn p_send_billpay_screen(state: &mut ProgramState) {
    p_populate_header_info(state);
    // SKIP: unresolved ref
}

/// RECEIVE-BILLPAY-SCREEN
fn p_receive_billpay_screen(state: &mut ProgramState) {
    // EXEC CICS RECEIVE 
    state.cics.execute("RECEIVE", &[("MAP", Some("_unknown")), ("_unknown", Some("_unknown")), ("MAPSET", Some("_unknown")), ("_unknown", Some("_unknown")), ("INTO", Some("_unknown")), ("COBIL0AI", Some("_unknown")), ("RESP", Some("_unknown")), ("WS-RESP-CD", Some("_unknown")), ("RESP2", Some("_unknown")), ("WS-REAS-CD", Some("_unknown"))]);
}

/// POPULATE-HEADER-INFO
fn p_populate_header_info(state: &mut ProgramState) {
    {
        let _bytes = b"20260319120000+0000";
        let _len = _bytes.len();
        if _len > 0 { let _end = _len.min(0+4); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.ws_date_time.ws_curdate_data.ws_curdate.ws_curdate_year = _s.parse().unwrap_or_default(); }
        if _len > 4 { let _end = _len.min(4+2); let _s = String::from_utf8_lossy(&_bytes[4.._end]).trim().to_string(); state.ws_date_time.ws_curdate_data.ws_curdate.ws_curdate_month = _s.parse().unwrap_or_default(); }
        if _len > 6 { let _end = _len.min(6+2); let _s = String::from_utf8_lossy(&_bytes[6.._end]).trim().to_string(); state.ws_date_time.ws_curdate_data.ws_curdate.ws_curdate_day = _s.parse().unwrap_or_default(); }
        if _len > 0 { let _end = _len.min(0+8); let _s = String::from_utf8_lossy(&_bytes[0.._end]).trim().to_string(); state.ws_date_time.ws_curdate_data.ws_curdate_n = _s.parse().unwrap_or_default(); }
        if _len > 8 { let _end = _len.min(8+2); let _s = String::from_utf8_lossy(&_bytes[8.._end]).trim().to_string(); state.ws_date_time.ws_curdate_data.ws_curtime.ws_curtime_hours = _s.parse().unwrap_or_default(); }
        if _len > 10 { let _end = _len.min(10+2); let _s = String::from_utf8_lossy(&_bytes[10.._end]).trim().to_string(); state.ws_date_time.ws_curdate_data.ws_curtime.ws_curtime_minute = _s.parse().unwrap_or_default(); }
        if _len > 12 { let _end = _len.min(12+2); let _s = String::from_utf8_lossy(&_bytes[12.._end]).trim().to_string(); state.ws_date_time.ws_curdate_data.ws_curtime.ws_curtime_second = _s.parse().unwrap_or_default(); }
        if _len > 14 { let _end = _len.min(14+2); let _s = String::from_utf8_lossy(&_bytes[14.._end]).trim().to_string(); state.ws_date_time.ws_curdate_data.ws_curtime.ws_curtime_milsec = _s.parse().unwrap_or_default(); }
        if _len > 8 { let _end = _len.min(8+8); let _s = String::from_utf8_lossy(&_bytes[8.._end]).trim().to_string(); state.ws_date_time.ws_curdate_data.ws_curtime_n = _s.parse().unwrap_or_default(); }
    }
    state.cobil0ao.title01o = FixedString::copy_from(&state.ccda_screen_title.ccda_title01);
    state.cobil0ao.title02o = FixedString::copy_from(&state.ccda_screen_title.ccda_title02);
    state.cobil0ao.trnnameo = FixedString::copy_from(&state.ws_variables.ws_tranid);
    state.cobil0ao.pgmnameo = FixedString::copy_from(&state.ws_variables.ws_pgmname);
    state.ws_date_time.ws_curdate_mm_dd_yy.ws_curdate_mm = state.ws_date_time.ws_curdate_data.ws_curdate.ws_curdate_month as u32;
    state.ws_date_time.ws_curdate_mm_dd_yy.ws_curdate_dd = state.ws_date_time.ws_curdate_data.ws_curdate.ws_curdate_day as u32;
    state.ws_date_time.ws_curdate_mm_dd_yy.ws_curdate_yy = { let _rm_s = state.ws_date_time.ws_curdate_data.ws_curdate.ws_curdate_year.to_string(); String::from(&_rm_s[(3 - 1) as usize..(3 - 1 + 2) as usize]) }.trim().parse::<u32>().unwrap_or(0);
    state.cobil0ao.curdateo = FixedString::copy_from(&state.ws_date_time.ws_curdate_mm_dd_yy);
    state.ws_date_time.ws_curtime_hh_mm_ss.ws_curtime_hh = state.ws_date_time.ws_curdate_data.ws_curtime.ws_curtime_hours as u32;
    state.ws_date_time.ws_curtime_hh_mm_ss.ws_curtime_mm = state.ws_date_time.ws_curdate_data.ws_curtime.ws_curtime_minute as u32;
    state.ws_date_time.ws_curtime_hh_mm_ss.ws_curtime_ss = state.ws_date_time.ws_curdate_data.ws_curtime.ws_curtime_second as u32;
    state.cobil0ao.curtimeo = FixedString::copy_from(&state.ws_date_time.ws_curtime_hh_mm_ss);
}

/// READ-ACCTDAT-FILE
fn p_read_acctdat_file(state: &mut ProgramState) {
    // EXEC CICS READ 
    state.cics.execute("READ", &[("DATASET", Some("_unknown")), ("WS-ACCTDAT-FILE", Some("_unknown")), ("INTO", Some("_unknown")), ("ACCOUNT-RECORD", Some("_unknown")), ("LENGTH", Some("_unknown")), ("LENGTH", Some("OF")), ("ACCOUNT-RECORD", Some("_unknown")), ("RIDFLD", Some("_unknown")), ("ACCT-ID", Some("_unknown")), ("KEYLENGTH", Some("_unknown")), ("LENGTH", Some("OF")), ("ACCT-ID", Some("_unknown")), ("UPDATE", None), ("RESP", Some("_unknown")), ("WS-RESP-CD", Some("_unknown")), ("RESP2", Some("_unknown")), ("WS-REAS-CD", Some("_unknown"))]);
    match state.ws_variables.ws_resp_cd {
        _ => {}
        _ => {
            state.ws_variables.ws_err_flg = "Y".into();
            state.ws_variables.ws_message = "Account ID NOT found...".into();
            state.cobil0ai.actidinl = -1 as i32;
            p_send_billpay_screen(state);
        }
        _ => {
            println!("{}{}{}{}", "RESP:", state.ws_variables.ws_resp_cd, "REAS:", state.ws_variables.ws_reas_cd);
            state.ws_variables.ws_err_flg = "Y".into();
            state.ws_variables.ws_message = "Unable to lookup Account...".into();
            state.cobil0ai.actidinl = -1 as i32;
            p_send_billpay_screen(state);
        }
    }
}

/// UPDATE-ACCTDAT-FILE
fn p_update_acctdat_file(state: &mut ProgramState) {
    // EXEC CICS REWRITE 
    state.cics.execute("REWRITE", &[("DATASET", Some("_unknown")), ("WS-ACCTDAT-FILE", Some("_unknown")), ("FROM", Some("_unknown")), ("ACCOUNT-RECORD", Some("_unknown")), ("LENGTH", Some("_unknown")), ("LENGTH", Some("OF")), ("ACCOUNT-RECORD", Some("_unknown")), ("RESP", Some("_unknown")), ("WS-RESP-CD", Some("_unknown")), ("RESP2", Some("_unknown")), ("WS-REAS-CD", Some("_unknown"))]);
    match state.ws_variables.ws_resp_cd {
        _ => {}
        _ => {
            state.ws_variables.ws_err_flg = "Y".into();
            state.ws_variables.ws_message = "Account ID NOT found...".into();
            state.cobil0ai.actidinl = -1 as i32;
            p_send_billpay_screen(state);
        }
        _ => {
            println!("{}{}{}{}", "RESP:", state.ws_variables.ws_resp_cd, "REAS:", state.ws_variables.ws_reas_cd);
            state.ws_variables.ws_err_flg = "Y".into();
            state.ws_variables.ws_message = "Unable to Update Account...".into();
            state.cobil0ai.actidinl = -1 as i32;
            p_send_billpay_screen(state);
        }
    }
}

/// READ-CXACAIX-FILE
fn p_read_cxacaix_file(state: &mut ProgramState) {
    // EXEC CICS READ 
    state.cics.execute("READ", &[("DATASET", Some("_unknown")), ("WS-CXACAIX-FILE", Some("_unknown")), ("INTO", Some("_unknown")), ("CARD-XREF-RECORD", Some("_unknown")), ("LENGTH", Some("_unknown")), ("LENGTH", Some("OF")), ("CARD-XREF-RECORD", Some("_unknown")), ("RIDFLD", Some("_unknown")), ("XREF-ACCT-ID", Some("_unknown")), ("KEYLENGTH", Some("_unknown")), ("LENGTH", Some("OF")), ("XREF-ACCT-ID", Some("_unknown")), ("RESP", Some("_unknown")), ("WS-RESP-CD", Some("_unknown")), ("RESP2", Some("_unknown")), ("WS-REAS-CD", Some("_unknown"))]);
    match state.ws_variables.ws_resp_cd {
        _ => {}
        _ => {
            state.ws_variables.ws_err_flg = "Y".into();
            state.ws_variables.ws_message = "Account ID NOT found...".into();
            state.cobil0ai.actidinl = -1 as i32;
            p_send_billpay_screen(state);
        }
        _ => {
            println!("{}{}{}{}", "RESP:", state.ws_variables.ws_resp_cd, "REAS:", state.ws_variables.ws_reas_cd);
            state.ws_variables.ws_err_flg = "Y".into();
            state.ws_variables.ws_message = "Unable to lookup XREF AIX file...".into();
            state.cobil0ai.actidinl = -1 as i32;
            p_send_billpay_screen(state);
        }
    }
}

/// STARTBR-TRANSACT-FILE
fn p_startbr_transact_file(state: &mut ProgramState) {
    // EXEC CICS STARTBR 
    state.cics.execute("STARTBR", &[("DATASET", Some("_unknown")), ("WS-TRANSACT-FILE", Some("_unknown")), ("RIDFLD", Some("_unknown")), ("TRAN-ID", Some("_unknown")), ("KEYLENGTH", Some("_unknown")), ("LENGTH", Some("OF")), ("TRAN-ID", Some("_unknown")), ("RESP", Some("_unknown")), ("WS-RESP-CD", Some("_unknown")), ("RESP2", Some("_unknown")), ("WS-REAS-CD", Some("_unknown"))]);
    match state.ws_variables.ws_resp_cd {
        _ => {}
        _ => {
            state.ws_variables.ws_err_flg = "Y".into();
            state.ws_variables.ws_message = "Transaction ID NOT found...".into();
            state.cobil0ai.actidinl = -1 as i32;
            p_send_billpay_screen(state);
        }
        _ => {
            println!("{}{}{}{}", "RESP:", state.ws_variables.ws_resp_cd, "REAS:", state.ws_variables.ws_reas_cd);
            state.ws_variables.ws_err_flg = "Y".into();
            state.ws_variables.ws_message = "Unable to lookup Transaction...".into();
            state.cobil0ai.actidinl = -1 as i32;
            p_send_billpay_screen(state);
        }
    }
}

/// READPREV-TRANSACT-FILE
fn p_readprev_transact_file(state: &mut ProgramState) {
    // EXEC CICS READPREV 
    state.cics.execute("READPREV", &[("DATASET", Some("_unknown")), ("WS-TRANSACT-FILE", Some("_unknown")), ("INTO", Some("_unknown")), ("TRAN-RECORD", Some("_unknown")), ("LENGTH", Some("_unknown")), ("LENGTH", Some("OF")), ("TRAN-RECORD", Some("_unknown")), ("RIDFLD", Some("_unknown")), ("TRAN-ID", Some("_unknown")), ("KEYLENGTH", Some("_unknown")), ("LENGTH", Some("OF")), ("TRAN-ID", Some("_unknown")), ("RESP", Some("_unknown")), ("WS-RESP-CD", Some("_unknown")), ("RESP2", Some("_unknown")), ("WS-REAS-CD", Some("_unknown"))]);
    match state.ws_variables.ws_resp_cd {
        _ => {}
        _ => {
            state.tran_record.tran_id = Default::default();
        }
        _ => {
            println!("{}{}{}{}", "RESP:", state.ws_variables.ws_resp_cd, "REAS:", state.ws_variables.ws_reas_cd);
            state.ws_variables.ws_err_flg = "Y".into();
            state.ws_variables.ws_message = "Unable to lookup Transaction...".into();
            state.cobil0ai.actidinl = -1 as i32;
            p_send_billpay_screen(state);
        }
    }
}

/// ENDBR-TRANSACT-FILE
fn p_endbr_transact_file(state: &mut ProgramState) {
    // EXEC CICS ENDBR 
    state.cics.execute("ENDBR", &[("DATASET", Some("_unknown")), ("WS-TRANSACT-FILE", Some("_unknown"))]);
}

/// WRITE-TRANSACT-FILE
fn p_write_transact_file(state: &mut ProgramState) {
    // EXEC CICS WRITE 
    state.cics.execute("WRITE", &[("DATASET", Some("_unknown")), ("WS-TRANSACT-FILE", Some("_unknown")), ("FROM", Some("_unknown")), ("TRAN-RECORD", Some("_unknown")), ("LENGTH", Some("_unknown")), ("LENGTH", Some("OF")), ("TRAN-RECORD", Some("_unknown")), ("RIDFLD", Some("_unknown")), ("TRAN-ID", Some("_unknown")), ("KEYLENGTH", Some("_unknown")), ("LENGTH", Some("OF")), ("TRAN-ID", Some("_unknown")), ("RESP", Some("_unknown")), ("WS-RESP-CD", Some("_unknown")), ("RESP2", Some("_unknown")), ("WS-REAS-CD", Some("_unknown"))]);
    match state.ws_variables.ws_resp_cd {
        _ => {
            p_initialize_all_fields(state);
            state.ws_variables.ws_message = FixedString::spaces();
            state.cobil0ao.errmsgc = FixedString::copy_from(&state.dfhgreen);
            {
                let mut _str_ptr: usize = 1;
                string_append(state.ws_variables.ws_message.as_bytes_mut(), &mut _str_ptr, "Payment successful. ".as_bytes());
                string_append(state.ws_variables.ws_message.as_bytes_mut(), &mut _str_ptr, " Your Transaction ID is ".as_bytes());
                let _bytes_tmp = state.tran_record.tran_id.to_string(); let _src = string_delimited(_bytes_tmp.as_bytes(), b" ");
                string_append(state.ws_variables.ws_message.as_bytes_mut(), &mut _str_ptr, _src);
                string_append(state.ws_variables.ws_message.as_bytes_mut(), &mut _str_ptr, ".".as_bytes());
            }
            p_send_billpay_screen(state);
        }
        _ | _ => {
            state.ws_variables.ws_err_flg = "Y".into();
            state.ws_variables.ws_message = "Tran ID already exist...".into();
            state.cobil0ai.actidinl = -1 as i32;
            p_send_billpay_screen(state);
        }
        _ => {
            println!("{}{}{}{}", "RESP:", state.ws_variables.ws_resp_cd, "REAS:", state.ws_variables.ws_reas_cd);
            state.ws_variables.ws_err_flg = "Y".into();
            state.ws_variables.ws_message = "Unable to Add Bill pay Transaction...".into();
            state.cobil0ai.actidinl = -1 as i32;
            p_send_billpay_screen(state);
        }
    }
}

/// CLEAR-CURRENT-SCREEN
fn p_clear_current_screen(state: &mut ProgramState) {
    p_initialize_all_fields(state);
    p_send_billpay_screen(state);
}

/// INITIALIZE-ALL-FIELDS
fn p_initialize_all_fields(state: &mut ProgramState) {
    state.cobil0ai.actidinl = -1 as i32;
    state.cobil0ai.actidini = FixedString::spaces();
    state.cobil0ai.curbali = FixedString::spaces();
    state.cobil0ai.confirmi = FixedString::spaces();
    state.ws_variables.ws_message = FixedString::spaces();
}

fn main() {
    let mut state = ProgramState::default();
    p_main_para(&mut state);
}

