use std::collections::HashMap;
// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use std::io::{BufRead, BufReader, BufWriter, Write};
use std::fs::File;

use cobol_runtime::FixedString;
use cobol_runtime::Sqlca;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsInputVars {
    /// INPUT-TYPE
    pub input_type: FixedString<1>,
    /// INPUT-TR-NUMBER
    pub input_tr_number: FixedString<2>,
    /// INPUT-TR-DESC
    pub input_tr_desc: FixedString<50>,
}
impl std::fmt::Display for WsInputVars {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.input_type, self.input_tr_number, self.input_tr_desc)
    }
}
impl From<&str> for WsInputVars {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsInputVars {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsInputVars {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct TrRecord {
    /// WS-INPUT-VARS
    pub ws_input_vars: WsInputVars,
}
impl std::fmt::Display for TrRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.ws_input_vars)
    }
}
impl From<&str> for TrRecord {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for TrRecord {
    fn from(_s: String) -> Self { Self::default() }
}
impl TrRecord {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Flags {
    /// LASTREC
    pub lastrec: FixedString<1>,
}
impl std::fmt::Display for Flags {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.lastrec)
    }
}
impl From<&str> for Flags {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Flags {
    fn from(_s: String) -> Self { Self::default() }
}
impl Flags {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WorkingVariables {
    /// WS-RETURN-MSG
    pub ws_return_msg: FixedString<80>,
}
impl std::fmt::Display for WorkingVariables {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.ws_return_msg)
    }
}
impl From<&str> for WorkingVariables {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WorkingVariables {
    fn from(_s: String) -> Self { Self::default() }
}
impl WorkingVariables {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsMiscVars {
    /// WS-VAR-SQLCODE
    pub ws_var_sqlcode: u32,
}
impl std::fmt::Display for WsMiscVars {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}", self.ws_var_sqlcode)
    }
}
impl From<&str> for WsMiscVars {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsMiscVars {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsMiscVars {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsInfStatus {
    /// WS-INF-STAT1
    pub ws_inf_stat1: FixedString<1>,
    /// WS-INF-STAT2
    pub ws_inf_stat2: FixedString<1>,
}
impl std::fmt::Display for WsInfStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.ws_inf_stat1, self.ws_inf_stat2)
    }
}
impl From<&str> for WsInfStatus {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsInfStatus {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsInfStatus {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsInputRec {
    /// INPUT-REC-TYPE
    pub input_rec_type: FixedString<1>,
    /// INPUT-REC-NUMBER
    pub input_rec_number: FixedString<2>,
    /// INPUT-REC-DESC
    pub input_rec_desc: FixedString<50>,
}
impl std::fmt::Display for WsInputRec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}", self.input_rec_type, self.input_rec_number, self.input_rec_desc)
    }
}
impl From<&str> for WsInputRec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsInputRec {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsInputRec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    pub _unresolved_sqlcode: FixedString<8>,
    pub _unresolved_tr_description: FixedString<8>,
    pub host_vars: HashMap<String, String>,
    pub sql: Sqlca,
    /// FD group: WS-INPUT-VARS
    pub ws_input_vars: FixedString<53>,
    /// FD: INPUT-TYPE
    pub input_type: FixedString<1>,
    /// FD: INPUT-TR-NUMBER
    pub input_tr_number: FixedString<2>,
    /// FD: INPUT-TR-DESC
    pub input_tr_desc: FixedString<50>,
    /// FLAGS
    pub flags: Flags,
    /// LASTREC
    pub lastrec: FixedString<1>,
    /// WORKING-VARIABLES
    pub working_variables: WorkingVariables,
    /// WS-RETURN-MSG
    pub ws_return_msg: FixedString<80>,
    /// WS-MISC-VARS
    pub ws_misc_vars: WsMiscVars,
    /// WS-VAR-SQLCODE
    pub ws_var_sqlcode: u32,
    /// WS-INF-STATUS
    pub ws_inf_status: WsInfStatus,
    /// WS-INF-STAT1
    pub ws_inf_stat1: FixedString<1>,
    /// WS-INF-STAT2
    pub ws_inf_stat2: FixedString<1>,
    /// WS-INPUT-REC
    pub ws_input_rec: WsInputRec,
    /// INPUT-REC-TYPE
    pub input_rec_type: FixedString<1>,
    /// INPUT-REC-NUMBER
    pub input_rec_number: FixedString<2>,
    /// INPUT-REC-DESC
    pub input_rec_desc: FixedString<50>,
    /// File status for TR-RECORD
    pub _fs_tr_record: FileStatus,
    /// File handle for TR-RECORD
    pub _fh_tr_record: CobolFile,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            sql: Sqlca::default(),
            host_vars: HashMap::new(),
            _unresolved_sqlcode: Default::default(),
            _unresolved_tr_description: Default::default(),
            ws_input_vars: Default::default(),
            input_type: Default::default(),
            input_tr_number: Default::default(),
            input_tr_desc: Default::default(),
            flags: Default::default(),
            lastrec: Default::default(),
            working_variables: Default::default(),
            ws_return_msg: Default::default(),
            ws_misc_vars: Default::default(),
            ws_var_sqlcode: Default::default(),
            ws_inf_status: Default::default(),
            ws_inf_stat1: Default::default(),
            ws_inf_stat2: Default::default(),
            ws_input_rec: Default::default(),
            input_rec_type: Default::default(),
            input_rec_number: Default::default(),
            input_rec_desc: Default::default(),
            _fs_tr_record: FileStatus::Success,
            _fh_tr_record: CobolFile::Closed,
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// 0001-OPEN-FILES
fn p_0001_open_files(state: &mut ProgramState) {
    tr_record_open_input(state);
    if { let _s = format!("{}", state.ws_inf_status); _s.trim().to_string() } == "00".to_string() {
        println!("{}", "OPEN FILE OK");
    } else {
        println!("{}", "OPEN FILE NOT OK");
    }
}

/// 1001-READ-NEXT-RECORDS
fn p_1001_read_next_records(state: &mut ProgramState) {
    p_1002_read_records(state);
    while !(&format!("{}", state.flags.lastrec) == &"Y".to_string()) {
        // SKIP: unresolved ref
    }
    p_2001_close_stop(state);
    { let _ = state._fh_tr_record.close();
        std::process::exit(0); }
}

/// 1002-READ-RECORDS
fn p_1002_read_records(state: &mut ProgramState) {
    tr_record_read(state);
    state.flags.lastrec = "Y".into();
    if &format!("{}", state.flags.lastrec) != &"Y".to_string() {
        println!("{}{}", "PROCESSING   ", state.ws_input_rec);
    }
}

/// 1003-TREAT-RECORD
fn p_1003_treat_record(state: &mut ProgramState) {
    if state.ws_input_rec.input_rec_type.to_string() == "A" {
        println!("{}", "ADDING RECORD");
        p_10031_insert_db(state);
    } else {
        if state.ws_input_rec.input_rec_type.to_string() == "U" {
            println!("{}", "UPDATING RECORD");
            p_10032_update_db(state);
        } else {
            if state.ws_input_rec.input_rec_type.to_string() == "D" {
                println!("{}", "DELETING RECORD");
                p_10033_delete_db(state);
            } else {
                if state.ws_input_rec.input_rec_type.to_string() == "*" {
                    println!("{}", "IGNORING COMMENTED LINE");
                } else {
                    if true {
                        {
                            let mut _str_ptr: usize = 1;
                            string_append(state.working_variables.ws_return_msg.as_bytes_mut(), &mut _str_ptr, "ERROR: TYPE NOT VALID".as_bytes());
                        }
                        p_9999_abend(state);
                    }
                }
            }
        }
    }
}

/// 10031-INSERT-DB
fn p_10031_insert_db(state: &mut ProgramState) {
    // EXEC SQL
    state.sql.execute_sql("INSERT INTO CARDDEMO", &[]);
}

/// END-EXEC
fn p_end_exec(state: &mut ProgramState) {
    // SKIP: unresolved ref: state.ws_misc_vars.ws_var_sqlcode = format!("{}", state._unresolved_sqlcode).trim().parse::<u32>().unwrap_or(0);
    // SKIP: unresolved condition
}

/// 10032-UPDATE-DB
fn p_10032_update_db(state: &mut ProgramState) {
    // EXEC SQL
    state.sql.execute_sql("UPDATE CARDDEMO", &[]);
    // SKIP: unresolved ref: state._unresolved_tr_description = Default::default();
    // SKIP: unresolved ref: state.ws_misc_vars.ws_var_sqlcode = format!("{}", state._unresolved_sqlcode).trim().parse::<u32>().unwrap_or(0);
    // SKIP: unresolved condition
}

/// 10033-DELETE-DB
fn p_10033_delete_db(state: &mut ProgramState) {
    // EXEC SQL
    state.sql.execute_sql("DELETE FROM CARDDEMO", &[]);
}

/// END-EXEC
fn p_end_exec_2(state: &mut ProgramState) {
    // SKIP: unresolved ref: state.ws_misc_vars.ws_var_sqlcode = format!("{}", state._unresolved_sqlcode).trim().parse::<u32>().unwrap_or(0);
    // SKIP: unresolved condition
}

/// 9999-ABEND
fn p_9999_abend(state: &mut ProgramState) {
    println!("{}", state.working_variables.ws_return_msg);
    state.return_code = 4 as i32;
}

/// 2001-CLOSE-STOP
fn p_2001_close_stop(state: &mut ProgramState) {
    tr_record_close(state);
}

/// STUB: p__unnamed
fn p__unnamed(state: &mut ProgramState) {
    // SKIP: unresolved ref
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// OPEN INPUT TR-RECORD
fn tr_record_open_input(state: &mut ProgramState) {
    let path = std::env::var("TR_RECORD").unwrap_or("tr_record.dat".to_string());
    match CobolFile::open_input(&path) {
        Ok(handle) => { state._fh_tr_record = handle; state._fs_tr_record = FileStatus::Success; }
        Err(_) => { state._fs_tr_record = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_tr_record); let _b = _s.as_bytes(); unsafe { let p = &mut state.ws_inf_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN OUTPUT TR-RECORD
fn tr_record_open_output(state: &mut ProgramState) {
    let path = std::env::var("TR_RECORD").unwrap_or("tr_record.dat".to_string());
    match CobolFile::open_output(&path) {
        Ok(handle) => { state._fh_tr_record = handle; state._fs_tr_record = FileStatus::Success; }
        Err(_) => { state._fs_tr_record = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_tr_record); let _b = _s.as_bytes(); unsafe { let p = &mut state.ws_inf_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// READ TR-RECORD
fn tr_record_read(state: &mut ProgramState) -> Result<(), FileStatus> {
    match state._fh_tr_record.read_line() {
        Ok(line) => {
            let _bytes = line.as_bytes();
            let _len = _bytes.len().min(53);
            if _len > 0 { let _end = _len.min(0+1); state.input_type = FixedString::from(String::from_utf8_lossy(&_bytes[0.._end])); }
            if _len > 1 { let _end = _len.min(1+2); state.input_tr_number = FixedString::from(String::from_utf8_lossy(&_bytes[1.._end])); }
            if _len > 3 { let _end = _len.min(3+50); state.input_tr_desc = FixedString::from(String::from_utf8_lossy(&_bytes[3.._end])); }
            state._fs_tr_record = FileStatus::Success;
    { let _s = format!("{}", state._fs_tr_record); let _b = _s.as_bytes(); unsafe { let p = &mut state.ws_inf_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(FileStatus::AtEnd) => {
            state._fs_tr_record = FileStatus::AtEnd;
    { let _s = format!("{}", state._fs_tr_record); let _b = _s.as_bytes(); unsafe { let p = &mut state.ws_inf_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
        Err(e) => {
            state._fs_tr_record = e.clone();
    { let _s = format!("{}", state._fs_tr_record); let _b = _s.as_bytes(); unsafe { let p = &mut state.ws_inf_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
        }
    }
    Ok(())
}

/// WRITE to TR-RECORD
fn tr_record_write(state: &mut ProgramState) {
    let mut _buf = vec![b' '; 53];
    { let _src = state.input_type.as_bytes(); let _end = (0+1).min(_buf.len()); let _cl = _src.len().min(_end-0); _buf[0..0+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.input_tr_number.as_bytes(); let _end = (1+2).min(_buf.len()); let _cl = _src.len().min(_end-1); _buf[1..1+_cl].copy_from_slice(&_src[.._cl]); }
    { let _src = state.input_tr_desc.as_bytes(); let _end = (3+50).min(_buf.len()); let _cl = _src.len().min(_end-3); _buf[3..3+_cl].copy_from_slice(&_src[.._cl]); }
    match state._fh_tr_record.write_record(&_buf) {
        Ok(()) => state._fs_tr_record = FileStatus::Success,
        Err(e) => state._fs_tr_record = e,
    }
}

/// CLOSE TR-RECORD
fn tr_record_close(state: &mut ProgramState) {
    match state._fh_tr_record.close() {
        Ok(()) => state._fs_tr_record = FileStatus::Success,
        Err(e) => state._fs_tr_record = e,
    }
    { let _s = format!("{}", state._fs_tr_record); let _b = _s.as_bytes(); unsafe { let p = &mut state.ws_inf_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN I-O TR-RECORD
fn tr_record_open_io(state: &mut ProgramState) {
    let path = std::env::var("TR_RECORD").unwrap_or("tr_record.dat".to_string());
    match CobolFile::open_io(&path) {
        Ok(handle) => { state._fh_tr_record = handle; state._fs_tr_record = FileStatus::Success; }
        Err(_) => { state._fs_tr_record = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_tr_record); let _b = _s.as_bytes(); unsafe { let p = &mut state.ws_inf_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

/// OPEN EXTEND TR-RECORD
fn tr_record_open_extend(state: &mut ProgramState) {
    let path = std::env::var("TR_RECORD").unwrap_or("tr_record.dat".to_string());
    match CobolFile::open_extend(&path) {
        Ok(handle) => { state._fh_tr_record = handle; state._fs_tr_record = FileStatus::Success; }
        Err(_) => { state._fs_tr_record = FileStatus::Error("35".to_string()); }
    }
    { let _s = format!("{}", state._fs_tr_record); let _b = _s.as_bytes(); unsafe { let p = &mut state.ws_inf_status as *mut _ as *mut u8; for i in 0.._b.len().min(2) { *p.add(i) = _b[i]; } } }
}

fn main() {
    let mut state = ProgramState::default();
    p_0001_open_files(&mut state);
}

