// Generated by Ironclad — Deterministic COBOL-to-Rust Transpiler
// Do not edit manually. Regenerate from COBOL source.

use cobol_runtime::chrono_shim::Local;

use cobol_runtime::FixedString;
use cobol_runtime::Decimal;
use cobol_runtime::PackedDecimal;
use cobol_runtime::FileStatus;
use cobol_runtime::CobolFile;
#[allow(unused_imports)]
use cobol_runtime::string_ops::*;
#[allow(unused_imports)]
use cobol_runtime::chrono_shim::*;


#[derive(Debug, Clone, Default, PartialEq)]
pub struct Opfil2Rec {
    /// ROOT-SEG-KEY
    pub root_seg_key: PackedDecimal<11> /* Signed */,
    /// CHILD-SEG-REC
    pub child_seg_rec: FixedString<200>,
}
impl std::fmt::Display for Opfil2Rec {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.root_seg_key, self.child_seg_rec)
    }
}
impl From<&str> for Opfil2Rec {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Opfil2Rec {
    fn from(_s: String) -> Self { Self::default() }
}
impl Opfil2Rec {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsVariables {
    /// WS-PGMNAME
    pub ws_pgmname: FixedString<8>,
    /// CURRENT-DATE
    pub current_date: u32,
    /// CURRENT-YYDDD
    pub current_yyddd: u32,
    /// WS-AUTH-DATE
    pub ws_auth_date: u32,
    /// WS-EXPIRY-DAYS
    pub ws_expiry_days: i32,
    /// WS-DAY-DIFF
    pub ws_day_diff: i32,
    /// IDX
    pub idx: i32,
    /// WS-CURR-APP-ID
    pub ws_curr_app_id: u64,
    /// WS-NO-CHKP
    pub ws_no_chkp: u32,
    /// WS-AUTH-SMRY-PROC-CNT
    pub ws_auth_smry_proc_cnt: u32,
    /// WS-TOT-REC-WRITTEN
    pub ws_tot_rec_written: i32,
    /// WS-NO-SUMRY-READ
    pub ws_no_sumry_read: i32,
    /// WS-NO-SUMRY-DELETED
    pub ws_no_sumry_deleted: i32,
    /// WS-NO-DTL-READ
    pub ws_no_dtl_read: i32,
    /// WS-NO-DTL-DELETED
    pub ws_no_dtl_deleted: i32,
    /// WS-ERR-FLG
    pub ws_err_flg: FixedString<1>,
    /// WS-END-OF-AUTHDB-FLAG
    pub ws_end_of_authdb_flag: FixedString<1>,
    /// WS-MORE-AUTHS-FLAG
    pub ws_more_auths_flag: FixedString<1>,
    /// WS-END-OF-ROOT-SEG
    pub ws_end_of_root_seg: FixedString<1>,
    /// WS-END-OF-CHILD-SEG
    pub ws_end_of_child_seg: FixedString<1>,
    /// WS-INFILE-STATUS
    pub ws_infile_status: FixedString<2>,
    /// WS-OUTFL1-STATUS
    pub ws_outfl1_status: FixedString<2>,
    /// WS-OUTFL2-STATUS
    pub ws_outfl2_status: FixedString<2>,
    /// WS-CUSTID-STATUS
    pub ws_custid_status: FixedString<2>,
    /// WK-CHKPT-ID
    pub wk_chkpt_id: WkChkptId,
}
impl std::fmt::Display for WsVariables {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self.ws_pgmname, self.current_date, self.current_yyddd, self.ws_auth_date, self.ws_expiry_days, self.ws_day_diff, self.idx, self.ws_curr_app_id, self.ws_no_chkp, self.ws_auth_smry_proc_cnt, self.ws_tot_rec_written, self.ws_no_sumry_read, self.ws_no_sumry_deleted, self.ws_no_dtl_read, self.ws_no_dtl_deleted, self.ws_err_flg, self.ws_end_of_authdb_flag, self.ws_more_auths_flag, self.ws_end_of_root_seg, self.ws_end_of_child_seg, self.ws_infile_status, self.ws_outfl1_status, self.ws_outfl2_status, self.ws_custid_status, self.wk_chkpt_id)
    }
}
impl From<&str> for WsVariables {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsVariables {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsVariables {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WkChkptId {
    /// FILLER PIC FILLER
    pub _filler_93: FixedString<4>,
    /// WK-CHKPT-ID-CTR
    pub wk_chkpt_id_ctr: u32,
}
impl std::fmt::Display for WkChkptId {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self._filler_93, self.wk_chkpt_id_ctr)
    }
}
impl From<&str> for WkChkptId {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WkChkptId {
    fn from(_s: String) -> Self { Self::default() }
}
impl WkChkptId {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct WsImsVariables {
    /// IMS-RETURN-CODE
    pub ims_return_code: FixedString<2>,
    /// WS-IMS-PSB-SCHD-FLG
    pub ws_ims_psb_schd_flg: FixedString<1>,
}
impl std::fmt::Display for WsImsVariables {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.ims_return_code, self.ws_ims_psb_schd_flg)
    }
}
impl From<&str> for WsImsVariables {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for WsImsVariables {
    fn from(_s: String) -> Self { Self::default() }
}
impl WsImsVariables {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct RootUnqualSsa {
    /// FILLER PIC FILLER
    pub _filler_116: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_117: FixedString<1>,
}
impl std::fmt::Display for RootUnqualSsa {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self._filler_116, self._filler_117)
    }
}
impl From<&str> for RootUnqualSsa {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for RootUnqualSsa {
    fn from(_s: String) -> Self { Self::default() }
}
impl RootUnqualSsa {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct ChildUnqualSsa {
    /// FILLER PIC FILLER
    pub _filler_120: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_121: FixedString<1>,
}
impl std::fmt::Display for ChildUnqualSsa {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self._filler_120, self._filler_121)
    }
}
impl From<&str> for ChildUnqualSsa {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for ChildUnqualSsa {
    fn from(_s: String) -> Self { Self::default() }
}
impl ChildUnqualSsa {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PrmInfo {
    /// P-EXPIRY-DAYS
    pub p_expiry_days: u32,
    /// FILLER PIC FILLER
    pub _filler_125: FixedString<1>,
    /// P-CHKP-FREQ
    pub p_chkp_freq: FixedString<5>,
    /// FILLER PIC FILLER
    pub _filler_127: FixedString<1>,
    /// P-CHKP-DIS-FREQ
    pub p_chkp_dis_freq: FixedString<5>,
    /// FILLER PIC FILLER
    pub _filler_129: FixedString<1>,
    /// P-DEBUG-FLAG
    pub p_debug_flag: FixedString<1>,
    /// FILLER PIC FILLER
    pub _filler_133: FixedString<1>,
}
impl std::fmt::Display for PrmInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}", self.p_expiry_days, self._filler_125, self.p_chkp_freq, self._filler_127, self.p_chkp_dis_freq, self._filler_129, self.p_debug_flag, self._filler_133)
    }
}
impl From<&str> for PrmInfo {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PrmInfo {
    fn from(_s: String) -> Self { Self::default() }
}
impl PrmInfo {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct FuncCodes {
    /// FUNC-GU
    pub func_gu: FixedString<4>,
    /// FUNC-GHU
    pub func_ghu: FixedString<4>,
    /// FUNC-GN
    pub func_gn: FixedString<4>,
    /// FUNC-GHN
    pub func_ghn: FixedString<4>,
    /// FUNC-GNP
    pub func_gnp: FixedString<4>,
    /// FUNC-GHNP
    pub func_ghnp: FixedString<4>,
    /// FUNC-REPL
    pub func_repl: FixedString<4>,
    /// FUNC-ISRT
    pub func_isrt: FixedString<4>,
    /// FUNC-DLET
    pub func_dlet: FixedString<4>,
    /// PARMCOUNT
    pub parmcount: i32,
}
impl std::fmt::Display for FuncCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}", self.func_gu, self.func_ghu, self.func_gn, self.func_ghn, self.func_gnp, self.func_ghnp, self.func_repl, self.func_isrt, self.func_dlet, self.parmcount)
    }
}
impl From<&str> for FuncCodes {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for FuncCodes {
    fn from(_s: String) -> Self { Self::default() }
}
impl FuncCodes {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PendingAuthSummary {
    /// PA-ACCT-ID
    pub pa_acct_id: PackedDecimal<11> /* Signed */,
    /// PA-CUST-ID
    pub pa_cust_id: u32,
    /// PA-AUTH-STATUS
    pub pa_auth_status: FixedString<1>,
    /// PA-ACCOUNT-STATUS
    pub pa_account_status: [FixedString<2>; 5],
    /// PA-CREDIT-LIMIT
    pub pa_credit_limit: PackedDecimal<11> /* Signed */,
    /// PA-CASH-LIMIT
    pub pa_cash_limit: PackedDecimal<11> /* Signed */,
    /// PA-CREDIT-BALANCE
    pub pa_credit_balance: PackedDecimal<11> /* Signed */,
    /// PA-CASH-BALANCE
    pub pa_cash_balance: PackedDecimal<11> /* Signed */,
    /// PA-APPROVED-AUTH-CNT
    pub pa_approved_auth_cnt: i32,
    /// PA-DECLINED-AUTH-CNT
    pub pa_declined_auth_cnt: i32,
    /// PA-APPROVED-AUTH-AMT
    pub pa_approved_auth_amt: PackedDecimal<11> /* Signed */,
    /// PA-DECLINED-AUTH-AMT
    pub pa_declined_auth_amt: PackedDecimal<11> /* Signed */,
    /// FILLER PIC FILLER
    pub _filler_199: FixedString<34>,
}
impl std::fmt::Display for PendingAuthSummary {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}", self.pa_acct_id, self.pa_cust_id, self.pa_auth_status, self.pa_credit_limit, self.pa_cash_limit, self.pa_credit_balance, self.pa_cash_balance, self.pa_approved_auth_cnt, self.pa_declined_auth_cnt, self.pa_approved_auth_amt, self.pa_declined_auth_amt, self._filler_199)
    }
}
impl From<&str> for PendingAuthSummary {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PendingAuthSummary {
    fn from(_s: String) -> Self { Self::default() }
}
impl PendingAuthSummary {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PendingAuthDetails {
    /// PA-AUTHORIZATION-KEY
    pub pa_authorization_key: PaAuthorizationKey,
    /// PA-AUTH-ORIG-DATE
    pub pa_auth_orig_date: FixedString<6>,
    /// PA-AUTH-ORIG-TIME
    pub pa_auth_orig_time: FixedString<6>,
    /// PA-CARD-NUM
    pub pa_card_num: FixedString<16>,
    /// PA-AUTH-TYPE
    pub pa_auth_type: FixedString<4>,
    /// PA-CARD-EXPIRY-DATE
    pub pa_card_expiry_date: FixedString<4>,
    /// PA-MESSAGE-TYPE
    pub pa_message_type: FixedString<6>,
    /// PA-MESSAGE-SOURCE
    pub pa_message_source: FixedString<6>,
    /// PA-AUTH-ID-CODE
    pub pa_auth_id_code: FixedString<6>,
    /// PA-AUTH-RESP-CODE
    pub pa_auth_resp_code: FixedString<2>,
    /// PA-AUTH-RESP-REASON
    pub pa_auth_resp_reason: FixedString<4>,
    /// PA-PROCESSING-CODE
    pub pa_processing_code: u32,
    /// PA-TRANSACTION-AMT
    pub pa_transaction_amt: PackedDecimal<12> /* Signed */,
    /// PA-APPROVED-AMT
    pub pa_approved_amt: PackedDecimal<12> /* Signed */,
    /// PA-MERCHANT-CATAGORY-CODE
    pub pa_merchant_catagory_code: FixedString<4>,
    /// PA-ACQR-COUNTRY-CODE
    pub pa_acqr_country_code: FixedString<3>,
    /// PA-POS-ENTRY-MODE
    pub pa_pos_entry_mode: u32,
    /// PA-MERCHANT-ID
    pub pa_merchant_id: FixedString<15>,
    /// PA-MERCHANT-NAME
    pub pa_merchant_name: FixedString<22>,
    /// PA-MERCHANT-CITY
    pub pa_merchant_city: FixedString<13>,
    /// PA-MERCHANT-STATE
    pub pa_merchant_state: FixedString<2>,
    /// PA-MERCHANT-ZIP
    pub pa_merchant_zip: FixedString<9>,
    /// PA-TRANSACTION-ID
    pub pa_transaction_id: FixedString<15>,
    /// PA-MATCH-STATUS
    pub pa_match_status: FixedString<1>,
    /// PA-AUTH-FRAUD
    pub pa_auth_fraud: FixedString<1>,
    /// PA-FRAUD-RPT-DATE
    pub pa_fraud_rpt_date: FixedString<8>,
    /// FILLER PIC FILLER
    pub _filler_256: FixedString<17>,
}
impl std::fmt::Display for PendingAuthDetails {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}", self.pa_authorization_key, self.pa_auth_orig_date, self.pa_auth_orig_time, self.pa_card_num, self.pa_auth_type, self.pa_card_expiry_date, self.pa_message_type, self.pa_message_source, self.pa_auth_id_code, self.pa_auth_resp_code, self.pa_auth_resp_reason, self.pa_processing_code, self.pa_transaction_amt, self.pa_approved_amt, self.pa_merchant_catagory_code, self.pa_acqr_country_code, self.pa_pos_entry_mode, self.pa_merchant_id, self.pa_merchant_name, self.pa_merchant_city, self.pa_merchant_state, self.pa_merchant_zip, self.pa_transaction_id, self.pa_match_status, self.pa_auth_fraud, self.pa_fraud_rpt_date, self._filler_256)
    }
}
impl From<&str> for PendingAuthDetails {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PendingAuthDetails {
    fn from(_s: String) -> Self { Self::default() }
}
impl PendingAuthDetails {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct PaAuthorizationKey {
    /// PA-AUTH-DATE-9C
    pub pa_auth_date_9c: PackedDecimal<5> /* Signed */,
    /// PA-AUTH-TIME-9C
    pub pa_auth_time_9c: PackedDecimal<9> /* Signed */,
}
impl std::fmt::Display for PaAuthorizationKey {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}", self.pa_auth_date_9c, self.pa_auth_time_9c)
    }
}
impl From<&str> for PaAuthorizationKey {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for PaAuthorizationKey {
    fn from(_s: String) -> Self { Self::default() }
}
impl PaAuthorizationKey {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Pautbpcb {
    /// PAUT-DBDNAME
    pub paut_dbdname: FixedString<8>,
    /// PAUT-SEG-LEVEL
    pub paut_seg_level: FixedString<2>,
    /// PAUT-PCB-STATUS
    pub paut_pcb_status: FixedString<2>,
    /// PAUT-PCB-PROCOPT
    pub paut_pcb_procopt: FixedString<4>,
    /// FILLER PIC FILLER
    pub _filler_284: i32,
    /// PAUT-SEG-NAME
    pub paut_seg_name: FixedString<8>,
    /// PAUT-KEYFB-NAME
    pub paut_keyfb_name: i32,
    /// PAUT-NUM-SENSEGS
    pub paut_num_sensegs: i32,
    /// PAUT-KEYFB
    pub paut_keyfb: FixedString<255>,
}
impl std::fmt::Display for Pautbpcb {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}", self.paut_dbdname, self.paut_seg_level, self.paut_pcb_status, self.paut_pcb_procopt, self._filler_284, self.paut_seg_name, self.paut_keyfb_name, self.paut_num_sensegs, self.paut_keyfb)
    }
}
impl From<&str> for Pautbpcb {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Pautbpcb {
    fn from(_s: String) -> Self { Self::default() }
}
impl Pautbpcb {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Pasflpcb {
    /// PASFL-DBDNAME
    pub pasfl_dbdname: FixedString<8>,
    /// PASFL-SEG-LEVEL
    pub pasfl_seg_level: FixedString<2>,
    /// PASFL-PCB-STATUS
    pub pasfl_pcb_status: FixedString<2>,
    /// PASFL-PCB-PROCOPT
    pub pasfl_pcb_procopt: FixedString<4>,
    /// FILLER PIC FILLER
    pub _filler_310: i32,
    /// PASFL-SEG-NAME
    pub pasfl_seg_name: FixedString<8>,
    /// PASFL-KEYFB-NAME
    pub pasfl_keyfb_name: i32,
    /// PASFL-NUM-SENSEGS
    pub pasfl_num_sensegs: i32,
    /// PASFL-KEYFB
    pub pasfl_keyfb: FixedString<100>,
}
impl std::fmt::Display for Pasflpcb {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}", self.pasfl_dbdname, self.pasfl_seg_level, self.pasfl_pcb_status, self.pasfl_pcb_procopt, self._filler_310, self.pasfl_seg_name, self.pasfl_keyfb_name, self.pasfl_num_sensegs, self.pasfl_keyfb)
    }
}
impl From<&str> for Pasflpcb {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Pasflpcb {
    fn from(_s: String) -> Self { Self::default() }
}
impl Pasflpcb {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone, Default, PartialEq)]
pub struct Padflpcb {
    /// PADFL-DBDNAME
    pub padfl_dbdname: FixedString<8>,
    /// PADFL-SEG-LEVEL
    pub padfl_seg_level: FixedString<2>,
    /// PADFL-PCB-STATUS
    pub padfl_pcb_status: FixedString<2>,
    /// PADFL-PCB-PROCOPT
    pub padfl_pcb_procopt: FixedString<4>,
    /// FILLER PIC FILLER
    pub _filler_336: i32,
    /// PADFL-SEG-NAME
    pub padfl_seg_name: FixedString<8>,
    /// PADFL-KEYFB-NAME
    pub padfl_keyfb_name: i32,
    /// PADFL-NUM-SENSEGS
    pub padfl_num_sensegs: i32,
    /// PADFL-KEYFB
    pub padfl_keyfb: FixedString<255>,
}
impl std::fmt::Display for Padflpcb {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}{}{}{}{}{}{}{}{}", self.padfl_dbdname, self.padfl_seg_level, self.padfl_pcb_status, self.padfl_pcb_procopt, self._filler_336, self.padfl_seg_name, self.padfl_keyfb_name, self.padfl_num_sensegs, self.padfl_keyfb)
    }
}
impl From<&str> for Padflpcb {
    fn from(_s: &str) -> Self { Self::default() }
}
impl From<String> for Padflpcb {
    fn from(_s: String) -> Self { Self::default() }
}
impl Padflpcb {
    pub fn as_str(&self) -> String { format!("{}", self) }
    pub fn as_bytes(&self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn as_bytes_mut(&mut self) -> Vec<u8> { format!("{}", self).into_bytes() }
    pub fn trimmed(&self) -> String { format!("{}", self).trim_end().to_string() }
}

#[derive(Debug, Clone)]
pub struct ProgramState {
    /// OPFIL1-REC
    pub opfil1_rec: FixedString<100>,
    /// OPFIL2-REC
    pub opfil2_rec: Opfil2Rec,
    /// ROOT-SEG-KEY
    pub root_seg_key: PackedDecimal<11> /* Signed */,
    /// CHILD-SEG-REC
    pub child_seg_rec: FixedString<200>,
    /// WS-VARIABLES
    pub ws_variables: WsVariables,
    /// WS-PGMNAME
    pub ws_pgmname: FixedString<8>,
    /// CURRENT-DATE
    pub current_date: u32,
    /// CURRENT-YYDDD
    pub current_yyddd: u32,
    /// WS-AUTH-DATE
    pub ws_auth_date: u32,
    /// WS-EXPIRY-DAYS
    pub ws_expiry_days: i32,
    /// WS-DAY-DIFF
    pub ws_day_diff: i32,
    /// IDX
    pub idx: i32,
    /// WS-CURR-APP-ID
    pub ws_curr_app_id: u64,
    /// WS-NO-CHKP
    pub ws_no_chkp: u32,
    /// WS-AUTH-SMRY-PROC-CNT
    pub ws_auth_smry_proc_cnt: u32,
    /// WS-TOT-REC-WRITTEN
    pub ws_tot_rec_written: i32,
    /// WS-NO-SUMRY-READ
    pub ws_no_sumry_read: i32,
    /// WS-NO-SUMRY-DELETED
    pub ws_no_sumry_deleted: i32,
    /// WS-NO-DTL-READ
    pub ws_no_dtl_read: i32,
    /// WS-NO-DTL-DELETED
    pub ws_no_dtl_deleted: i32,
    /// WS-ERR-FLG
    pub ws_err_flg: FixedString<1>,
    /// WS-END-OF-AUTHDB-FLAG
    pub ws_end_of_authdb_flag: FixedString<1>,
    /// WS-MORE-AUTHS-FLAG
    pub ws_more_auths_flag: FixedString<1>,
    /// WS-END-OF-ROOT-SEG
    pub ws_end_of_root_seg: FixedString<1>,
    /// WS-END-OF-CHILD-SEG
    pub ws_end_of_child_seg: FixedString<1>,
    /// WS-INFILE-STATUS
    pub ws_infile_status: FixedString<2>,
    /// WS-OUTFL1-STATUS
    pub ws_outfl1_status: FixedString<2>,
    /// WS-OUTFL2-STATUS
    pub ws_outfl2_status: FixedString<2>,
    /// WS-CUSTID-STATUS
    pub ws_custid_status: FixedString<2>,
    /// WK-CHKPT-ID
    pub wk_chkpt_id: WkChkptId,
    /// WK-CHKPT-ID-CTR
    pub wk_chkpt_id_ctr: u32,
    /// WS-IMS-VARIABLES
    pub ws_ims_variables: WsImsVariables,
    /// IMS-RETURN-CODE
    pub ims_return_code: FixedString<2>,
    /// WS-IMS-PSB-SCHD-FLG
    pub ws_ims_psb_schd_flg: FixedString<1>,
    /// ROOT-UNQUAL-SSA
    pub root_unqual_ssa: RootUnqualSsa,
    /// CHILD-UNQUAL-SSA
    pub child_unqual_ssa: ChildUnqualSsa,
    /// PRM-INFO
    pub prm_info: PrmInfo,
    /// P-EXPIRY-DAYS
    pub p_expiry_days: u32,
    /// P-CHKP-FREQ
    pub p_chkp_freq: FixedString<5>,
    /// P-CHKP-DIS-FREQ
    pub p_chkp_dis_freq: FixedString<5>,
    /// P-DEBUG-FLAG
    pub p_debug_flag: FixedString<1>,
    /// FUNC-CODES
    pub func_codes: FuncCodes,
    /// FUNC-GU
    pub func_gu: FixedString<4>,
    /// FUNC-GHU
    pub func_ghu: FixedString<4>,
    /// FUNC-GN
    pub func_gn: FixedString<4>,
    /// FUNC-GHN
    pub func_ghn: FixedString<4>,
    /// FUNC-GNP
    pub func_gnp: FixedString<4>,
    /// FUNC-GHNP
    pub func_ghnp: FixedString<4>,
    /// FUNC-REPL
    pub func_repl: FixedString<4>,
    /// FUNC-ISRT
    pub func_isrt: FixedString<4>,
    /// FUNC-DLET
    pub func_dlet: FixedString<4>,
    /// PARMCOUNT
    pub parmcount: i32,
    /// PENDING-AUTH-SUMMARY
    pub pending_auth_summary: PendingAuthSummary,
    /// PA-ACCT-ID
    pub pa_acct_id: PackedDecimal<11> /* Signed */,
    /// PA-CUST-ID
    pub pa_cust_id: u32,
    /// PA-AUTH-STATUS
    pub pa_auth_status: FixedString<1>,
    /// PA-ACCOUNT-STATUS
    pub pa_account_status: [FixedString<2>; 5],
    /// PA-CREDIT-LIMIT
    pub pa_credit_limit: PackedDecimal<11> /* Signed */,
    /// PA-CASH-LIMIT
    pub pa_cash_limit: PackedDecimal<11> /* Signed */,
    /// PA-CREDIT-BALANCE
    pub pa_credit_balance: PackedDecimal<11> /* Signed */,
    /// PA-CASH-BALANCE
    pub pa_cash_balance: PackedDecimal<11> /* Signed */,
    /// PA-APPROVED-AUTH-CNT
    pub pa_approved_auth_cnt: i32,
    /// PA-DECLINED-AUTH-CNT
    pub pa_declined_auth_cnt: i32,
    /// PA-APPROVED-AUTH-AMT
    pub pa_approved_auth_amt: PackedDecimal<11> /* Signed */,
    /// PA-DECLINED-AUTH-AMT
    pub pa_declined_auth_amt: PackedDecimal<11> /* Signed */,
    /// PENDING-AUTH-DETAILS
    pub pending_auth_details: PendingAuthDetails,
    /// PA-AUTHORIZATION-KEY
    pub pa_authorization_key: PaAuthorizationKey,
    /// PA-AUTH-DATE-9C
    pub pa_auth_date_9c: PackedDecimal<5> /* Signed */,
    /// PA-AUTH-TIME-9C
    pub pa_auth_time_9c: PackedDecimal<9> /* Signed */,
    /// PA-AUTH-ORIG-DATE
    pub pa_auth_orig_date: FixedString<6>,
    /// PA-AUTH-ORIG-TIME
    pub pa_auth_orig_time: FixedString<6>,
    /// PA-CARD-NUM
    pub pa_card_num: FixedString<16>,
    /// PA-AUTH-TYPE
    pub pa_auth_type: FixedString<4>,
    /// PA-CARD-EXPIRY-DATE
    pub pa_card_expiry_date: FixedString<4>,
    /// PA-MESSAGE-TYPE
    pub pa_message_type: FixedString<6>,
    /// PA-MESSAGE-SOURCE
    pub pa_message_source: FixedString<6>,
    /// PA-AUTH-ID-CODE
    pub pa_auth_id_code: FixedString<6>,
    /// PA-AUTH-RESP-CODE
    pub pa_auth_resp_code: FixedString<2>,
    /// PA-AUTH-RESP-REASON
    pub pa_auth_resp_reason: FixedString<4>,
    /// PA-PROCESSING-CODE
    pub pa_processing_code: u32,
    /// PA-TRANSACTION-AMT
    pub pa_transaction_amt: PackedDecimal<12> /* Signed */,
    /// PA-APPROVED-AMT
    pub pa_approved_amt: PackedDecimal<12> /* Signed */,
    /// PA-MERCHANT-CATAGORY-CODE
    pub pa_merchant_catagory_code: FixedString<4>,
    /// PA-ACQR-COUNTRY-CODE
    pub pa_acqr_country_code: FixedString<3>,
    /// PA-POS-ENTRY-MODE
    pub pa_pos_entry_mode: u32,
    /// PA-MERCHANT-ID
    pub pa_merchant_id: FixedString<15>,
    /// PA-MERCHANT-NAME
    pub pa_merchant_name: FixedString<22>,
    /// PA-MERCHANT-CITY
    pub pa_merchant_city: FixedString<13>,
    /// PA-MERCHANT-STATE
    pub pa_merchant_state: FixedString<2>,
    /// PA-MERCHANT-ZIP
    pub pa_merchant_zip: FixedString<9>,
    /// PA-TRANSACTION-ID
    pub pa_transaction_id: FixedString<15>,
    /// PA-MATCH-STATUS
    pub pa_match_status: FixedString<1>,
    /// PA-AUTH-FRAUD
    pub pa_auth_fraud: FixedString<1>,
    /// PA-FRAUD-RPT-DATE
    pub pa_fraud_rpt_date: FixedString<8>,
    /// LINKAGE: PAUTBPCB
    pub pautbpcb: Pautbpcb,
    /// LINKAGE: PASFLPCB
    pub pasflpcb: Pasflpcb,
    /// LINKAGE: PADFLPCB
    pub padflpcb: Padflpcb,
    /// RETURN-CODE special register
    pub return_code: i32,
    /// TALLY special register
    pub tally: i32,
    /// SORT-RETURN special register
    pub sort_return: i32,
    /// COB-CRT-STATUS special register
    pub cob_crt_status: i32,
    /// DEBUG-ITEM special register
    pub debug_item: FixedString<80>,
    /// NUMBER-OF-CALL-PARAMETERS special register
    pub number_of_call_parameters: i32,
    /// WHEN-COMPILED special register
    pub when_compiled: FixedString<16>,
}

impl Default for ProgramState {
    fn default() -> Self {
        Self {
            opfil1_rec: Default::default(),
            opfil2_rec: Default::default(),
            root_seg_key: Default::default(),
            child_seg_rec: Default::default(),
            ws_variables: Default::default(),
            ws_pgmname: Default::default(),
            current_date: Default::default(),
            current_yyddd: Default::default(),
            ws_auth_date: Default::default(),
            ws_expiry_days: Default::default(),
            ws_day_diff: Default::default(),
            idx: Default::default(),
            ws_curr_app_id: Default::default(),
            ws_no_chkp: Default::default(),
            ws_auth_smry_proc_cnt: Default::default(),
            ws_tot_rec_written: Default::default(),
            ws_no_sumry_read: Default::default(),
            ws_no_sumry_deleted: Default::default(),
            ws_no_dtl_read: Default::default(),
            ws_no_dtl_deleted: Default::default(),
            ws_err_flg: Default::default(),
            ws_end_of_authdb_flag: Default::default(),
            ws_more_auths_flag: Default::default(),
            ws_end_of_root_seg: Default::default(),
            ws_end_of_child_seg: Default::default(),
            ws_infile_status: Default::default(),
            ws_outfl1_status: Default::default(),
            ws_outfl2_status: Default::default(),
            ws_custid_status: Default::default(),
            wk_chkpt_id: Default::default(),
            wk_chkpt_id_ctr: Default::default(),
            ws_ims_variables: Default::default(),
            ims_return_code: Default::default(),
            ws_ims_psb_schd_flg: Default::default(),
            root_unqual_ssa: Default::default(),
            child_unqual_ssa: Default::default(),
            prm_info: Default::default(),
            p_expiry_days: Default::default(),
            p_chkp_freq: Default::default(),
            p_chkp_dis_freq: Default::default(),
            p_debug_flag: Default::default(),
            func_codes: Default::default(),
            func_gu: Default::default(),
            func_ghu: Default::default(),
            func_gn: Default::default(),
            func_ghn: Default::default(),
            func_gnp: Default::default(),
            func_ghnp: Default::default(),
            func_repl: Default::default(),
            func_isrt: Default::default(),
            func_dlet: Default::default(),
            parmcount: Default::default(),
            pending_auth_summary: Default::default(),
            pa_acct_id: Default::default(),
            pa_cust_id: Default::default(),
            pa_auth_status: Default::default(),
            pa_account_status: Default::default(),
            pa_credit_limit: Default::default(),
            pa_cash_limit: Default::default(),
            pa_credit_balance: Default::default(),
            pa_cash_balance: Default::default(),
            pa_approved_auth_cnt: Default::default(),
            pa_declined_auth_cnt: Default::default(),
            pa_approved_auth_amt: Default::default(),
            pa_declined_auth_amt: Default::default(),
            pending_auth_details: Default::default(),
            pa_authorization_key: Default::default(),
            pa_auth_date_9c: Default::default(),
            pa_auth_time_9c: Default::default(),
            pa_auth_orig_date: Default::default(),
            pa_auth_orig_time: Default::default(),
            pa_card_num: Default::default(),
            pa_auth_type: Default::default(),
            pa_card_expiry_date: Default::default(),
            pa_message_type: Default::default(),
            pa_message_source: Default::default(),
            pa_auth_id_code: Default::default(),
            pa_auth_resp_code: Default::default(),
            pa_auth_resp_reason: Default::default(),
            pa_processing_code: Default::default(),
            pa_transaction_amt: Default::default(),
            pa_approved_amt: Default::default(),
            pa_merchant_catagory_code: Default::default(),
            pa_acqr_country_code: Default::default(),
            pa_pos_entry_mode: Default::default(),
            pa_merchant_id: Default::default(),
            pa_merchant_name: Default::default(),
            pa_merchant_city: Default::default(),
            pa_merchant_state: Default::default(),
            pa_merchant_zip: Default::default(),
            pa_transaction_id: Default::default(),
            pa_match_status: Default::default(),
            pa_auth_fraud: Default::default(),
            pa_fraud_rpt_date: Default::default(),
            pautbpcb: Default::default(),
            pasflpcb: Default::default(),
            padflpcb: Default::default(),
            return_code: 0,
            tally: 0,
            sort_return: 0,
            cob_crt_status: 0,
            debug_item: Default::default(),
            number_of_call_parameters: 0,
            when_compiled: Default::default(),
        }
    }
}

/// PADFLPCB
fn p_padflpcb(state: &mut ProgramState) {
}

/// MAIN-PARA
fn p_main_para(state: &mut ProgramState) {
}

/// PADFLPCB
fn p_padflpcb_2(state: &mut ProgramState) {
    p_1000_initialize(state);
    p_1000_exit(state);
    p_2000_find_next_auth_summary(state);
    p_2000_exit(state);
    p_4000_file_close(state);
    p_4000_exit(state);
    return;
}

/// 1000-INITIALIZE
fn p_1000_initialize(state: &mut ProgramState) {
    {
    let _now = Local::now();
    let _ds = _now.format("%y%m%d").to_string();
    state.ws_variables.current_date = _ds.parse().unwrap_or_default();
    }
    // ACCEPT CURRENT-YYDDD FROM DAY
    println!("{}", "STARTING PROGRAM DBUNLDGS::");
    println!("{}", "*-------------------------------------*");
    println!("{}{}", "TODAYS DATE            :", state.ws_variables.current_date);
    println!("{}", " ");
}

/// 1000-EXIT
fn p_1000_exit(state: &mut ProgramState) {
}

/// 2000-FIND-NEXT-AUTH-SUMMARY
fn p_2000_find_next_auth_summary(state: &mut ProgramState) {
    state.pautbpcb.paut_pcb_status = Default::default();
    {
        let mut _p1 = (state.func_codes.func_gn).clone();
        let mut _p2 = (state.pautbpcb).clone();
        let mut _p3 = (state.pending_auth_summary).clone();
        let mut _p4 = (state.root_unqual_ssa).clone();
        cbltdli(&mut _p1, &mut _p2, &mut _p3, &mut _p4);
        state.func_codes.func_gn = _p1;
        state.pautbpcb = _p2;
        state.pending_auth_summary = _p3;
        state.root_unqual_ssa = _p4;
    }
    if state.pautbpcb.paut_pcb_status.trimmed() == " " {
        state.ws_variables.ws_no_sumry_read += 1 as i32;
        state.ws_variables.ws_auth_smry_proc_cnt += 1 as u32;
        state.opfil1_rec = FixedString::copy_from(&state.pending_auth_summary);
        state.opfil2_rec.root_seg_key = Default::default();
        state.opfil2_rec.child_seg_rec = Default::default();
        // SKIP: unresolved ref
        if state.pending_auth_summary.pa_acct_id.value != 0 {
        }
        p_3100_insert_parent_seg_gsam(state);
        p_3100_exit(state);
        state.ws_variables.ws_end_of_child_seg = Default::default();
        p_3000_find_next_auth_dtl(state);
        p_3000_exit(state);
    }
    if &format!("{}", state.pautbpcb.paut_pcb_status) == &"GB".to_string() {
        state.ws_variables.ws_end_of_authdb_flag = "Y".into();
        state.ws_variables.ws_end_of_root_seg = "Y".into();
    }
    // SKIP: unresolved condition
}

/// 2000-EXIT
fn p_2000_exit(state: &mut ProgramState) {
}

/// 3000-FIND-NEXT-AUTH-DTL
fn p_3000_find_next_auth_dtl(state: &mut ProgramState) {
    {
        let mut _p1 = (state.func_codes.func_gnp).clone();
        let mut _p2 = (state.pautbpcb).clone();
        let mut _p3 = (state.pending_auth_details).clone();
        let mut _p4 = (state.child_unqual_ssa).clone();
        cbltdli(&mut _p1, &mut _p2, &mut _p3, &mut _p4);
        state.func_codes.func_gnp = _p1;
        state.pautbpcb = _p2;
        state.pending_auth_details = _p3;
        state.child_unqual_ssa = _p4;
    }
    if state.pautbpcb.paut_pcb_status.trimmed() == " " {
        state.ws_variables.ws_more_auths_flag = "Y".into();
        state.ws_variables.ws_no_sumry_read += 1 as i32;
        state.ws_variables.ws_auth_smry_proc_cnt += 1 as u32;
        // SKIP: unresolved ref
        p_3200_insert_child_seg_gsam(state);
        p_3200_exit(state);
    }
    if &format!("{}", state.pautbpcb.paut_pcb_status) == &"GE".to_string() {
        state.ws_variables.ws_end_of_child_seg = "Y".into();
        println!("{}{}", "CHILD SEG FLAG GE : ", state.ws_variables.ws_end_of_child_seg);
    }
    // SKIP: unresolved condition
    state.pautbpcb.paut_pcb_status = Default::default();
}

/// 3000-EXIT
fn p_3000_exit(state: &mut ProgramState) {
}

/// 3100-INSERT-PARENT-SEG-GSAM
fn p_3100_insert_parent_seg_gsam(state: &mut ProgramState) {
    {
        let mut _p1 = (state.func_codes.func_isrt).clone();
        let mut _p2 = (state.pasflpcb).clone();
        let mut _p3 = (state.pending_auth_summary).clone();
        let mut _p4: i64 = 0;
        cbltdli(&mut _p1, &mut _p2, &mut _p3, &mut _p4);
        state.func_codes.func_isrt = _p1;
        state.pasflpcb = _p2;
        state.pending_auth_summary = _p3;
    }
    if state.pasflpcb.pasfl_pcb_status.trimmed() != " " {
        println!("{}{}", "GSAM PARENT FAIL :", state.pasflpcb.pasfl_pcb_status);
        println!("{}{}", "KFB AREA IN GSAM:", state.pasflpcb.pasfl_keyfb);
        p_9999_abend(state);
    }
}

/// 3100-EXIT
fn p_3100_exit(state: &mut ProgramState) {
}

/// 3200-INSERT-CHILD-SEG-GSAM
fn p_3200_insert_child_seg_gsam(state: &mut ProgramState) {
    {
        let mut _p1 = (state.func_codes.func_isrt).clone();
        let mut _p2 = (state.padflpcb).clone();
        let mut _p3 = (state.pending_auth_details).clone();
        let mut _p4: i64 = 0;
        cbltdli(&mut _p1, &mut _p2, &mut _p3, &mut _p4);
        state.func_codes.func_isrt = _p1;
        state.padflpcb = _p2;
        state.pending_auth_details = _p3;
    }
    if state.padflpcb.padfl_pcb_status.trimmed() != " " {
        println!("{}{}", "GSAM PARENT FAIL :", state.padflpcb.padfl_pcb_status);
        println!("{}{}", "KFB AREA IN GSAM:", state.padflpcb.padfl_keyfb);
        p_9999_abend(state);
    }
}

/// 3200-EXIT
fn p_3200_exit(state: &mut ProgramState) {
}

/// 4000-FILE-CLOSE
fn p_4000_file_close(state: &mut ProgramState) {
    println!("{}", "CLOSING THE FILE");
}

/// 4000-EXIT
fn p_4000_exit(state: &mut ProgramState) {
}

/// 9999-ABEND
fn p_9999_abend(state: &mut ProgramState) {
    println!("{}", "DBUNLDGS ABENDING ...");
    state.return_code = 16 as i32;
    return;
}

/// 9999-EXIT
fn p_9999_exit(state: &mut ProgramState) {
}

// ── Runtime Stubs ──────────────────────────────────────────────

/// External: CALL 'CBLTDLI'
fn cbltdli(_param1: &mut impl std::fmt::Debug, _param2: &mut impl std::fmt::Debug, _param3: &mut impl std::fmt::Debug, _param4: &mut impl std::fmt::Debug) {
    todo!("External subroutine 'CBLTDLI' not yet linked — implement or link the CBLTDLI module")
}

fn main() {
    let mut state = ProgramState::default();
    p_padflpcb(&mut state);
}

